### ISSUE TITLE
API is not Thread-Safe

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#10]
There appears to be some unsafe code lurking about.  I have run tests and they will pass sometimes, but not others (usually just one).  Running the failed test again passes successfully, so this is sign of a (unsafe) threading issue.

**Comment by wojtpl2** [comment]
I think that my code without your changes was thread-safe. I've never had this situation. But you never know. 
I think your changes in this topic are good and solved this proplem.

**Comment by Mike-EEE** [comment]
Yes threading is soooooooo tricky.  I've basically spent the past year learning about it.  xUnit is absolutely fantastic in this regard because it is parallel by default.  Like I said it is random and occurs every once and a while.  If you run enough tests over and over you should see it.

The one thing I haven't done yet is use a `ConditionalWeakTable` on the type definitions.  I will submit this and some other adjustments I made.

**Comment by wojtpl2** [comment]
I think that this issue is done.
