### ISSUE TITLE
Tests for different configuration

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#100]
Currently we have only 1 configuration for 1 case. We should have many configuration (with namespace, auto property, default) for 1 test. 
What do you think?

**Comment by Mike-EEE** [comment]
Agreed. I am never going to say less tests are better! :)  We definitely need to flesh out the tests, for sure.  Tests have always been a point of constant improvement for me, so they are not the best (or most comprehensive), unfortunately.

I was basically offline for 3 days... just got back online now. 😮  I refreshed my entire environment, machine and all.  Turns out overclocked non-qualified memory is what was causing all my problems with https://github.com/dotnet/BenchmarkDotNet/issues/433.  I am hoping to get everything back online and together again by this weekend and then I can start back on where I left off here with EXS. 😎

**Comment by wojtpl2** [comment]
I've tried below class, but it is not the best solution. Do you have a better idea?
```C#
public class ExtendeXmlSerializerTests
    {
        const string HelloWorld = "Hello World!";
        public static IExtendedXmlSerializer ClassicModeSerializer = new ConfigurationContainer().EnableClassicMode().Create();
        public static IExtendedXmlSerializer AutoFormattingSerializer = new ConfigurationContainer().UseAutoFormatting().Create();

        [Theory]
        [MemberData(nameof(SplitCountData))]
        public void MultiTest(object obj, IExtendedXmlSerializer serializer, string xml)
        {
            var data = serializer.Serialize(obj);
            Assert.Equal(
                xml,
                data);
            var actual = serializer.Deserialize(data);
            obj.ShouldBeEquivalentTo(actual);
     }

        public static IEnumerable<object[]> SplitCountData
        {
            get
            {
                return new[]
                {
                new object[] { 6776, ClassicModeSerializer, @"<?xml version=""1.0"" encoding=""utf-8""?><int xmlns=""https://extendedxmlserializer.github.io/system"">6776</int>" },
                new object[] { 6776, AutoFormattingSerializer, @"<?xml version=""1.0"" encoding=""utf-8""?><int xmlns=""https://extendedxmlserializer.github.io/system"">6776</int>" },
                new object[] { new ExtendedXmlSerializerTests.SimpleNestedClass {PropertyName = HelloWorld}, ClassicModeSerializer, @"<?xml version=""1.0"" encoding=""utf-8""?><ExtendedXmlSerializerTests-SimpleNestedClass xmlns=""clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel.Xml;assembly=ExtendedXmlSerializer.Tests""><PropertyName>Hello World!</PropertyName></ExtendedXmlSerializerTests-SimpleNestedClass>", },
                new object[] { new ExtendedXmlSerializerTests.SimpleNestedClass {PropertyName = HelloWorld}, AutoFormattingSerializer, @"<?xml version=""1.0"" encoding=""utf-8""?><ExtendedXmlSerializerTests-SimpleNestedClass PropertyName=""Hello World!"" xmlns=""clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel.Xml;assembly=ExtendedXmlSerializer.Tests"" />", },
                };
            }
        }
    }
```

**Comment by Mike-EEE** [comment]
Oh man, yeah that's a good one... I haven't had much experience with this, but doesn't xUnit support its own data-provider infrastructure?  We could possibly make our own attributes to help out, just a thought.

I was also thinking AutoFixture might be a good answer, but it still doesn't support .NET Core (or doesn't look like it does), and it appears that the owner just moved onto better things. :(

**Comment by Mike-EEE** [comment]
Just got bit with this w/ #146.  The extensibility framework is a pretty decent first stab, but there are indeed chances that all extensions will not align properly.  It's not too difficult to fix these (missed) alignments, but it would be nice to have improvements in the framework (maybe at a later date/rewrite/version) that do account for this in an elegant way.  More of a pipeline-type orchestration in compiling all the elements from configuration.

**Comment by Mike-EEE** [comment]
Going to close this issue as it will be handled better by v3.  Or should be. 😄
