### ISSUE TITLE
Getting System.ArgumentException calling to Serialize

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#101]
I'm getting this:

![sin titulo](https://cloud.githubusercontent.com/assets/3109851/25524693/ecec31e8-2c0b-11e7-8afd-f3756fa10ba1.png)

You can reproduce it with this zipped solution. Run XamlLoadTest and you will see.
[OmniXaml.zip](https://github.com/wojtpl2/ExtendedXmlSerializer/files/964042/OmniXaml.zip)

> {System.ArgumentException: Incorrect number of arguments supplied for call to method 'Void Add(System.Object, System.Object)'
> Parameter name: method
>    at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
>    at ExtendedXmlSerialization.Cache.ObjectAccessors.CreateMethodAddToDictionary(Type type)
>    at ExtendedXmlSerialization.Cache.TypeDefinition..ctor(Type type)
>    at ExtendedXmlSerialization.Cache.TypeDefinitionCache.<>c.<GetDefinition>b__3_0(Type t)
>    at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
>    at ExtendedXmlSerialization.Cache.PropertieDefinition..ctor(Type type, PropertyInfo propertyInfo, String name)
>    at ExtendedXmlSerialization.Cache.TypeDefinition.GetPropertieToSerialze()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at ExtendedXmlSerialization.ExtendedXmlSerializer.WriteXml(XmlWriter writer, Object o, TypeDefinition type, String name, Boolean writeReservedObject, Boolean forceSaveType)
>    at ExtendedXmlSerialization.ExtendedXmlSerializer.Serialize(Object o)
>    at XamlLoadTest.Program.ShowResult(Object instance) in F:\Source\Repos\OmniGUI\OmniXAML\XamlLoadTest\Program.cs:line 29
>    at XamlLoadTest.Program.Main(String[] args) in F:\Source\Repos\OmniGUI\OmniXAML\XamlLoadTest\Program.cs:line 23}	System.ArgumentException
>

**Comment by wojtpl2** [comment]
Can you try 2.0 alpha3 version?
In near future we will move to version 2.0. It is completely rewritten version.

**Comment by Mike-EEE** [comment]
WOWWWWWWWW.... we have superstars sniffing around our bits. 😄 what's up @SuperJMN?  I feel sort of sheepish saying that I work on an Xml serializer now, but I swear it "just happened!" 😆 

I was actually going to make an announcement and such, whenever I got this sucker completed for v2.0.  *IF* I ever complete it, LOL.  Anyways, were you able to try alpha-3?  I am not sure if it works, and I got caught up in a bit of an environmental upgrade/ordeal this past week (not to mention I am in a bit of a refactor on the current task), so I am a bit behind on where I would like this right now.

In any case, it would be interesting/helpful to know if you were able to get benchmarks out of the latest. 👍

**Comment by SuperJMN** [comment]
Hey @Mike-EEE !! Glad to see you! How is it going? To say the truth, I'm using this to test OmniXAML v2. I'm going through A LOT of refinements and design changes in order to cover all the common use cases like namescopes (that are a pain in the ass). I created a console application that given a XAML, it parses the result and shows the resulting object several forms, like JSON and XML. It makes me test easier, but I have a problem: my testing object model has a dictionary :( so I cannot make a XML out of it. I'm going to try v2 right now :) Let me run it! I'll come with the results.

**Comment by SuperJMN** [comment]
I have tried 2.0 alpha 3 with this code. It runs, but I'm getting an empty string :(

 ```
            var sb = new StringBuilder();
            var cc = new ConfigurationContainer();
            cc.Create().Serialize(XmlWriter.Create(new StringWriter(sb)), instance);
            Console.Write(sb.ToString());
```

**Comment by Mike-EEE** [comment]
Cooooool, that sounds great, @SuperJMN!  Are you saying that you cannot make a dictionary out of EXS?  It is definitely supported, but admittedly happy path.

If you are getting an empty string, you might have to call `Flush` on the `XmlWriter`.

(My environment is currently being reconstructed so I am using email for now.  Hopefully formatting/mentions work as expected.)
________________________________

**Comment by SuperJMN** [comment]
Wow, it works as expected! It looks like I'm not too used to dealing with buffered things :) I get the XML now! Look the output at the bottom of the snapshot.

![sin titulo](https://cloud.githubusercontent.com/assets/3109851/25947738/fa4d8374-3650-11e7-9106-d727d43f0e46.png)

It seems you're doing a GREAT job with this ExtenedXmlSerializer!

Big thanks!

BTW, if you want to get in touch, just look for my nickname in Skype. See you, Mike! :D

**Comment by wojtpl2** [comment]
You can use:
`new ConfigurationContainer().UseOptimizedNamespaces().Create();`
If you want to optimize namespaces.

**Comment by Mike-EEE** [comment]
That's great!  Very awesome to hear!  We have a lot of work still to go, but it is showing some promise in some areas.  I will definitely add you on Skype and see you on your [Gitter](https://gitter.im/SuperJMN/OmniXAML)!

(Btw @wojtpl2 we also need a Gitter. 😄)

**Comment by Mike-EEE** [comment]
Haha ok yeah, I think we figured this one out.  Feel free to stop by anytime, @SuperJMN!
