### ISSUE TITLE
ExtendedXmlSerializer.Samples program doesn't work

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#102]
CustomSerializatorSamples and MigrationMapSamples don't work.

**Comment by wojtpl2** [comment]
I use this Sample program to generate documentation.
I cut the pieces of code and insert them into the code.. I also use the resulting xml.

**Comment by wojtpl2** [comment]
I've fixed CustomSerializatorSamples.

**Comment by wojtpl2** [comment]
I've fixed MigrationMapSamples too.

**Comment by Mike-EEE** [comment]
Hey great to hear.  I am still neck deep in moving chaos here.  Starting to see the end of it, however.  It might spill into next week, unfortunately.  Will keep you updated!
