### ISSUE TITLE
Xaml Standard

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#103]
Still treading water here (maybe sinking a little too 😆) at the moment, but still actively thinking about this project when I can.

Have you seen this?
https://github.com/Microsoft/xaml-standard

I think it would be cool to somehow become a Xaml Standard-compliant serializer.  It would look something like what we have with markup extensions:

```
var serializer = new ConfigurationContainer().EnableXamlStandardCompliance().Create();
// ...
```

Something to think about. 😄

**Comment by wojtpl2** [comment]
It looks great.

**Comment by Mike-EEE** [comment]
After getting schooled in the Xaml Standard repo in regards to what it actually is about, this doesn't make much sense, unfortunately.  Xaml Standard is primarily geared towards consolidating vocabularies between Xamarin.Forms and UWP.  If we can figure out a way to tie into this, we can open up a new issue for discussion and inclusion for a future version.  Closing this for now.
