### ISSUE TITLE
use base class property as id for references in v2

### ISSUE THREAD

**Issue by InvalidCast44** [wojtpl2/ExtendedXmlSerializer#104]
hi!

this
`new ConfigurationContainer()
                                           .ConfigureType<SampleClass>()
                                           .EnableReferences(p => p.Name)`

with Name property in SampleClass works well, as in v1.5
the generated xml use the string property Name

one thing that worked in v1.5 was:
- having a base class with Name property
- configuring for this base class, and NOT for any of its child classes
- the serialization handled well Name property for ALL of child classes

in v2, you can't configure as id, a property defined in a base class, EVEN if you configure the child class directly: an int id is used instead

ex:

`public class ParentClass
{
   public string Name{get;set;}
}`

`public ChildClass : ParentClass{}`

then:

`new ConfigurationContainer()
                                           .ConfigureType<ChildClass>()
                                           .EnableReferences(p => p.Name)`

won't work, neither

`new ConfigurationContainer()
                                           .ConfigureType<ParentClass>()
                                           .EnableReferences(p => p.Name)`

i tried to use abstract or virtual to override the property in the child class

in some cases, exception are thrown to say member cannot be found, in others, int id is used.

so for the moment, i would have:
- to remove my base class
- add an interface with contains Name property
- get all types in my assembly that implements this interface
- configure all these types

that's a little cumbersome, and works only in this case because all used types are in the same assembly

**Comment by wojtpl2** [comment]
Thanks for reporting!
Can you make pull request with test for it ?

**Comment by InvalidCast44** [comment]
i'm new to github, but i will do my best.
maybe you have a good link which teach how to do it properly?

**Comment by wojtpl2** [comment]
There is good video https://www.youtube.com/watch?v=YTbRzhQju4c

1. You have to fork this repo
2. Clone your forked repo in you computer 
3. Make your changes
4. Push the changes to your repo
5. Make pull request

**Comment by InvalidCast44** [comment]
i'm sorry: although i'm able to fork, clone, and compile main branch on my machine, i'm not able to do it for branch 2.0.0
compilation problems, for ex using Microsoft.DotNet.ProjectModel is causing trouble in ExtendedXmlSerializer.Tests and AnalyzerOptions in OptimizedNamespaceExtensionTests.

also vs2017 force me to migrate your proj files

i won't be able able to help you.

but it's simple.


`public class ParentClass {public string Name{get;set;}}`

`public class ChildClass : ParentClass {}`

1) configure like this:

`new ConfigurationContainer() .ConfigureType<ParentClass>() .EnableReferences(p => p.Name)`

and serialize an instance of ParentClass
and check that this work: in output xml, Name is used as reference key.
you can copy the output xml: it should be the result for the following test

1) configure like this:

`new ConfigurationContainer() .ConfigureType<ParentClass>() .EnableReferences(p => p.Name)`

BUT serialize an instance of ChildClass: see that Name is not used for key

**Comment by Mike-EEE** [comment]
Ahhh yes we have not officially made the jump to VS2017 yet, @InvalidCast44.  I have been hit with a massive wave of Real Life distractions for the past few weeks.  I should be back online this week and will look into your issue when I can.

Thank you for letting us know! 👍   I will follow up here with any questions that I have.

**Comment by Mike-EEE** [comment]
Looking into this now.  Glad you brought this up @InvalidCast44 ... looks like there are a couple issues here.  Will update this thread when addressed. 👍

**Comment by Mike-EEE** [comment]
Alright, I was able to address these issues.  Turns out it was an easy fix as we had already accounted for members between hierarchies, it's just that our attribute extension was not configured to use it. :)  I've checked in the latest.  We should be able to release this tomorrow for Alpha 4, hopefully.  Please feel free to comment on this issue if you have any questions and/or run into any additional problems around this.  Once again, great find.  Thanks again for reporting it!
