### ISSUE TITLE
Encrypt Configuration - Order of function calls

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#105]
If you want to configure Encrypt you have to call function in one way:
```c#
new ConfigurationContainer()
	.UseEncryptionAlgorithm()
	.ConfigureType<TestClassWithEncryptedData>()
	.Member(p => p.Password, x => x.Encrypt())
	.Member(p => p.Salary).Encrypt().Owner.Configuration;
```
You have to call `UseEncryptionAlgorithm()` before `ConfigureType()`
If you want to configure in different way you get exception. 
```C#
var config = new ConfigurationContainer();
config.ConfigureType<Type1>().Member(p => p.Password, x => x.Encrypt());
config.ConfigureType<Type2>().Member(p => p.Password, x => x.Encrypt());
config.UseEncryptionAlgorithm(new CustomEncryption())
var serializer = config.Create()
```
I think It should be work.

**Comment by wojtpl2** [comment]
I created test case "ConfigureEncryptDifferenetOrder".

**Comment by Mike-EEE** [comment]
FWIW, I currently have this test commented out as it is dependent on #109 being completed.

**Comment by Mike-EEE** [comment]
This has been addressed and works better with the new API.  Please go ahead and try it out and let me know what you think.  Hope it's better for you now. 😄

**Comment by Mike-EEE** [comment]
This should now be addressed.  Please feel free to comment/reopen if not and we will proceed from there.
