### ISSUE TITLE
Too difficult IEncryption interface

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#106]
If you want to create custom encryption algorithm you have to create object inheriting from IEncryption interface.

If you create object inheriting from IEncryption you have to implement methods:
```C#
    public class CustomEncryption : IEncryption
    {
        public string Parse(string data)
        {
            throw new NotImplementedException();
        }

        public string Format(string instance)
        {
            throw new NotImplementedException();
        }

        public bool IsSatisfiedBy(TypeInfo parameter)
        {
            throw new NotImplementedException();
        }
    }
```

For me users shouldn't implement IsSatisfiedBy. We need to change interfate of IEncryption or expose abstract object with implementation of IsSatisfiedBy.

In example project I did work around:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/samples/ExtendedXmlSerializer.Samples/Encrypt/EncryptSamples.cs#L86-L97 

```C#
public class CustomEncryption : ConverterBase<string>, IEncryption
{
}
```
But it isn't the best idea.

**Comment by Mike-EEE** [comment]
Hmm... that does seem odd.  Will definitely look into this.

**Comment by Mike-EEE** [comment]
Alright, made a base interface `IConvert` that is used for parsing/formatting.  Simple fix that simplifies implementations.  Please let me know if there are any other issues around this one and we can take a look at it.
