### ISSUE TITLE
Support .NETStandard 1.3 as Minimum Level

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#107]
Currently EXS supports .NETStandard 1.6, which is a beefy set of APIs, and precludes from using it in portable scenarios (such as Xamarin, etc).   The idea here is to make the code more portable so it can be used in essentially any .NET scenario.

(Please also feel free to let me know if I have this wrong and/or misunderstood something.)

**Comment by wojtpl2** [comment]
It will be great, but I tried use minimum level. I use something .NETStandard 1.6. I don't remember but I think it is reflection in read properties or generating dynamic gets and sets.

**Comment by Mike-EEE** [comment]
Yeah, I am concerned it might turn into an involved work, but I think it will be good/beneficial going forward.  Other serializers are 1.3.

**Comment by Mike-EEE** [comment]
This is based on an inaccurate understanding of .NET Standard.  Please see #92 for more details.

**Comment by Mike-EEE** [comment]
Re-opening this as this indeed was understood correctly the first time (hate when that happens. ;) ).

**Comment by Mike-EEE** [comment]
I am thinking this makes a better v3 feature.  Closing for now until we get inspired to make such a version. :)
