### ISSUE TITLE
UseAutoFormatting not support nullable types

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#108]
If I have configuration:
`new ConfigurationContainer().UseAutoFormatting().Create()`
And Class:
```C#
	    class TestClass
	    {
	        public int Int { get; set; }
	    }
```
Then I'll get xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoMemberFormatExtensionTests-TestClass Int="2" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel.Xml;assembly=ExtendedXmlSerializer.Tests" />
```

But if I change property type to nullable type:
```C#
	    class TestClass
	    {
	        public int? Int { get; set; }
	    }
```
Then I'll get xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoMemberFormatExtensionTests-TestClass xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel.Xml;assembly=ExtendedXmlSerializer.Tests">
  <Int>2</Int>
</AutoMemberFormatExtensionTests-TestClass>
```

I've added unit test for this case: 'VerifyAutoFormattingForNullableWithValue'

**Comment by Mike-EEE** [comment]
OK I just fixed this one. I had to update the `[VerifyAutoFormattingForNullableWithValue](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/Xml/AutoMemberFormatExtensionTests.cs#L54)`'s expected XML as it had properties that were not in the class.  Please let me know if I misunderstood something and/or if this requires more work.
