### ISSUE TITLE
Add Support for Read-only Collection Properties

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#11]
As mentioned in https://github.com/wojtpl2/ExtendedXmlSerializer/issues/7#issuecomment-263023573, it would be ideal to support read-only collection properties.  I will be taking a look at this and submitting a PR if successful.

**Comment by wojtpl2** [comment]
Thanks for your changes!

**Comment by Mike-EEE** [comment]
Sure thing.  So cool to see this project.  Spending so much time configuring and/or trying to figure out how to get DataContractSerializer to "just work" has grown tired on me.  Especially when there's JSON.NET and of course the granddaddy Xaml serializers that will take objects and _just put it in a freaking file_!  There so needs to be something like that for XML so I am more than supportive of this!

**Comment by wojtpl2** [comment]
It will be fixed in version above 1.4.1.
