### ISSUE TITLE
Aplha version2 Deserialization xml from standard XMLSerializer

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#110]
I was thinking about v2 and I have one thing.
One of our support features is:
* Deserialization xml from standard XMLSerializer

In V1.5 you can use ExtendedXmlSerializer instead of standard XmlSerializer. After use ExtendedXmlSerializer you were able to read old xml. But in v2 it isn't true. 

We should talk it over.

**Comment by wojtpl2** [comment]
We have to remove "Deserialization xml from standard XMLSerializer" from our support feature list or we need to support it.

**Comment by Mike-EEE** [comment]
No I agree I thought this was a cool feature.  Let's see if we can make this work.

**Comment by wojtpl2** [comment]
I agree with you that xml from v2 are better.
But some people want to xml which looks like from standard XMLSerializer.

For me we can remove this feature but I want to know your opinion.

**Comment by Mike-EEE** [comment]
Is there a test that fails here that you have in mind?  From what I know, as long as it follows legacy XML it should serialize/deserialize OK.  For example, I just serialized the example from #111 (with legacy XML attributes) and it worked no problem.

**Comment by Mike-EEE** [comment]
Moving this to Alpha 5 as all other items have been accounted for and this is more of a feature than bug.  We can post Alpha 4 to NuGet if you like. :)

**Comment by wojtpl2** [comment]
Ok. I would like to release Alpha 4. Where is the code? on v2.0.0 or restart branch?

**Comment by Mike-EEE** [comment]
V2.0.0.0.  Restart did not start haha.  I will delete it if that is ok with you.

Sent from my Windows 10 phone

**Comment by wojtpl2** [comment]
Let's delete it ;)

**Comment by Mike-EEE** [comment]
Done. 👍

**Comment by wojtpl2** [comment]
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha4
Have you seen preview version of nuget page?
https://preview.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha4

**Comment by Mike-EEE** [comment]
Wow super cool!  That looks pretty good. :)  Guess I should start working on that new FluentAPI now huh?  Hehehe.

**Comment by Mike-EEE** [comment]
Btw, Visual Studio released their 15.3 Preview 7 today!

**Comment by Mike-EEE** [comment]
As far as I know this is working with the old XMLSerializer.  If there is a scenario you find that is not working as expected, please create a broken test highlighting the issue and I will fix it/them. 👍
