### ISSUE TITLE
 Message "The empty string '' is not a valid local name." Issue

### ISSUE THREAD

**Issue by jayonsoftware** [wojtpl2/ExtendedXmlSerializer#111]
I am trying to serialize an object and getting the above error message. Any thoughts on what is causing the issue.

**Comment by Mike-EEE** [comment]
Thanks for reporting this @jayonsoftware.  Do you know if you are using the [the v2.0 alpha](https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha3)?  If so, would it be possible to provide a sample Xml that reproduces this exception?

After a little bit of personal time to sort out some issues, I am diving back into this project for the foreseeable future, so I will be able to address it with the rest of the issues that have been reported against 2.0. 👍

**Comment by wojtpl2** [comment]
Can you provide also a class which you get this error message and Xml?

**Comment by Mike-EEE** [comment]
Haha!  Yes, class as well would be helpful, too.  Like I said, brushing off the dust here. 👼

**Comment by jayonsoftware** [comment]
Sorry for the delay, here is the code. 

`using ExtendedXmlSerialization;

namespace ServiceStackRest.LoginRequest
{
    public class LoginRequest
    {
        public LoginRequest()
        {

            var request = new Envelope
            {

                Body = new EnvelopeBody
                {
                    login = new login
                    {
                        password = "abc",
                        username = "abc"
                    }
                }
            };
            ExtendedXmlSerializer serializer = new ExtendedXmlSerializer();
            // Serializaion Fails. 
            var xml = serializer.Serialize(request);
            System.Console.WriteLine(xml);
        }
    }


    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
    public partial class Envelope
    {

        private object headerField;

        private EnvelopeBody bodyField;

        /// <remarks/>
        public object Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public EnvelopeBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public partial class EnvelopeBody
    {

        private login loginField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:tooling.soap.sforce.com")]
        public login login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:tooling.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:tooling.soap.sforce.com", IsNullable = false)]
    public partial class login
    {

        private string usernameField;

        private string passwordField;

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }


}
`

**Comment by jayonsoftware** [comment]
Looks like the errors are due to the Attributes, if I remove them all works fine. The issue with 

XmlRootAttribute

**Comment by Mike-EEE** [comment]
OK this appears to be v1.0 code.  I will verify that this works with v2.0 with the next round of bug fixes to be sure.  Thanks again for reporting, @jayonsoftware. 👍

**Comment by Mike-EEE** [comment]
Alright... this was still a problem in the latest v2 code and has been fixed in v2.0.0 branch.  Please let me know if there is anything further with this issue and/or feel free to open a new issue if you find any additional problems.  Thanks for reporting this, @jayonsoftware!
