### ISSUE TITLE
Enable Platform-Specific Resourcing (ditch the #defs)

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#112]
Now that VS2017 is out (#92), it might be worth exploring a more structured/discoverable way to introduce and locate platform-specific resources and dependencies.

One thought is to use convention by default, and do a test for an assembly that has the same name as the current assembly + `Platforms` + moniker.  So, in the case of `ExtendedXmlSerializer`:

- `ExtendedXmlSerializer.Platforms.NetCore` <== .NET Core
- `ExtendedXmlSerializer.Platforms.NetFramework` <== .NET Framework

Additionally, once the assembly has been resolved and located, a simple call to register it with the current (internal) container (enabling the use of an [ICompositionRoot](https://github.com/seesharper/LightInject/wiki/Getting-started#compositionroot)) would be a very straight forward task.

**Advantages of this approach:**

- No more #defines (!)
- Clean separation of platform concerns

**Disadvantages:**

- Two more assemblies to account for in our solution and for NuGet.
- ? (Additional feedback welcomed)

**Comment by wojtpl2** [comment]
It is bad idea.
In this way you need to two project for test:
ExtendedXmlSerializer.Tests.Platforms.NetCore
ExtendedXmlSerializer.Tests.Platforms.NetFramework

And of course you need to `core` projects

ExtendedXmlSerializer.Core
ExtendedXmlSerializer.Tests.Core

And if you want to create function for specific framework, you have to think "how can I do this".
Eg:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/a12ee8bc2bbb6c5f6f68658400bca91765859719/src/ExtendedXmlSerializer/Cache/TypeDefinitionCache.cs#L54-L82

I know it could be done, but it is unnecessary work.
For me we have to wait for working VS2017. If VS2015 is better for us we should still use VS2015. In this case your approach is not pragmatic. 

I don't like #defines either but Resharper and VS2015/VS2017 support it now. This is better than split the project into several.

**Comment by wojtpl2** [comment]
There is examples of this approach:
https://www.nuget.org/packages/autofac
https://www.nuget.org/packages/fluentvalidation
https://www.nuget.org/packages/automapper

**Comment by Mike-EEE** [comment]
LOL end of discussion? 😄  Hehe... yeah, it's a bit more work, but more challenging.  You are correct though... we already have plenty enough challenges enough as it is.

I would recommend VS2015 but unfortunately VS2017 is the future, and provides insight where things are going.  While rough, it's good to get a head start.  Keep in mind I thought the same thing about Silverlight! 😆 

Consider the problem we have now:

- `ExtendedXmlSerializer` can be made a 1.x .NET Standard library.  This simplifies things greatly.  By default this supports .NETFramework 4.x AND .NET Core 1.x.  However, the problem we run into is the above.  We could still do `<TargetFrameworks>net4x;netcoreapp1.x</TargetFrameworks>` (basically 2 builds per assembly like we did in VS2015) but this goes against what .NET Standard is supposed to be about.

Also consider that what I am suggesting does not involve or change testing in any way.  You would only be concerned with three assemblies total (I've thought more about the names and are reflected below -- _also, these are merely thoughts and discussion not implying action_):

- ExtendedXmlSerializer (.NET Standard)
- ExtendedXmlSerializer.dotNet.Core (.NET Core-specific code)
- ExtendedXmlSerializer.dotNet.Framework (.NET Framework-specific code)

But another thought we could do this:

- ExtendedXmlSerializer (.NET Standard)
- ExtendedXmlSerializer.Platforms (This would have a `<TargetFrameworks>net4x;netcoreapp1.x</TargetFrameworks>` and use #defines)

That way we retain the .NET Standard awesome while separating out the platform-specific implementations (the important part)

**Comment by wojtpl2** [comment]
I've checked that
'<TargetFrameworks>netstandard1.4;net45</TargetFrameworks>`
works well in VS2017.
Then you can use `#ifdef`. 

It is enough for us. 

I don't want many projects. It is not needed.

**Comment by Mike-EEE** [comment]
That does work, but it ends up creating two DLLs, correct?  One for .NETStandard 1.4 (supports both .NET Core 1.1 and .NET Framework 4.6.1) and then another for 4.5.

Supporting .NET Standard 1.3 (if we want to support 4.5 -- which I think we should) will also create two assemblies: one for .NET Standard 1.3 (supports .NET Core 1.1 and .NET Framework 4.5), and then another for 4.5 specifically.

I am trying to be mindful of the extra assemblies, but also want to provide good guidance and practice.  I would prefer to have 1 project/assembly per platform, but I can compromise here and do one 1 project for now:

- ExtendedXmlSerializer (.NET Standard)
- ExtendedXmlSerializer.Runtime (`<TargetFrameworks>net45;netcoreapp1.x</TargetFrameworks>` with #defines)

If it helps, we can merge `ExtendedXmlSerializer.Tests` and `ExtendedXmlSerializer.Tests.Performance` into one project now.  That would effectively swap one project out for another and keep the project count as-is. :)

**Comment by wojtpl2** [comment]
I've written 
```xml
<TargetFrameworks>netstandard1.4;net45</TargetFrameworks>
```
netstandard1.4 not netcoreapp1.x.
and we can have one project for .NET Standard and Net4.5.
We can have even .NET Standard 1.0 and .net 4.5 in one project, Way not?

**Comment by wojtpl2** [comment]
Don't merge ExtendedXmlSerializer.Tests and ExtendedXmlSerializer.Tests.Performance. Performance tests aren't unit test.

**Comment by Mike-EEE** [comment]
Ah!  OK... Try to reference `DependencyContext.Default` in a .NET Standard 1.4 (or 1.5) library, then you'll see the problem.  Or have a better solution than the one I am presenting. :)

And yes, agreed... performance tests are not unit tests.  Looking to see if we can keep the project count low (so we will _not_ merge).

**Comment by wojtpl2** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.DependencyModel

It is from .NET Standard 1.3

**Comment by wojtpl2** [comment]
I've used it in V1.0 https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/project.json#L40

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/Cache/TypeDefinitionCache.cs#L58

The second link I've sent to you before. But whole #ifdef.

**Comment by Mike-EEE** [comment]
Ahhh!  OK I overlooked that, then.  Let me see if I can make this work just using that. 👍

**Comment by Mike-EEE** [comment]
No I am indeed using it.  This is my (test) csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.5</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="1.1.0" />
  </ItemGroup>

</Project>
```

When I try to examine `DependencyContext`, this is what I see in 1.1:

```
// Decompiled with JetBrains decompiler
// Type: Microsoft.Extensions.DependencyModel.DependencyContext
// Assembly: Microsoft.Extensions.DependencyModel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// MVID: 127237B6-C94E-46BC-A508-906FDA3249CA
// Assembly location: C:\Users\Michael\.nuget\packages\microsoft.extensions.dependencymodel\1.1.0\lib\netstandard1.3\Microsoft.Extensions.DependencyModel.dll

using System;
using System.Collections.Generic;
using System.Linq;

namespace Microsoft.Extensions.DependencyModel
{
  public class DependencyContext
  {
    public TargetInfo Target { get; }

    public CompilationOptions CompilationOptions { get; }

    public IReadOnlyList<CompilationLibrary> CompileLibraries { get; }

    public IReadOnlyList<RuntimeLibrary> RuntimeLibraries { get; }

    public IReadOnlyList<RuntimeFallbacks> RuntimeGraph { get; }

    public DependencyContext(TargetInfo target, CompilationOptions compilationOptions, IEnumerable<CompilationLibrary> compileLibraries, IEnumerable<RuntimeLibrary> runtimeLibraries, IEnumerable<RuntimeFallbacks> runtimeGraph)
    {
      if (target == null)
        throw new ArgumentNullException("target");
      if (compilationOptions == null)
        throw new ArgumentNullException("compilationOptions");
      if (compileLibraries == null)
        throw new ArgumentNullException("compileLibraries");
      if (runtimeLibraries == null)
        throw new ArgumentNullException("runtimeLibraries");
      if (runtimeGraph == null)
        throw new ArgumentNullException("runtimeGraph");
      this.Target = target;
      this.CompilationOptions = compilationOptions;
      this.CompileLibraries = (IReadOnlyList<CompilationLibrary>) compileLibraries.ToArray<CompilationLibrary>();
      this.RuntimeLibraries = (IReadOnlyList<RuntimeLibrary>) runtimeLibraries.ToArray<RuntimeLibrary>();
      this.RuntimeGraph = (IReadOnlyList<RuntimeFallbacks>) runtimeGraph.ToArray<RuntimeFallbacks>();
    }

    public DependencyContext Merge(DependencyContext other)
    {
      if (other == null)
        throw new ArgumentNullException("other");
      return new DependencyContext(this.Target, this.CompilationOptions, this.CompileLibraries.Union<CompilationLibrary>((IEnumerable<CompilationLibrary>) other.CompileLibraries, (IEqualityComparer<CompilationLibrary>) new DependencyContext.LibraryMergeEqualityComparer<CompilationLibrary>()), this.RuntimeLibraries.Union<RuntimeLibrary>((IEnumerable<RuntimeLibrary>) other.RuntimeLibraries, (IEqualityComparer<RuntimeLibrary>) new DependencyContext.LibraryMergeEqualityComparer<RuntimeLibrary>()), this.RuntimeGraph.Union<RuntimeFallbacks>((IEnumerable<RuntimeFallbacks>) other.RuntimeGraph));
    }

    private class LibraryMergeEqualityComparer<T> : IEqualityComparer<T> where T : Library
    {
      public bool Equals(T x, T y)
      {
        return StringComparer.OrdinalIgnoreCase.Equals(x.Name, y.Name);
      }

      public int GetHashCode(T obj)
      {
        return StringComparer.OrdinalIgnoreCase.GetHashCode(obj.Name);
      }
    }
  }
}
```

So things changed in 1.1 from 1.0, I'm thinking?

**Comment by wojtpl2** [comment]
Ok no problem ;) 

_I hope that you remember that my English isn't the best and sometimes I write sentence as I can. I do not want to be rude. :)_

**Comment by Mike-EEE** [comment]
Haha, you're fine!  I'm the one brushing off the dust here.  My C#/.NET isn't too good right now after not speaking it for two months. ;)

I see how you did it now.  It works, but in 1.0 we were still creating two assemblies: 1 .NET Standard, and 1 .NET Framework.  There is overlap there as the .NET Standard library should account for all "shared" code.  That is what I trying to remove now that VS2017 is available: the overlap.

We should have 1 .NET Standard library, and then have 1 runtime library w/ platform-specific code (using #ifdefs), that way there is not _any_ overlap.

So in 1.0:
ExtendedXmlSerializer.csproj:
- netstandard1.6/ExtendedXmlSerializer.dll - 100KB (guessing)
- net45/ExtendedXmlSerializer.dll - 100KB (guessing -- overlaps)


In 2.0:
ExtendedXmlSerializer.csproj:
- netstandard1.5/ExtendedXmlSerializer.dll - 100KB (guessing)
ExtendedXmlSerializer.Runtime.csproj (with #ifdefs):
- net462/ExtendedXmlSerializer.Runtime.dll - 1KB (guessing - no overlap)
- netcoreapp1.1/ExtendedXmlSerializer.dll - 1KB (guessing - no overlap)

Hope this makes sense. :)

**Comment by wojtpl2** [comment]
We should have:
ExtendedXmlSerializer.csproj:
- netstandard1.5/ExtendedXmlSerializer.dll - 100KB
- **net45**/ExtendedXmlSerializer.Runtime.dll - 1KB 


Why you want to add this? In our case it is the same like netstandard1.5
- netcoreapp1.1/ExtendedXmlSerializer.Runtime.dll - 1KB (guessing - no overlap)

**Comment by Mike-EEE** [comment]
OK to start with, I had an error in my assembly list above.  I have fixed it.

> We should have:
> ExtendedXmlSerializer.csproj:
> ...
> - **net45**/ExtendedXmlSerializer.Runtime.dll - 1KB

I agree, but we cannot make the assembly (`ExtendedXmlSerializer.Runtime.dll`) from one project (`ExtendedXmlSerializer.csproj`). :)  Hence the reason we need another project (`ExtendedXmlSerializer.Runtime.csproj`)

To be sure, what I would ideally/really like to have is (to add to the confusion I've settled on yet another set of names 😆 👼):

- ExtendedXmlSerializer (`netstandard1.5`)
- ExtendedXmlSerializer.Runtime.Core (`netcoreapp1.1`)
- ExtendedXmlSerializer.Runtime.Windows (`net45`)

ISN'T CROSS-PLATFORMING FUN?!?!?!?! :)

This actually is not a lot of work.  I can make a checkin with a simple example (or maybe another temp branch altogether) and have you take a look at it so that you have a better understanding on what's at play here.

**Comment by Mike-EEE** [comment]
Alright, I've added some simple SLNs to help demonstrate the differences:

- [VS2017.NetStandard](https://github.com/Mike-EEE/Stash/tree/master/VS2017.NetStandard): What I am suggesting for v2.0
- [VS2017.NetStandard.MultiTarget](https://github.com/Mike-EEE/Stash/tree/master/VS2017.NetStandard.MultiTarget): What we are using for v1.0.

Please feel free to fork/copy and commit samples of what you are thinking, and if you can get them to work in `netstandard1.5`.

Btw, I tried to use `netstandard1.3` but it produced a bunch of errors.  So I am focusing on 1.5 for now (`netcoreapp1.1` and `net462`), with the intention of eventually moving to 1.1 (`netcoreapp1.1` and `net45`) or 1.2 (`netcoreapp1.1` and `net451`).

**Comment by wojtpl2** [comment]
I prefer VS2017.NetStandard.MultiTarget. In this case we have one nuget package. In first place we have to think about user, not about design.

**Comment by Mike-EEE** [comment]
100% agree.  If this is a hassle for our users, then that is a deal breaker for sure.  Good news though, as it does appear we can keep our users hassle-free while maintaining good design:

https://stackoverflow.com/questions/7486651/create-nuget-package-with-multiple-dlls

So, if I understand correctly, in the case of our NuGet package it would add both `ExtendedXmlSerializer.dll` and `ExtendedXmlSerializer.Platform.dll` when users add the `ExtendedXmlSerializer` NuGet package to either a .NET Framework application or a .NET Core application.

Make sense?  Is that OK? Please let me know if I have misunderstood something here, or if this is a problem.

BTW, xunit is doing the same thing with their DLLs.  In the case of xunit's `Debug\net462` folder, there's a `xunit.runner.reporters.net452.dll` and in our `Debug\netcoreapp1.1` there is a `xunit.runner.utility.netstandard15.dll`.  So, I am not _totally_ off my rocker.  Not yet, at least. :)

**Comment by Mike-EEE** [comment]
(Well I was off my rocker, after all.  The two correct assemblies are `xunit.runner.reporters.net452.dll` and **`xunit.runner.reporters.netstandard15.dll`**.  Edited to reflect this.)

**Comment by wojtpl2** [comment]
I still prefer VS2017.NetStandard.MultiTarget: What we are using for v1.0.

Some times #if is batter then you solution. Eg:

```
public class Example
{
  public int Id {get; set;}
 
#if NET4
  public string Point {get; set} //from win32
#end if
}
```
I prefer one project that will be compile to multiple framework.

**Comment by Mike-EEE** [comment]
OK. :)  I think the way to go for now is to do one project to multiple frameworks, like v1.0, and then for v3.0 we can revisit this, maybe for #107.  

Since there is only one `#if` this isn't a big deal for 2.0, but I think for .NET Standard 1.x it will require many more `#if`'s, and that will be ugly, so having separate projects will be better then.

Sound good?

**Comment by wojtpl2** [comment]
Ok it sounds good.
