### ISSUE TITLE
Help with custom serialization

### ISSUE THREAD

**Issue by danielmedina** [wojtpl2/ExtendedXmlSerializer#113]
Hi guys.

So, I'm trying to change just one element in my serialized xml and I thought that custom serialization could be a good choice.

Let me explain properly the problem with this hypothetical situation

I have these classes:

```
public class Department{
    public string Id { get; set; }
    public string Name { get; set; } 
    public List<Person> Employees { get; set; }
}

public class Person{
    public string Id {get; set; }
    public string Name {get; set;}
}
```

And, for a reason, I need to the department's name concatenated with the Id and the person's name concatenated with the id just in the serialization. I don't want to serialize again.  So, I started to write my custom serialization:

```
  public class DepartmentConfig : ExtendedXmlSerializerConfig<Department>
    {
        public DepartmentConfig()
        {
            CustomSerializer(Serializer, Deserialize);
            ObjectReference(p => p.Id);
        }

        public Department Deserialize(XElement element)
        {
            return new Department();
        }

        public void Serializer(XmlWriter writer, Department obj)
        {
            writer.WriteStartElement("Id");
            writer.WriteRaw(obj.Id);
            writer.WriteEndElement();
            writer.WriteStartElement("Name");
            writer.WriteRaw(obj.id + "- " + obj.Name);
            writer.WriteEndElement();
        }
    }

    public class PersonConfig : ExtendedXmlSerializerConfig<Person>
    {
        public PersonConfig ()
        {
            CustomSerializer(Serializer, Deserialize);
            ObjectReference(p => p.Id);
        }

        public Person Deserialize(XElement element)
        {
            return new Person();
        }

        public void Serializer(XmlWriter writer, Person obj)
        {
            writer.WriteStartElement("Id");
            writer.WriteRaw(obj.Id);
            writer.WriteEndElement();
            writer.WriteStartElement("Name");
            writer.WriteRaw(obj.id + "- " + obj.Nome);
            writer.WriteEndElement();
        }
    }
```

And then, I configured it in my WebApiConfig.Register()

```
            var simpleConfig = new SimpleSerializationToolsFactory();
            simpleConfig.Configurations.Add(new PersonConfig());
            simpleConfig.Configurations.Add(new DepartmentConfig());

            var serializer = new ExtendedXmlSerializer(simpleConfig);

            config.RegisterExtendedXmlSerializer(serializer);
```

But, when I serialize Departament, my employees list don't appear. I thought that it hapenned because I didn't  refer it in the Departament.Serialize(). But, how can I do it?

**Comment by Mike-EEE** [comment]
Hi @danielmedina thanks for checking in with this.  My experience and exposure w/ 1.0 is limited (working on v2.0 now :) ), but are you saying that when you serialize w/o using the custom configuration you do see your employees within the department?

**Comment by Mike-EEE** [comment]
Wanted to ping on this issue before closing it out.  Please let us know if you are still having problems here and we'll do our best to assist.

**Comment by Mike-EEE** [comment]
We're going to close out this issue for now.  Please let us know if you have any further questions/comments/issues with this item and we'll re-open it back up.  Please also feel free to open a new issue altogether if you find something new. :)
