### ISSUE TITLE
Error when using Custom Serializer and Circular reference together

### ISSUE THREAD

**Issue by ArnaudDebaene** [wojtpl2/ExtendedXmlSerializer#114]
Hello,

Say I have a class with a Custom Serializer / Deserializer:

`
public class MyStuffConfig : ExtendedXmlSerializerConfig<MyStuff>
    {
        public TestClassConfig()
        {
            CustomSerializer(Serialize, Deserialize);
        }
        public MyStuff Deserialize(XElement element)
        {
            //read the XML content and return an object
        }
        public void Serialize(XmlWriter writer, MyStuff obj)
        {
            //write the content of obj into the writer
        }
    }
`

Now, if the MyStuff objects are part of an object cycle, I may end with something like this in the serialized XML:
`
<MyStuff type="Sample.MyStuff" ref="12345" />
`

When I will deserialize this XML, my custom Deserialize method will be called on this node, but it will be unable to do anything with it:
- Most probably, the Deserialize method expect to have some attributes and/or elements in the XML element that won't be here.
- Even if I code Deserialize to handle the "ref" attribute, I have no way to check if this object already exist in the internal cache of the deserializer (the _referencesObjects dictionary), and/or to add it

Another problem with the current situation is also that, when I encounter a MyStuff element with an "Id" attribute in the XML, my custom Deserialize method will create it correctly, but the new object won't be inserted into the _referencesObjects dictionary, and therefore won't be available later to resolve references.

If you are interested, I have designed a workaround around this limitation, but it involves changing the interface for the custom Deserialize method (basically, this custom method needs to be splitted in 2 : One method that instanciate the new object, and another one, called later, that fill the newly created object with serialized stuff... Between the 2 calls, the new object can be inserted into the dictionary...)

**Comment by Mike-EEE** [comment]
Hi @ArnaudDebaene thanks for checking in and letting us know about this.  I am not too familiar with v1 extensions, but do not think this is a supported scenario.

Have you had a chance to try [v2 Alpha](https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha3) yet?  I would be interested in knowing how our new references functionality pairs with the custom serialization/deserialization.  Let me know if you have any questions around this and I will do my best to help you out.

**Comment by Mike-EEE** [comment]
This issue should be addressed with the latest alpha.  I am closing this issue for now.  If you do experience any further issues with the latest alpha, please feel free to open a new issue.
