### ISSUE TITLE
LightInject.Source is installed during installation of v2.0.0-alpha4 nuget

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#115]
LightInject.Source is installed during installation of v2.0.0-alpha4 nuget.

![image](https://user-images.githubusercontent.com/17333903/28910151-d260a4aa-782b-11e7-83ae-a104a95b6f0d.png)

Maybe it is some bug in nuget package or in new VS.

For comparison, there is list of dependencies of previous v2.0.0-alpha3:
![image](https://user-images.githubusercontent.com/17333903/28910252-4a5861e6-782c-11e7-8e85-f5c52d63af38.png)

In .net 4.5.1 was only two dependencies. Now we have 9 dependencies.

**Comment by Mike-EEE** [comment]
Good catch.  Fixed and committed.  Not sure if you want to make a `2.0.0-alpha4a` or something similar to push to nuget.  Guess it's not too big of a deal. :)

**Comment by Mike-EEE** [comment]
This should be addressed now.
