### ISSUE TITLE
Specifying the type of child class

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#118]
Hi,
So I'm sure its possible, I just can't find out how:
I have a component class, and multiple children of that class (e.g. MeshRenderer extends Component).
In my xml, I now want to specify which implementation to use. I thought it would be possible with the type argument, but this is not working:
```
      <Components>
        <Component type="BrokenEngine.Componenets.MeshRenderer">
          <Mesh>airboat.obj</Mesh>
          <Material>MyFirstMaterial</Material>
        </Component>
      </Components>
```
(Components is a List<Component> Components)

Thank you for your help!

**Comment by Mike-EEE** [comment]
OK cool.  My recommendation would be to create a very simple unit test (or console app) that takes a list of objects in memory, and then serialize that into the data form.  Then take the result of that and put that in the file to start with, and modify accordingly.  At least, that is how I make my files. :)

In v2 the attributes have changed so they require full namespaces now.  It should be something like the following:

```
<Components>
        <Component xml:exs="https://extendedxmlserializer.github.io/v2" exs:type="BrokenEngine.Componenets.MeshRenderer">
          <Mesh>airboat.obj</Mesh>
          <Material>MyFirstMaterial</Material>
        </Component>
      </Components>
```

Let me know how that works for you.

**Comment by michidk** [comment]
Okay, it didn't work at first, but then I serialized a hardcoded object.
I didn't know that the property name should be the type-name as well.

So this worked:
```     <Components>
        <MeshRenderer xmlns="clr-namespace:BrokenEngine.Components;assembly=BrokenEngine">
          <Mesh>airboat.obj</Mesh>
          <Material>MyFirstMaterial</Material>
        </MeshRenderer>
      </Components>
```
