### ISSUE TITLE
Suggestion: Introduce ExtendedXmlSerializer Namespace

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#12]
I hate to suggest this, but it's worth exploring.  The XML emitted by EXS is quite pretty.  Although, it does suffer from what I feel/believe is non-compliant XML, or rather XML that does not conform to a valid schema.

In particular, all of the properties that it emits are done in the default namespace, which does conflict with the content it is trying to serialize.  It works for EXS, but another serializer would break reading it (I think).

It would be nice/ideal to introduce an `exs` (or `xxs`? or `xs`?) namespace that these attributes use.

So for example this:

```
<TestClassWithReadOnlyCollectionProperty 
    type="ExtendedXmlSerialization.Test.TestObject.TestClassWithReadOnlyCollectionProperty" />
```

... would become this:

```
<TestClassWithReadOnlyCollectionProperty 
    xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer"
    exs:type="ExtendedXmlSerialization.Test.TestObject.TestClassWithReadOnlyCollectionProperty" />
```

**Comment by wojtpl2** [comment]
That sounds like great idea. I'll add this task to my todo list.

**Comment by Mike-EEE** [comment]
This is now complete and available in the v2 branch.
