### ISSUE TITLE
Custom Serializer

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#120]
Im currently trying to get a custom serializer to work (using alpha5). Because I encountered some issues (Deserializer method not called), I created a new xml test project and encountered a other issue.
When deserializing a serialized object, I get an InvalidOperationException:
```System.InvalidOperationException occurred
  HResult=0x80131509
  Message=The XmlReader state should be EndOfFile after this operation.
  Source=System.Xml.Linq
  StackTrace:
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at ExtendedXmlSerializer.ExtensionModel.Xml.CustomXmlExtension.Contents.Serializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionContentsHandler.Handle(IListInnerContent contents, IReader reader)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IListInnerContent contents, IReader reader)
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionInnerContentHandler.Execute(IInnerContent parameter)
   at ExtendedXmlSerializer.Core.SelectedCommand`1.Execute(T parameter)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member)
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Deserialize(XmlReader reader)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, IXmlReaderFactory factory, Stream stream)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, XmlReaderSettings settings, Stream stream)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, String data)
   at XMLTest.Program.Main(String[] args) in C:\Users\Michi\Programming\Visual Studio\XMLTest\XMLTest\Program.cs:line 23
```
The code can be found here: https://github.com/michidk/XMLTest/blob/master/XMLTest/Program.cs#L23

**Comment by michidk** [comment]
Now also getting the same error in my main project. Deserializtion with IExtendedXmlCustomSerializer in alpha 5 is not working.

**Comment by michidk** [comment]
Also I got a question: Is it possible to call the default serializer from the custom one? So that I can add additional logic?

**Comment by Mike-EEE** [comment]
Boo... not good.  I will look into this.  Thank you for reporting it and providing an easy test case. 👍 

As for custom logic, the `IExtendedXmlCustomSerializer` is more for legacy purposes to keep v1 code in the loop for v2.  The model is pretty flexible, however, for v2.0 we're keeping a lot of functionality private  and exposing most of the big features via extensions methods, just for stability and release reasons.  Going forward we envision opening this up to enable custom scenarios.  However, you should be able to do what you are looking to do... I will have to noodle on it to get you a (hopefully) viable solution, however.  I am a little caught up in Real Life for the next few days but should be able to get to this by Tuesday/Wednesday.

**Comment by michidk** [comment]
If IExtendedXmlCustomSerializer is legacy, then how to achieve the same functionality with Extensions?

**Comment by wojtpl2** [comment]
There is example of custom Serializer https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/samples/ExtendedXmlSerializer.Samples/CustomSerializator/CustomSerializatorSamples.cs#L31

**Comment by michidk** [comment]
But this sample uses IExtendedXmlCustomSerializer, in fact thats exactly the way I do it.

**Comment by Mike-EEE** [comment]
Man I've been a little too busy lately.  I was able to just now check this out.  Turns out that this is an issue with `XElement.Load`.  Instead of passing in the reader, you pass in the subtree.  [More can be found here](https://stackoverflow.com/questions/1133643/cant-load-xmlreader-into-xdocument).  Please get the latest when you get the chance and verify it has been fixed for you (you will still have to use csproj as we have not deployed a new version just yet).

**Comment by Mike-EEE** [comment]
OK, as for extensibility and overriding default functionality, this is a somewhat unsupported scenario for v2, but you should be able to do so.  I can point you in the direction, but it will probably involve some spelunking on your part to get it to work.  Part of the problem you will be facing is that a lot of the extensibility components (for v2) are internal so if you run into an interface that needs to be made public, please let me know (or better yet, submit a pull request) and we can take it from there.

That said, take a look at the [`MarkupExtension`](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtensionModel/Markup/MarkupExtension.cs#L37-L38).  I've highlighted the two lines that are most important.  Mostly you will need to decorate the [`IContents`](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtensionModel/Markup/Contents.cs) and [`ISerializers`](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer/ExtensionModel/Markup/Serializers.cs) interfaces to provide your own serializers when a type is requested.

The `ISerializerExtension` is also a place to do service registration in case you need dependencies delivered to you (again, the Contents/Serializers implementations above are good examples).

So, unsupported ATM but if you do run into problems, I will do my best to help.  Guess that means it's supported after all. 😛

**Comment by TLASZKIE** [comment]
Hi Mike,

First of all, thank you very much for your and Wojtek work. The library is amazing! :)

Do you know, when will the above fix be released? I have the same problem and I cannot use cproj as an alternative to nuget package (company policy...)

Cheers!

**Comment by wojtpl2** [comment]
@Mike-EEE Can I release alpha?

**Comment by Mike-EEE** [comment]
sure thing, @wojtpl2 ... I have checked in all my bug fixes.  I will update the milestone to reflect the new number as well. 👍   

And thanks for the encouragement @TLASZKIE.  FWIW, I am using this project on what I am working on now and it is working like a champ. :)  As an example, can you think of a single .NET serializer in existance that can serialize this class?

```
public sealed class Account : QueryBase
{
	public Account(Uri location, IList<Query> queries, QueryState state = QueryState.Active) : base(state)
	{
		Location = location;
		Key = key;
		Queries = queries;
	}

	public Uri Location { get; }

	public IList<Query> Queries { get; }
}
```
We have inheritance, list interface, and a parameterized constructor (with a default value no less!).  All of these, in my experience, have caused problems or out-right destruction to any serializer that ventures to tackle it.  EXSv2  was able to work with it easily.  Very happy with how this has turned out.

I hope to have some more free time next week so that I can finish out the FluentAPI rework, and then documentation to finally get this thing launched.

**Comment by wojtpl2** [comment]
I've just published 2.0.0-alpha6
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha6

**Comment by TLASZKIE** [comment]
Thank you very much! :)

**Comment by TLASZKIE** [comment]
Hi Guys, unfortunately I get the same error  duringcustom deserialization: 'The XmlReader state should be EndOfFile after this operation.'


```
[Test]
public void TestCustomSerialize()
{
	 var container = new ConfigurationContainer();
	 var typeConfiguration = container.Type<MyClass2>();
	 container.Type<CustomClass>().CustomSerializer(new CustomXmlConverter());
	 var extendedXmlSerializer = container.Create();
	 var toSerialize = new MyClass2() { Name = "TestClass", CustomClassValue = new CustomClass(){Value = "value"}};
	 var output = extendedXmlSerializer.Serialize(toSerialize);
	 var deserialized = extendedXmlSerializer.Deserialize < MyClass2>(output); //error InvalidOperationException 
}

class CustomXmlConverter : IExtendedXmlCustomSerializer<CustomClass>
{
	 public CustomClass Deserialize(XElement xElement)
	 {
		   return new CustomClass { Value = xElement.Value };
	 }

	 public void Serializer(XmlWriter xmlWriter, CustomClass obj)
	 {
		   xmlWriter.WriteValue(obj.Value.ToUpper());
	 }
}

public class MyClass2
{
	 public string Name { get; set; }
	 public CustomClass CustomClassValue { get; set; }

}

public class CustomClass
{
	 public string Value { get; set; }
}
```

Maybe I do something wrong?

**Comment by TLASZKIE** [comment]
Sorry, false alarm - I update nuget package, but not references... Stupid 8)

Everything works great - thank you!

**Comment by Mike-EEE** [comment]
Woohoo... those are the problems I like to see. 😄   Do let us know of any other issues you find for sure.

**Comment by Mike-EEE** [comment]
OK closing this issue.  Please feel free to open a new issue if you find problems, as always!
