### ISSUE TITLE
Serializing Array fails with null item

### ISSUE THREAD

**Issue by FathirMiah** [wojtpl2/ExtendedXmlSerializer#121]
If an array element value is null, it fails to serialize the object. for example: 
if you have a class as below:

    public class DataClass
    {
        public PlusMinus[] PlusMinus { get; set; }
    }

    public class PlusMinus
    {
        public string Name { get; set; }
    }

and if you have the data and instance as below:
             DataClass dataClass = new DataClass();

            dataClass.PlusMinus = new PlusMinus[2];
            dataClass.PlusMinus[0] = null;
            dataClass.PlusMinus[1] = new PlusMinus() { Name = "something" };

the object dataClass can not be serialized.

**Comment by Mike-EEE** [comment]
Thanks for reporting this @FathirMiah.  While it looks like it does not throw an exception in v2, it does emit a new non-null instance, which is not expected.  I will look into fixing this today.

**Comment by Mike-EEE** [comment]
OK I just committed a fix for this. @wojtpl2 did you release an Alpha 6 yet by chance?  I do not see one.  If you want you can release it and this fix will be in it.

**Comment by Mike-EEE** [comment]
OK this is addressed in the latest version.  Closing for now.
