### ISSUE TITLE
Encryption Forces Attributes

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#122]
I found an issue with the encryption extension and have fixed it on my side, but wanted to check in first here before pushing it, as it introduces a breaking change.

Basically, encryption was forcing encrypted content to be attributes whether or not the configuration was set to be attribute or not, so XML looked like this:

```
<?xml version="1.0" encoding="utf-8"?>
<TestClassWithEncryptedData Salary="Njc3Ng==" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests" />
```

Instead of like this:

```
<?xml version="1.0" encoding="utf-8"?>
<TestClassWithEncryptedData xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests">
	<Salary>Njc3Ng==</Salary>
</TestClassWithEncryptedData>
```

This has been fixed, but will introduce a breaking change for those who have used it.  I have been using this on the project I am working on now, that is how I found it. :) But wanted to make sure it's OK to commit before doing so.

**Comment by Mike-EEE** [comment]
I've created a PR for this issue here.  Please review and accept (or provide feedback), when you have the opportunity:
https://github.com/wojtpl2/ExtendedXmlSerializer/pull/123

**Comment by wojtpl2** [comment]
It is good fix! Thanks

**Comment by Mike-EEE** [comment]
Sure thing.  Today I will be getting back to finishing up the Fluent API hopefully by this weekend.  Here goes nothing. :)
