### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#124]
And now for the main event.  Saving the BEST for last, which is a joke because I hate doing it. :)  But this should be fun, actually.  Basically an overview of all the work from the past year-ish.  Should have a rough draft in a few days if not sooner.

**Comment by wojtpl2** [comment]
Look at `ExtendedXmlSerializer.DocGenerator` project. It generate documentation `docs\\get-started\\index.rst` and read me `readme.rst`. 

It use samples from code and results of `ExtendedXmlSerializer.Samples` project. Thanks to that after your big changes in API, we haven't had to update the documentation. I've just run to projects ExtendedXmlSerializer.Samples and ExtendedXmlSerializer.DocGenerator.

**Comment by wojtpl2** [comment]
docs\get-started\index.rst is used for generate documentation for our page http://extendedxmlserializer.readthedocs.io/en/v2.0.0/

**Comment by Mike-EEE** [comment]
OK cool.  Got a bit swamped with other items on my plate at the moment, but hope to have a look at this weekend and if not, definitely by Tuesday. 😸

**Comment by Mike-EEE** [comment]
OK... looking into this now.  Are we using `ExtendedXmlSerializer.Documentation` at all now anymore?  Can we remove this?

**Comment by wojtpl2** [comment]
`ExtendedXmlSerializer.Documentation` generate api documentation 
https://extendedxmlserializer.github.io/doc-v2.0.0/html/42fa4a74-3f63-fbac-9bcd-6f0f4552c82a.htm

`ExtendedXmlSerializer.DocGenerator` generate user documentation:
http://extendedxmlserializer.readthedocs.io/en/v2.0.0/

We should have `Quick Start` section with information how to migrate to `ExtendedXmlSerializer` from `XmlSerializer`
We can generate many documents in `ExtendedXmlSerializer.DocGenerator` but if you wish I can do it in next week.

**Comment by Mike-EEE** [comment]
OK cool.  I have it understood now. :)  And I am in agreement with the Quick Start.  I will try to get some work committed in over the weekend, and then we can see about generating the many documents/pages. 👍

**Comment by Mike-EEE** [comment]
This item has been completed with a first draft.  If there is anything outstanding regarding this issue, please feel free to open a new issue and we will take it from there.
