### ISSUE TITLE
Don't serialize empty collections and dummy objects

### ISSUE THREAD

**Issue by thomasjoscht** [wojtpl2/ExtendedXmlSerializer#128]
Hey, 

how could change serialization of empty lists? My classes often uses (Observable)Collections for storing objects in properties. For avoiding NullReferenceExceptions accessing the list it will be preinitialized in Constructor. Therefore the property have a value which will be serialized. But it contains no useful information. Therefore I would avoid property tag in XML.

How could I configure Serializer (v2) don't serializing properties which are only an empty list? 

Another use case is creation of dummy objects which have Id = 0. Could I conditionial check in serialization process for an property value (like an Id) and avoid serializing this object in case of specific value?

Thx Thomas

**Comment by Mike-EEE** [comment]
Hi @thomasjoscht thank you for your questions here.  

To start with the empty lists, if the property is writable, we need to signify in some way that an object is required (or expected) upon deserialization.  It would be possible to make it always force a create, even if there is none, but that might be a little more work.

We do support read-only collection properties.

So you could do something like this:

```
public class Subject
{
		public ObservableCollection<ObjectType> Counts { get; } = new ObservableCollection<ObjectType>();
}
```

And it will serialize for you as it does now with a writable-property.

Unfortunately, currently this is emitted even if there are not any items.  I agree with you and think that we should reduce the amount of emitted data where possible.  Currently we only emit values that are "assigned" (not-null or not default).  In the case of read-only lists we should do the equivalent and only emit when there are items.

Sound good to you?

As for the dummy serialization, this is also a good question. :)

We do have the ability to ignore and include members, and also to do so based on specification (conditions).  Unfortunately they were not wired up.  I took some time to do so, and you can now see how this is done here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/001b9f1d1b3cef726d01748406ef04d1c1e31f31/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue128Tests.cs

Unfortunately, we do not have a way of saying "when you see this type, emit it based on this specification".  It might not be so difficult to do, however.  So I will see what you think of the above changes before working on that.

**Comment by thomasjoscht** [comment]
Hi @Mike-EEE,

thanks a lot for your answers.  This is awesome!

Most part of my code could be changed to readonly collection properties. So your approach will work. Sometimes it could be that read-only is not possible in special circumstances, f.e. the collection property itself has some setter behaviour like NotifyPropertyChanged or the class is used by other libraries requiring setter like EF. But this is not really a problem in my case. Thx

Secondly for my dummy objects your approach also works fine. The solution to specify the condition for each member is passable in my app because dummy objects only necessary in special cases. A broader way specifing conditions for types instead of members could pe perfect, but I think the approach potentially willl not work in all ways (special exclusions). For me it is not necessary. Therefore Thx again!

A soon nuget publish will be nice ;-)

Regards, Thomas

**Comment by Mike-EEE** [comment]
Cool, @thomasjoscht!  Glad things will work for you as-is.  However, I do think having the ability to emit-per-type would be valuable.  It is actually something that was part of the original vision of this v2 work, so I should probably add it.  Shouldn't take more than today.  Then @wojtpl2 should be able to get a NuGet Alpha 7 push out for you. :)

In the meantime, you can always try cloning the project locally and reference it as a .csproj in your working SLN, if that makes sense.  I can provide further instruction if necessary.

**Comment by Mike-EEE** [comment]
This issue should be resolved now.  Please feel free to add a comment if not and we will take it from there.

**Comment by frjonsen** [comment]
> Unfortunately, we do not have a way of saying "when you see this type, emit it based on this specification". It might not be so difficult to do, however. So I will see what you think of the above changes before working on that.

I would like to ask to revisit this issue. I have a project with a large amount of objects containing ICollections. These are defaulted, when the objects are constructed, to new List<T>(), which makes me unable to use the EmitBehaviors that are included. Potentially I could setup configuration for each and every member, using .EmitWhen, but that would make for a large amount of configuration. Fortunately, all of these objects inherit from a common abstract class Entity. What I would be hoping to do would be something like:

`new ConfigurationContainer().ConfigureType<ICollection<Entity>>().EmitWhen(e => e.Count != 0)` or possibly
`new ConfigurationContainer().ConfigureType<ICollection<Entity>>().Emit(EmitBehaviors.NotEmpty)`

Is this already possible in some way that I have missed, or would this have to be added?

**Comment by Mike-EEE** [comment]
Cool @frjonsen thanks for  pinging back regarding this.  We're ramping up for 2.1 in the near future.  I think this is possible to do for this release.  I've added it to our list as a new issue:

https://github.com/wojtpl2/ExtendedXmlSerializer/issues/145

Please feel free to add additional feedback there. :)
