### ISSUE TITLE
Design Consideration: Read-only Properties

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#13]
Another consideration is perhaps move to read-only properties for properties, and move initialization to constructors.  For instance with `SimpleSerializationToolsFactory` making it look like this:

```
public class SimpleSerializationToolsFactory : ISerializationToolsFactory
{
    public SimpleSerializationToolsFactory(IEnumerable<IExtendedXmlSerializerConfig> configurations, IPropertyEncryption encryption)
    {
        Configurations = new List<IExtendedXmlSerializerConfig>(configurations);
        EncryptionAlgorithm = encryption;
    }

    public IList<IExtendedXmlSerializerConfig> Configurations { get; }
    public IPropertyEncryption EncryptionAlgorithm { get; }

    public IExtendedXmlSerializerConfig GetConfiguration(Type type)
    {
        foreach (var migrationMap in Configurations)
        {
            if (migrationMap.IsSatisfiedBy(type))
            {
                return migrationMap;
            }
        }
        return null;
    }
}
```

What this moves towards is _immutability_, which is automatically a thread-safe(r) design.  Also note the use of `IList` rather than `List`, which will allow consumers to use any object that implements `IList` rather than being forced to use a specific implementation.

These of course would be breaking changes to the current code.  You would have to `Obsolete` them and move users to the new classes.

**Comment by wojtpl2** [comment]
In v2 we don't have ISerializationToolsFactory any more.
