### ISSUE TITLE
LAUNCH V2!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#130]
OK Mr. @wojtpl2!  The day that we have been awaiting is FINALLY here!  All items have been accounted for with v2.  Please give the documentation a review, and if everything looks OK to you, feel free to merge `master` with `v2.0.0` and get this sucker launched. 😄 😄 😄

**Comment by Mike-EEE** [comment]
Ahhh... I just realized that the documentation is already posted:
http://extendedxmlserializer.readthedocs.io/en/v2.0.0/

Durp!  And the formatting is off for a lot of the new examples.  Let me try fixing that first.  I will post here once done.

**Comment by wojtpl2** [comment]
Documentation looks great! Really great job. Today I would like to try again v2 in my project and if every things be ok, I'll publish v2. I'll let you know.

**Comment by Mike-EEE** [comment]
Cool.  I got the formatting fixed (I hope 👼), and added a section for implicit typing.  We are good from my side. 👍 

Also... I've been using v2 in my side project and it has been wonderful, if I do say so myself. 😄

**Comment by wojtpl2** [comment]
Serializer and deserializer works but I have small issues. I'll create two new issues .

**Comment by Mike-EEE** [comment]
v2 is launched.  Congratulations @wojtpl2 ! ! ! 🎉

**Comment by wojtpl2** [comment]
Congratulation for you @Mike-EEE. You have 96% of autorship of version 2. 
![image](https://user-images.githubusercontent.com/17333903/32828626-f1b7bcba-c9ef-11e7-82da-043a4be4f4ea.png)

**Comment by Mike-EEE** [comment]
Oh man. 👼 I didn't mean to, it just happened! 😆

**Comment by wojtpl2** [comment]
I don't care about it. You did great job!

I've added you to authors section on Nuget. 
![image](https://user-images.githubusercontent.com/17333903/32829064-39886142-c9f1-11e7-9818-d4fc1bbacf55.png)

**Comment by Mike-EEE** [comment]
Cool!  Happy to see this is finally released.  I can start telling my friends about it! 😄

**Comment by wojtpl2** [comment]
Yes of course. Please give me feedback.
