### ISSUE TITLE
Parameterized Content Does Not Work with Dictionary<>

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#134]
Tracking down an ugly bug I found this morning.  Will update this issue once fixed (hopefully).  Please don't launch v2 until I get it fixed.

**Comment by Mike-EEE** [comment]
OK this has been addressed.  The problem is with native dictionary objects.  There is a hard check right now specifically for this type and to bypass it if so.  If someone wants to use [one of the parameterized constructors](https://msdn.microsoft.com/en-us/library/6918612z%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) at some later date, then we will have to revisit this issue.  Worth noting that if you inherit from `Dictionary<,>` and use your own parameterized constructors there, that this will (or should 👼) work as expected.

**Comment by wojtpl2** [comment]
Thanks!
