### ISSUE TITLE
Compatibility with the standard XML Serializer attributes

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#135]
I'm using the pre-release version of v2. I noticed that the standard serializer works for me, but your Extended one does not. I think it's because I'm adorning classes and properties with attributes like this:

```
    [XmlRoot(ElementName = "QDFFile")]
    public class QdfFile
    {
    }
```

**Comment by Mike-EEE** [comment]
Boh, thanks for reporting this @SuperJMN.  We do have [a test that verifies](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ContentModel/Members/MemberSerializationsTests.cs#L104) that `XmlRootElementAttribute` does work as far as translating the element name to the emitted document (and read back in).  When you say that it doesn't work, is it this aspect in particular?  Or maybe something else?

**Comment by SuperJMN** [comment]
Sorry, but I'm not able to use the serializer right now, so I cannot explain what's the problem until https://github.com/wojtpl2/ExtendedXmlSerializer/issues/147 is fixed :( 

I will close it for now.
