### ISSUE TITLE
Connect web page in all places 

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#137]
Connect web page
https://extendedxmlserializer.github.io/
to:
* all builds: https://www.nuget.org/packages/ExtendedXmlSerializer/
* github
* stackoverflow

**Comment by Mike-EEE** [comment]
I am pretty sure this is done, but just to be sure. :)

**Comment by Mike-EEE** [comment]
I believe this has been completed and will be closing this for now.  Please let me know if I have misunderstood!
