### ISSUE TITLE
Update documentation on Stackoverflow

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#138]
https://stackoverflow.com/users/4809321/wojtpl2?tab=answers

**Comment by wojtpl2** [comment]
I've updated 2 articles
https://stackoverflow.com/a/39633002/4809321
https://stackoverflow.com/a/39633618/4809321

**Comment by Mike-EEE** [comment]
Ping.  Please feel free to close this if it is completed. 😄

**Comment by Mike-EEE** [comment]
This is complete as far as I understand... please feel free to re-open if this is not the case.
