### ISSUE TITLE
Update Api Doc

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#139]
Update https://extendedxmlserializer.github.io/doc-v2.0.0/html/42fa4a74-3f63-fbac-9bcd-6f0f4552c82a.htm

**Comment by Mike-EEE** [comment]
Ping.  Please feel free to close this if it is completed. 😄

**Comment by Mike-EEE** [comment]
I believe everything is updated in regards to this issue.  Please let me know if that is not the case and we will reopen. 👍
