### ISSUE TITLE
Support for byte[] property

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#14]

**Comment by Mike-EEE** [comment]
This is now supported in v2.  A pre-release should be available by end of week at the latest and I will update this thread when available.  If you encounter any problems or unexpected behavior please feel to reopen this issue.

**Comment by Mike-EEE** [comment]
Pre-release deployment for this feature can be found at these feeds:
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha
