### ISSUE TITLE
Readonly Fields

### ISSUE THREAD

**Issue by AQuentin2033** [wojtpl2/ExtendedXmlSerializer#146]
I have been through the documentation but cannot find an example of how to do the following:

Given the class:
```
public class Plane
{
     private readonly double length;
     public double Length { get => length; }
     public int Rows { get; set; }

     public Plane(int rows, double Length)
     {
          Rows = rows;
          length = Length;
     }

     public Plane(double Length)
     {
          length = Length;
     }
}
```

`var p = new Plane(4.33);`

How do I serialize this as <Plane Length="4.33" /> ?  I explicitly do not want the Rows to get serialized and the Length must be as an attribute.

Thanks

**Comment by Mike-EEE** [comment]
Hi @AQuentin2033 thanks for writing in.  Looks like you have two concerns here.  One is that you are using parameterized constructors, which are indeed supported but require you to enable them in the container.  The 2nd concern is member configuration, which is also supported.  Here is the code to get you started:

```
var serializer = new ConfigurationContainer().EnableParameterizedContent()
                                             .ConfigureType<Plane>()
                                             .Member(x => x.Rows).Ignore()
                                             .Member(x => x.Length).Attribute()
                                             .Create()
```

I've also added this as a passing test to our suite [here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/50c0e9bbf2e111896813009548692df90770a43b/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue146Tests.cs) if interested.  Please let me know if you have any further questions in regards to this.

**Comment by AQuentin2033** [comment]
Thanks Mike, I am however getting something odd happen when I try the following:

```
    public struct SubItem
    {
        public readonly double X;
        public SubItem(double x)
        {
            this.X = x;
        }
    }

    public struct Master
    {
        public readonly SubItem sub;
        public double A => this.sub.X;
     
        public Master(double a)
            : this(new SubItem(a))
        {
        }

        public Master(SubItem item)
        {
            this.sub = item;
        }
    }
```
using the configuration

```
     var p = new Master(new SubItem(1));
     var serializer = new ConfigurationContainer().EnableParameterizedContent()
                                             .ConfigureType<Master>()
                                             .Member(x => x.sub).Include()
                                             .Member(x => x.A).Ignore()
                                             .ConfigureType<SubItem>()
                                             .Member(x => x.X).Attribute();
    var contents = serializer.Serialize(p);
```

This results in `<Master><A>1</A></Master>` instead of what I am trying to achieve which is  `<Master><SubItem X="1" /></Master>`

Do I need to add something special to the configuration because the member is a struct/class?

**Comment by Mike-EEE** [comment]
Structs are treated like classes and are supported.  That A shouldn't be emitted at all, as it is a readonly property and we ignore those by default.  Maybe there's something funny on with the `Ignore` on a readonly property in this case.  I'll check it out and let you know. 👍

**Comment by Mike-EEE** [comment]
As an update, I tracked this down to the `EnableParameterizedContent` call.  Hope to have a fix here in the next day or so when I can find the time.

**Comment by Mike-EEE** [comment]
OK @AQuentin2033 I got this addressed.  Please note that we follow the rules as [outlined here](http://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html), so that was causing some additional issues.  I did manage to get a test that [demonstrates expected output](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/b6bcf76f2d959799b7a1fb8e35b23d8a33b8a679/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue146Tests.cs#L42-L43), so this will be ready for v2.1.  In the meantime you can get the latest here from our preview nuget feed: https://www.myget.org/F/wojtpl2/api/v2/

**Comment by AQuentin2033** [comment]
Thanks Mike!

**Comment by Mike-EEE** [comment]
Happy New Year. :) Closing this issue as the latest code addresses it to the best of our understanding.  Please feel free to comment here and/or re-open a new issue if there is something not captured and needs to be addressed. Thank you!
