### ISSUE TITLE
'The type initializer for 'ExtendedXmlSerializer.ContentModel.Reflection.PartitionedTypeCandidates' threw an exception.'

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#147]
Hi guys!

I'm getting this exception when executing from a Windows 10 Universal Application (UWA).

The steps to reproduce are: 

1. Create a Windows Universal project targeting **Windows Fall Creators Update (16299)**. Set the minimum version to the same.
2. Open the automatically generated MainWindow.xaml.cs
3. Put this code

```
using Windows.UI.Xaml.Controls;
using ExtendedXmlSerializer.Configuration;

namespace App1
{
    /// <summary>
    /// Página vacía que se puede usar de forma independiente o a la que se puede navegar dentro de un objeto Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            new ConfigurationContainer().Create();

            this.InitializeComponent();
        }
    }
}
```
4. Run it. The exception will be thrown.

I hope this helps!

**Comment by Mike-EEE** [comment]
OK cool... thanks for submitting this, @SuperJMN.  Taking a look into this now.

**Comment by Mike-EEE** [comment]
Ah you know what... I just figured this out.  This project is currently set to .NET Standard 1.6, and I do not believe UWP supports that.  It only supports .NET Standard 2.0.  I will have to get with @wojtpl2 on this to figure out the best solution to fix this, and if we can support .NET Standard 2.0.

**Comment by SuperJMN** [comment]
That is really strange! The rule of thumb is that if something supports a .NET Standard of version x, then it should support any version lower than x. I mean, UWP supports 2.0, so it should support any version under 2.0, since they are subsets of the standard 😊

Please, check it with @wojtpl2<https://github.com/wojtpl2>. Maybe I’m wrong! It’s my default state 😝

________________________________
De: Mike-EEE <notifications@github.com>
Enviado: Thursday, November 30, 2017 1:41:38 PM
Para: wojtpl2/ExtendedXmlSerializer
Cc: José Manuel Nieto; Mention
Asunto: Re: [wojtpl2/ExtendedXmlSerializer] 'The type initializer for 'ExtendedXmlSerializer.ContentModel.Reflection.PartitionedTypeCandidates' threw an exception.' (#147)


Ah you know what... I just figured this out. This project is currently set to .NET Standard 1.6, and I do not believe UWP supports that. It only supports .NET Standard 2.0. I will have to get with @wojtpl2<https://github.com/wojtpl2> on this to figure out the best solution to fix this, and if we can support .NET Standard 2.0.

**Comment by Mike-EEE** [comment]
Ah well for starters I tried creating a new UWP project and then added my local ExtendedXmlSerializer project and got the following: 

![2017-11-30_0817](https://user-images.githubusercontent.com/2931376/33432697-ff7bee30-d5a6-11e7-83b1-9db399517808.png)

But now thinking about it... you are correct.  What you describe is the case for .NET Standard 1.x ... is the same for 2.0?  It was such a significant jump that I was thinking that 2.0 was not compatible w/ 1.x... This requires more investigation. 😄

**Comment by SuperJMN** [comment]
Aha! Presumably, you cannot add the reference because you aren’t targeting to the required build. Check that you are targeting Fall Creators Update (and the minimum version, as well). Otherwise, it won’t be able use .NET Standard libraries over 1.3 (if I remember well).

________________________________
De: Mike-EEE <notifications@github.com>
Enviado: Thursday, November 30, 2017 2:19:20 PM
Para: wojtpl2/ExtendedXmlSerializer
Cc: José Manuel Nieto; Mention
Asunto: Re: [wojtpl2/ExtendedXmlSerializer] 'The type initializer for 'ExtendedXmlSerializer.ContentModel.Reflection.PartitionedTypeCandidates' threw an exception.' (#147)


Ah well for starters I tried creating a new UWP project and then added my local ExtendedXmlSerializer project and got the following:

[2017-11-30_0817]<https://user-images.githubusercontent.com/2931376/33432697-ff7bee30-d5a6-11e7-83b1-9db399517808.png>

But now thinking about it... you are correct. What you describe is the case for .NET Standard 1.x ... is the same for 2.0? It was such a significant jump that I was thinking that 2.0 was not compatible w/ 1.x... This requires more investigation. 😄

**Comment by Mike-EEE** [comment]
Indeed... I have set both version above as you suggest.  But now thinking about this... EXS is not a strictly 1.x project.  We actually support both `net45;netstandard1.6`, which might be leading to this issue?  If I change this to `netstandard2.0` I am able to add the project.  Unfortunately I now get compile errors that return no results:
```
error CS0433: The type 'FormatterAssemblyStyle' exists in both 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

I will look further into this.

**Comment by Mike-EEE** [comment]
Well found the culprit for the above: https://github.com/JamesNK/Newtonsoft.Json/issues/1423

I was able to get the project to compile as .NET Standard 2.0, but when I run it, I get the following in Visual Studio:

![2017-11-30_0918 1](https://user-images.githubusercontent.com/2931376/33435203-916d7ad6-d5af-11e7-9785-48efe9efd9b0.png)

So it looks like it's a win32 exception we are causing?  UWP isn't so good at errors. ;)

**Comment by SuperJMN** [comment]
Can you publish the branch that you're using so I can try to see if it Works On My Machine®? :)

**Comment by Mike-EEE** [comment]
YOUR WISH IS MY COMMAND:
https://github.com/Mike-EEE/ExtendedXmlSerializer/tree/netstandard20

:)

**Comment by SuperJMN** [comment]
![image](https://user-images.githubusercontent.com/3109851/33456454-c95776fc-d61f-11e7-8fe7-79e9fbbbd853.png)

This is what I'm getting :( I don't have a clue of what's going on there!

**Comment by Mike-EEE** [comment]
Whoohoo!  Easy fix.  And we can get rid of compiler directives, to boot!  I just committed the fix to the branch.  Get latest now and see how it treats you.  FWIW, `AppDomain` works everywhere now, not just in Windows.

**Comment by Mike-EEE** [comment]
Alright, I've updated the remaining projects and they are in master now.  I do not think upgrading to .NET Standard 2.0 introduces any significant problems and in fact reduces complexity and dependencies in our code.  @wojtpl2 will have to make the final decision on this of course and we can open another dedicated issue if there is a problem.  In the meantime you can find the .NET Standard 2.0 version of EXS from the preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

As always please let me know if you find any additional issues.
