### ISSUE TITLE
Complex scenario: How do I configure constructor injection?

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#149]
Given this simple classes:

```
public class Rectangle 
{
    public Color Background {get; set; }
}

public struct Color 
{ 
    public Color(byte a, byte r, byte g, byte b) 
    {
       this.a = a;
       this.r = r;
       this.g = g;
       this.b = b;
    }
    public byte A { get; }
    public byte R { get; }
    public byte G { get; }
    public byte B { get; }
}
```

If a try to serialize an instance of Rectangle, then the Background property will serialized as:

```
<ns1:Rectangle>
    <Background />
</ns1:Rectangle>
```

So it seems that EXS doesn't work well with custom structs.

**Comment by Mike-EEE** [comment]
Is that the *exact* definition of your struct?   In order for the serializer to write the values (assuming default behavior), the properties must have setters. :)

**Comment by Mike-EEE** [comment]
Oh I see (I think)... are you saying that you expect the background to be empty and not emitted at all?

**Comment by Mike-EEE** [comment]
Ah OK so to enable parameterized content, you can enable this by following the example here:
https://github.com/wojtpl2/ExtendedXmlSerializer#parameterized-members-and-content

Please note that I used this article to base it from:
http://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html

This just so happens to be my favorite part about this serializer. :)

**Comment by Mike-EEE** [comment]
I spoke with @SuperJMN on Skype and this solved his woes.  Happy to see this work for you, my man!  Please feel free to create another issue if you run into any additional troubles.
