### ISSUE TITLE
Bad serialization of string in RTF format

### ISSUE THREAD

**Issue by SuperJMN** [wojtpl2/ExtendedXmlSerializer#150]
Hi fellows!

I've tried to serialize a text in RTF format and the resulting serialization was a bad-formed XML.

The string I've tried to serialize is this:

**{\rtf1\fbidis\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil Segoe UI;}}
{\colortbl ;\red0\green0\blue0;}
{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
\pard\tx720\cf1\f0\fs23 Sample Text\par
}**

I contains lot of braces and slashes that for sure are conflicting with the XML format.

Maybe there is an options to serialize a string as CDATA or something. Is there a workaround? Thank you!

**Comment by Mike-EEE** [comment]
Oh man... yeah we haven't done any of this sort of stuff yet. :)  I will look into this for you, @SuperJMN !

**Comment by SuperJMN** [comment]
Hey Mike! it may be possible to configure serialization/deserialization on a per-member basis, like converters. It would be useful as a workaround. For instance, I would write a Text property that is a RTF-formatted string to Base64, and convert back on deserialization. 

The other option I see is to have some configuration options also for members inside a Type, that allows it to be serialized as CDATA. 

What do you think?

**Comment by wojtpl2** [comment]
@SuperJMN Could you provide code example how you serialize RTF text?
You mean:
```c#
string rtfText = @"{\rtf1\fbidis\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil Segoe UI;}}
{\colortbl ;\red0\green0\blue0;}
{*\generator Riched20 10.0.16299}\viewkind4\uc1
\pard\tx720\cf1\f0\fs23 Sample Text\par
}";
```

Do you know if it is supported by standard XmlSerializer?

**Comment by wojtpl2** [comment]
CDATA should also be supported. 
Standard XmlSerializer support `XmlCDataSection`. There is example:
https://social.msdn.microsoft.com/Forums/en-US/6f59a2c0-2f70-4f19-9210-c675bbdce48d/cdata-serialization-with-xmlserializer?forum=asmxandxml

We can create also configuration for it. Example:
```c#
 var serializer = new ConfigurationContainer()
			    .Type<Class>() // Configuration of Person class
					.Member(p => p.File).CData()
			    .Create();
```
Or something like that. @Mike-EEE What do you think?

**Comment by Mike-EEE** [comment]
Yeahar... I like where this is going.  Essentially create an `RtfConverter` which is then applied to members via a `Cdata` extension method.  I got some client work that has popped up for me this week, but I should be able to take a look at this starting tomorrow. 👍   FWIW, I am keeping this categorized as a bug as the `XmlWriter` should be emitting data as CDATA automatically.  So we aren't wired up correctly somewhere.  The rest is considered an enhancement for v2.1 (which, incidentally, I will move to next week as I have not been able to put as much time into EXS as I had hoped this week).

**Comment by SuperJMN** [comment]
Halt the machines! It seems that there is a bug in the component that generated the RTF! I'm working to see what's going on. It seems that it's nothing to do with EXS.

**Comment by Mike-EEE** [comment]
Woohoo... those are the kind of problems I like. ;)  Please feel free to re-open if it is indeed connected here to EXS.

**Comment by SuperJMN** [comment]
OK, guys, this is REALLY strange. It keeps happening!

I have prepared a minimum scenario that reproduces the issue. Please, take a look. Clone the repo: https://github.com/SuperJMN/RtfIssue. It's UWP ready to run. 

Write some text, click on Save. It can happen 2 things: 

1. An exception is thrown
2. The file is written, but in a corrupted state

I'm now sure that it's a problem with EXS because if you use the official `XmlSerializer`, it writes the XML file just right.

If you need any further information, please tell me!

**Comment by Mike-EEE** [comment]
Ahhh ok cool!  Thanks for the repro... and repo. 😆   I will aim to take a look at this today or by tomorrow for sure.

**Comment by SuperJMN** [comment]
OK! Don't forget to check me at Skype if you need anything! Best regards :)

**Comment by Mike-EEE** [comment]
Alright, there's a "workaround" here:
https://stackoverflow.com/a/32888973/3602057

But I don't like that.  I think the `CData` method described above is much better.  We'll pipe it through this bad boy here:
https://msdn.microsoft.com/en-us/library/system.xml.xmlwriter.writecdata(v=vs.110).aspx

**Comment by Mike-EEE** [comment]
Hey @SuperJMN sorry for the delay here but I have FINALLY got a solution for you here.  You can now configure string-based members with the `Verbatim` method and it will configure that member for CData-based writing.  You can see some examples of this here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue150Tests.cs

You can get the latest version from our preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Please let me know if you run into any additional problems and I will look into them for you.  I am finally free to work on this repo once again so it should be faster this time, I promise. 👼

**Comment by Mike-EEE** [comment]
FWIW I just verified that this works as expected for the UWP sample.  Well, as much that UWP can "work" as expected. ;)

Here is the emitted XML now:

```
<?xml version="1.0" encoding="utf-8"?><TextModel xmlns="clr-namespace:App6;assembly=App6"><Text><![CDATA[{\rtf1\fbidis\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil Segoe UI;}}
{\colortbl ;\red0\green0\blue0;}
{\*\generator Riched20 10.0.16299}\viewkind4\uc1 
\pard\tx720\cf1\f0\fs23 asdfasdf\f1\par
}
 ]]></Text></TextModel>
```

**Comment by Mike-EEE** [comment]
This made me realize that we should have a `VerbatimAttribute` so that you can apply it to properties and it will automatically register it as a verbatim property.  I will work on that now.

**Comment by Mike-EEE** [comment]
Alright.  I've implemented `VerbatimAttribute`.  Please let me know if you run into any additional issues here and we will re-open this item.

**Comment by wojtpl2** [comment]
We should also support Verbatim in POCO class (without attribute). What do you think about it:
```c#
 var serializer = new ConfigurationContainer()
			    .Type<SubjectWithAttribute>() 
					.Member(p => p.Message).Verbatim()
			    .Create();
```

In documentation should be description about it.

**Comment by Mike-EEE** [comment]
Oops!  Sorry that wasn't clear, we do have that here, in the tests from above: 😄 
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue150Tests.cs#L56

**Comment by Mike-EEE** [comment]
Alright I have added documentation for this feature and have pushed the tags.  Hopefully a new version of Nuget will appear shortly. :)  Please feel free to reopen if there are any additional issues!

**Comment by Mike-EEE** [comment]
Holy moly!  Have I been in a rabbit hole.  I am just now getting my environment back online and being able to attend to this.  I hope to have this resolved today or tomorrow.  We'll see how I do. 😛
