### ISSUE TITLE
Implicit typing for whole namespace

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#153]
Hey, 
I am currently using this: `container.EnableImplicitTyping(typeof(Scene), typeof(Model), typeof(Mesh), typeof(Material), typeof(GameObject));` to keep my xml file clean. Is there a way to do this for a whole namespace/project instead of for every single type?

**Comment by Mike-EEE** [comment]
This is certainly possible.  Right now we allow a `params Type[] parameter` for that call.  We could allow a type of `IEnumerable<Type>` that allows you to pass in a class that inherits from this interface and then use the results of this for the types used.  We would then provide an `AssemblyTypes` or `NamespaceTypes` class that could help facilitate this.

**Comment by Mike-EEE** [comment]
Alright @michidk I have a first draft of this for you to check out.  You can see an example here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue153Tests.cs#L13-L21

There are several methods now, but in your case, it should be something like:

```
// ...
new ConfigurationContainer().EnableImplicitTypingFromNamespace<Scene>()
// ...
```

Assuming all the types you mention above are in the same namespace as `Scene`.  Please also keep in mind that if any of your classes share the same name it will result in an error being thrown, as we will not know which one to select to emit.

Please feel free to check it out and/or to provide any additional feedback around this issue.  You can find this on our preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by Mike-EEE** [comment]
Closing this issue as it has been deployed in 2.1.0: #162

Please feel free to open an issue if you encounter any further problems
