### ISSUE TITLE
Emitted Types for Read-only Properties

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#16]
FWIW/FYI here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializerTest/Resources/ClassWithReadOnlyCollectionProperty.xml#L3

Looks like types are being emitted for read-only properties.  This is not needed since the property is assigned internally to the object (in theory).

**Comment by wojtpl2** [comment]
You right. In this case we don't need this information. 
Would you like to create pull request for this issue?

**Comment by Mike-EEE** [comment]
Guess I should pull first and ask questions later. 😛

**Comment by wojtpl2** [comment]
I approve this commit. Thanks!
