### ISSUE TITLE
Release 2.1.13

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#162]
This issue serves as the destination for the version `2.1.x` launch, serving as a list of fixes and feature additions/adjustments.  Please feel free to add a comment for any discussion or to open a new issue in this repo if you have found an issue you would like for us to investigate.

New Features:
- Enable exception reporting for members #214
- Upgraded to .NET Core 2.1 #210 
- Classic list support for classic XmlSerializer documents (`ArrayOfObject`, etc) #206 
- Better version support - #198 
- Better property handling for tricky scenarios - #197 
- Improve parameterized content to allow additional scenarios #196 
- Add basic support for XmlTextAttribute (be gentle lol) #192
- Add Support for Multidimensional Arrays #173
- Add XmlEnumAttribute Support #174
- Add Support for Jagged Arrays #170
- Support for ISerializationSurrogate #161
- Implicit typing for whole namespace #153
- Add Type-Level Emit Specifications #145
- Add Support for Configuration Profiles #148
- Using multiple custom serializers for complex type #154

Issues addressed:
- Exception when Deserializing Empty List When Emit(Behavior) is Set #216
- Ignore Default Value #211
- Exception while Deserializing Abstract Member #213 #214
- Performance issue with `UseOptimizedNamespaces` #209 
- Better support for `Version` #198 
- Improved parameterized content #196
- Problem with installing nuget package #160
- Xml Deserialization Error #175
- Serialization Exception in UWP #167

**Comment by wojtpl2** [comment]
Great idea with this: https://github.com/wojtpl2/ExtendedXmlSerializer/commit/8eb6020f111847941ff1874986e9c24dc09ab5aa#diff-802233c775e8a749803978227a02cdb6R26

**Comment by Mike-EEE** [comment]
Hehe cool yeah?  Simplifies it and also makes it easier to contain any mistakes. :)

**Comment by wojtpl2** [comment]
I have a problem during installation of version 2.1.0:
```
Unable to find a version of 'Newtonsoft.Json' that is compatible with 'ExtendedXmlSerializer 2.1.0 constraint: Newtonsoft.Json (>= 11.0.1-beta1)'.			0	

```

Can you check it?

**Comment by wojtpl2** [comment]
We shouldn't use 
`<PackageReference Include="Newtonsoft.Json" Version="11.0.1-beta1" />`
We should use the lowest possible version.. Currently users have to update theirs Newtonsoft.Json to newer version. 

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj#L52

**Comment by Mike-EEE** [comment]
Boh!  I'll look into this right now.

**Comment by Mike-EEE** [comment]
Alright I just pushed `2.1.1`.  Should be deployed to nuget soon.  Turns out we didn't even need that dependency after the move to .NET Standard 2.0.

**Comment by wojtpl2** [comment]
It works now. Thanks!
