### ISSUE TITLE
Build improvements

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#165]
1. Add props files to keep version in one place.
2. Make JetBrains.Annotations reference as private assert
3. Remove lagacy projects from build.sh1 script. These projects are no longer developed.

**Comment by wojtpl2** [comment]
Idea of props file is from corefx repo. eg: https://github.com/dotnet/corefx/blob/master/src/System.AppContext/dir.props

Now you can change version in https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/dir.props

There is article about props file: https://www.thomaslevesque.com/2017/09/18/common-msbuild-properties-and-items-with-directory-build-props/

Eg: Int this file you can add nuget reference to all projects or create variable with version of nuget reference ...

**Comment by wojtpl2** [comment]
JetBrains.Annotations now is marked like private asserts. There is information about it https://stackoverflow.com/questions/46401170/should-jetbrains-annotations-be-declared-as-a-private-asset-in-my-csproj-files?rq=1

**Comment by Mike-EEE** [comment]
COOL!  I know that was a thorn in your side. 😄
