### ISSUE TITLE
type="" is Emitted with References

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#17]
In looking at some serialized examples, I see that the `type` attribute is emitted along with the `ref` attribute:
```
<ObjectA type="ExtendedXmlSerialization.Test.TestObject.TestClassReference" ref="1" />
```

Is this required?  I am thinking it should be:

```
<ObjectA ref="1" />
```

... as once an object is in memory, the object type (or any data for that matter) is not necessary.  I can look at a PR to fix this if needed.

**Comment by wojtpl2** [comment]
I think you right. You can do PR.

**Comment by wojtpl2** [comment]
I've updated test that hasn't passed after your changes. All function should work for inharitance.

**Comment by wojtpl2** [comment]
Thank for your effort!
