### ISSUE TITLE
How to prevent capacity element from the rendered xml?

### ISSUE THREAD

**Issue by umutesen** [wojtpl2/ExtendedXmlSerializer#171]
The following element is added for all properties of type list, what's the point?

`<Capacity>4</Capacity>`

**Comment by Mike-EEE** [comment]
Hey @umutesen thanks for asking this.  We actually have a pretty robust member selection system but unfortunately the configuration API doesn't work with it very well at present.  For v3 it should be a lot better. 

To keep members from emitting their values, you basically have to [add a `MemberInfo` to a blacklist.](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/3ad1aa16835f3309300f72d05e731df4cb685e8c/src/ExtendedXmlSerializer/ExtensionModel/Content/Extensions.cs#L82-L84).  

What's cool is that you can apply this based on an entire type, or entire generic type in this case.  Where any type that inherits from `IList<>` will not emit a property.  Unfortunately as I mentioned, our configuration doesn't play nicely with this, so I added a quick extension method to help you out ([example](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue171Tests.cs#L12-L18)).

You will have to use our preview here to use this:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Now, if you have a specific list type (like `List<int>`), this actually works now and I have provided [you an example here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue171Tests.cs#L21-L26).

Let me know if you have any questions around any of this!
