### ISSUE TITLE
Serialize List of objects without Root Element?

### ISSUE THREAD

**Issue by umutesen** [wojtpl2/ExtendedXmlSerializer#172]
Consider the following classes:
```
public class Course
{
    public string Title { get; set; }
    public List<Student> Students { get; set; }
}

public class Student
{
    public string Name { get; set; }
}
```
The desired output is the following xml:
```
<Course>
  <Title>Engineering</Title>
  <Student>
    <Name>John Doe</Name>
  </Student>
  <Student>
    <Name>Jane Doe</Name>
  </Student>
   ...
</Course>
```
Serilizing an instance of a course object generates xml with Students as wrapper element. I tried adding `[XmlElement("Student")]` to the collection property but it did not work. It still generates a wrapping Students element. 

The generated xml also has the following namespaces, even though I enabled implicit typing with `EnableImplicitTyping`. How do I tell the serializer to remove the namespaces?
`xmlns:exs="https://extendedxmlserializer.github.io/v2" xmlns:ns1="clr-namespace:MyProject;assembly=MyProjects" xmlns:sys="https://extendedxmlserializer.github.io/system"`

I really do not want to perform post serialization hacks (already thought about using string.replace :) )

**Comment by Mike-EEE** [comment]
Looks like we're 1 for 2 here, @umutesen.  [I have added an example](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/f86e707fe9020c9fcb8800e47c44e632a249de71/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue172Tests.cs) showing implicit typing working as expected.  My hunch is that you did not add the `List<Student>` which was adding all those attributes for you.

The other one is trickier.  It's basically a "default content" property that is applied per object.  System.Xaml has this via the `ContentPropertyAttribute` and XML does indeed (just verified) have this for XML via the `XmlElement` as prescribed above.

Unfortunately the v2 collections engine is a bit of a mess.  We're writing v3 now and it should be a lot easier to implement something like this.  Let's see if we can get it in there.

**Comment by umutesen** [comment]
Thank you for creating an example, however, the example seems to test against an output that has `<Students></Students>` wrapper element. I only require the individual students to be shown without a wrapping `<Students></Students>` element. Please refer to the desired output in my question.

I am looking forward to the v3 release! :)

**Comment by Mike-EEE** [comment]
Indeed, what I meant by being 1 for 2, @umutesen.  Meaning we can accommodate for one of your requests at the moment (implicit typing) but not the other (default content). 😄
