### ISSUE TITLE
Serializer does not respect the XmlEnum attribute 

### ISSUE THREAD

**Issue by umutesen** [wojtpl2/ExtendedXmlSerializer#174]
Suppose I have the following enum:

```
    public enum SessionTypeEnum
    {
        /// <remarks />
        [XmlEnum("My Training List")] MyTrainingList,

        /// <remarks />
        [XmlEnum("Training List")] TrainingList,

        /// <remarks />
        [XmlEnum("Service List")]
        ServiceList
    }
```

When I serialize an object with a property of the above enum, the selected value is not the `Name` property specified in the `XmlEnum` attribute.

e.g. for ServiceList, I expect the serializer to generate "Service List", but it generates ServiceList. Do I need to use another attribute?

**Comment by Mike-EEE** [comment]
Ahh the conflict. You are actually increasing document size by utilizing this, but on the other hand we do strive to be as compatible with the classic serializer where possible -- for better or for worse. 😄  This was an easy fix and you can try it out here:

https://www.myget.org/F/wojtpl2/api/v3/index.json

Please let us know if you find any additional issues.  The easier to fix, the better. 😉

**Comment by umutesen** [comment]
I am aware that the document size will increase, however, I will be submitting the XML to an external web service, which requires the enum values to match their schema...

Anyway, the project had reference to the `AspCore` package, changing that to the full package on MyGet solved the issue ☺️ 

Thank you for your help, it is much appreciated.

**Comment by Mike-EEE** [comment]
OK with you... there is always XSLT as well.  More work but the "right" way of doing it.

Also, just to be sure here, are you saying this `AspCore` reference was in our nuget/sources or with your own project.  I want to make sure we're not mucking something up inadvertently.

**Comment by umutesen** [comment]
The reference to `ExtendedXmlSerializer.AspCore` was in my project, obtained from `nuget.org` feed.

I uninstalled it from my project and installed `ExtendedXmlSerializer` package from `myget` feed.

Hope this helps.

**Comment by Mike-EEE** [comment]
Ah, yes indeed... that is from v1.x. :)  Great, thanks for the info and glad we could get you setup up correctly. 👍
