### ISSUE TITLE
Custom Serialization for a property but not the class of the property

### ISSUE THREAD

**Issue by mjalil** [wojtpl2/ExtendedXmlSerializer#180]
Hello Devs,
    I need a way to customize serialization of a property in a class but not customize serialization of property class everywhere.
like this:

    public class Foo
    {
        public Bar Bar1{get; set;} // <= just need to customize serialization of this
        public Bar Bar2{get; set;} // <= this should not be custom serialized
    }
another issue is i don't know how to extend ExtendedXmlSerliazer. in the quick start guide it seems it just limited to what is said. what is ISerializer? how to use it? who the library is organized? this questions might be in a new issue/doc, with a title like 'developer guid'

**Comment by Mike-EEE** [comment]
Hey @mjalil thanks for checking out our repo here.  When you say customize the serialization, what are you looking to achieve exactly? Modify the input/output?

Extending the serializer for v2 is a little undocumented at this point, although there are a myriad examples in the code base, of course. For v3 we'll be a little more open about it, but you should be able to do anything you would like with your scenario.

In any case I have gone ahead and created a simple example of our extension model for you here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue180Tests.cs

Hopefully that will show you how all the pieces fit together.  Please let me know if you have any questions around this and I will try to get you pointed in the right direction.

**Comment by mjalil** [comment]
Hi @Mike-EEE ,
Sorry for late response. I can not comment from my pc, it is a security limitation in our company( 😣).
I dived into the code and found out how should I write an expression for it, just when you were writing the above guide.I checked that example with my code and was same.

Thanks
