### ISSUE TITLE
Exception on deserialization of IDictionary

### ISSUE THREAD

**Issue by mjalil** [wojtpl2/ExtendedXmlSerializer#181]
Hi there,
I wrote a unit test against version 2.1.3 that show the exception:
```csharp
using ExtendedXmlSerializer.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using Xunit;

namespace ExtendedXmlSerializer.Tests
{
    public class Class1
    {
        [Fact]
        public void TestDictionarySerialization()
        {
            var data = new Model();
            data.Init();
            var tempDir = Path.GetTempPath();
            var tempFile = Path.Combine(tempDir, "test.xml");
            var serializer = new ConfigurationContainer().Create();
            using (XmlWriter writer = XmlWriter.Create(tempFile, new XmlWriterSettings { Indent = true }))
                serializer.Serialize(writer, data);
            using (XmlReader reader = XmlReader.Create(tempFile))
            {
                var result = (Model)serializer.Deserialize(reader);
            }
        }
    }

    #region Test Data
    class Model
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IDictionary<string, string> Map { get; set; } = new Dictionary<string, string>();

        public void Init()
        {
            Id = 2;
            Name = "Parent";
            Map = new Dictionary<string, string> { { "test", "test1" }, { "test2", "test2" } };
        }
    }
    #endregion Test Data
}
```

the result `test.xml` is as below :
```xml
<?xml version="1.0" encoding="utf-8"?>
<Model xmlns="clr-namespace:ExtendedXmlSerializer.Tests;assembly=ExtendedXmlSerializer.Tests">
  <Id>2</Id>
  <Name>Parent</Name>
  <Map xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="sys:Dictionary[sys:string,sys:string]">
    <sys:Item>
      <Key>test</Key>
      <Value>test1</Value>
    </sys:Item>
    <sys:Item>
      <Key>test2</Key>
      <Value>test2</Value>
    </sys:Item>
  </Map>
</Model>
```
the serializer can not deserialize `Map` property

**Comment by Mike-EEE** [comment]
Wow that is strange @mjalil thanks for that.  It seems we have an issue with using `XmlReader`s directly.  If you create an `XmlReader` using our `XmlReaderFactory` it works OK.  I have created an example for you here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue181Tests.cs

That should get you unblocked for now.  I'll see if I can figure out why `XmlReader` don't "just work" in the meantime.

**Comment by mjalil** [comment]
thanks @Mike-EEE 
XmlReaderFactory worked. I stepped into debug and see a  XmlNameSpaceManager that could not resolve `sys` namespace to its uri. in XmlReaderFactory a NameTable is created that I don't create when I use `XmlReader.Create`. this may help to find out the root cause

**Comment by Mike-EEE** [comment]
Alright, awesome.  Thank you for pointing out this issue @mjalil.  It's kind of embarrassing, TBH. 😄 All of our testing has been geared towards `XmlReader`s that have been created via the `XmlReaderFactory` but we never tested the VERY OBVIOUS SCENARIO of creating them as traditionally done via the `XmlReader.Create`.  Luckily all the components used to do this were internal and this has been addressed with no breaking changes.

This fix is now available via our preview feed at:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Please try it out and see how it treats you.

@wojtpl2 this might be something worth deploying sooner than later, if we can.  I'm surprised it hasn't been reported yet.  I guess that shows how much everyone is using our extension methods.  Or I'd like to think that, at least. 😆

**Comment by wojtpl2** [comment]
We should create documentation for extension methods. Our documentation is really poor :wink:

**Comment by Mike-EEE** [comment]
Alright, I believe this issue has been resolved.  If not, please let me know if you have any concerns/questions and we will take it from there. 👍
