### ISSUE TITLE
Dynamically ignore members

### ISSUE THREAD

**Issue by chucker** [wojtpl2/ExtendedXmlSerializer#182]
I'm trying to only emit certain properties as elements in certain situations. For example:

```csharp
public class Leistungszeitraum
{
    public enum LeistungszeitraumTyp
    {
        Tag = 1,
        Monat
    }

    [XmlAttribute]
    public LeistungszeitraumTyp Typ { get; set; }

    public DateTime Tag { get; set; }
    public string Monat { get; set; }

    //[EditorBrowsable(EditorBrowsableState.Never)]
    //public bool ShouldSerializeTag()
    //    => Typ == LeistungszeitraumTyp.Tag;

    //[EditorBrowsable(EditorBrowsableState.Never)]
    //public bool ShouldSerializeMonat()
    //    => Typ == LeistungszeitraumTyp.Monat;
}
```

With classic `XmlSerializer`, I can accomplish this with the commented-out `ShouldSerialize*` members. This doesn't appear to be supported by `ExtendedXmlSerializer`. Instead, [this comment](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/169#issuecomment-365573872) suggests using `EmitWhen`, but that doesn't appear to work for me:

```csharp
var serializer = new ConfigurationContainer()
                 .Type<Leistungszeitraum>(c =>
                 {
                     c.Member(x => x.Tag).EmitWhen(x => x.Typ == Leistungszeitraum.LeistungszeitraumTyp.Tag);
                     c.Member(x => x.Monat).EmitWhen(x => x.Typ == Leistungszeitraum.LeistungszeitraumTyp.Monat);
                 })
                 .Create();
```

Instead, this apparently defines whether the entire _type_ gets emitted or not. 

Do I need to use the other overload of `Member()`?

**Comment by Mike-EEE** [comment]
Boh... thanks for pointing this out @chucker.  It's sort of funny that I absolutely hate the `ShouldSerialize`* magic string/definition conventions but I never put in a suitable replacement. 😆  It's technically an enhancement but really it's a bug.  I will try to have something for you by EOD today to remedy this.

**Comment by chucker** [comment]
Hey,

are you sure you published it? I added the feed and only see v2.1.3, even with 'Include prerelease' enabled and Package source set to your feed.

As for the German (yup, it's German), I apologize for not translating. It's basically an enum of different date/time representations: when set to "Tag", it refers to a specific day; when set to "Monat", it refers to a month (i.e. a range of ~30 days, if you will). There's also "Zeitraum", which refers to an explicit range of days, and which I omitted for brevity. So, Leistungszeitraum is one of these:

```csharp
    Leistungszeitraum = new Leistungszeitraum
    {
        Typ = Leistungszeitraum.LeistungszeitraumTyp.Tag,
        Tag = invoice.Tag
    };
//or
    Leistungszeitraum = new Leistungszeitraum
    {
        Typ = Leistungszeitraum.LeistungszeitraumTyp.Monat,
        Monat = invoice.Monat
    };
//or
    Leistungszeitraum = new Leistungszeitraum
    {
        Typ = Leistungszeitraum.LeistungszeitraumTyp.Zeitraum,
        Von = invoice.Von,
        Bis = invoice.Bis
    };
```

And the resulting node should be one of these three:

```xml
<Leistungszeitraum Typ="Tag">
    <Tag>2017-08-13</Tag>
</Leistungszeitraum>
<!--or-->
<Leistungszeitraum Typ="Monat">
    <Monat>2017-08-01</Monat>
</Leistungszeitraum>
<!--or-->
<Leistungszeitraum Typ="Zeitraum">
    <Von>2017-08-11</Von>
    <Bis>2017-08-13</Bis>
</Leistungszeitraum>
```

I could presumably achieve something similar using an abstract class, but that seems like a lot more overhead.

As for the tests: does it matter that `Leistungszeitraum` isn't the root element? As in, do I need to configure a nested element differently?

Thanks!

**Comment by chucker** [comment]
Sorry, hadn't gotten a chance to test it. It works as expected.

Regarding the package, I had to remove it from the local package cache _and_ make sure the custom feed was listed _before_ nuget.org (makes sense, but someone else may overlook this part). Is there a reason you aren't simply giving the package its own pre-release version, like `2.1.4-issue182`? That would fix the caching/precedence issues. (Does the CI not support this?)

Anyway, thanks for implementing this!

**Comment by Mike-EEE** [comment]
Sweet!  Glad to hear that works.  As for our release experience.  It has popped up a few times, but [now we have an issue to track it](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/184). 😄 

Please let us know if there are any further issues and we will take a look into it.  Thanks again for bringing this to our attention!  Closing for now.
