### ISSUE TITLE
How to develop an extention that : makes implicit all namespaces and emit type attribute only for interface properties 

### ISSUE THREAD

**Issue by mjalil** [wojtpl2/ExtendedXmlSerializer#183]
In early versions of the project there was a `type` attribute that preserve the concrete type of an interface property. I need such that attribute. Also I don't care about xml namespaces. Indeed I prefer to have no namespaces at all

**Comment by Mike-EEE** [comment]
Hi @mjalil we have indeed moved the v1 `type` to `exs:type` in v2. It is used for properties that are interfaces as you are describing.

Are you having trouble serializing an object by chance?  We should be able to serialize anything you have, so if you have something that is having trouble please share it if you can and I will do my best to help you with it.

**Comment by mjalil** [comment]
Hey @Mike-EEE, 
No trouble in serialization.
I know and saw the `exs:type`attribute. but I need to rename it to something else like `x-type` and embed the namespaces and assembly in it instead of a namespace. Indeed I need to have an assembly qualified type name in the `x-type`. Let me describe my needs with a sample xml. 
```xml
<Model>
    <PropertyWithInterface x-type="TheProject.ConcreteImplementation, TheProject">
       ... 
    </PropertyWithInterface>
</Model>
```
Notice that there is no namespaces at all. Just in `x-type` attribute and just for properties with interface. I just use the xml **_notation_**, don't want an xml with full standard specifications. I don't care about xml namespaces because I know the type of a property on deserialization. Just don't the know the type of concrete class, and the `x-type` resolves it

**Comment by Mike-EEE** [comment]
Alright, well I am not sure we will be able to help you with `x-type` with our current version. You could conceivably take our output and run it through XSLT to get what you are looking for.  

I just checked in a sample for you seen here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue183Tests.cs

It produces results somewhat close to what you are looking for:

```
<?xml version="1.0" encoding="utf-8"?><Issue183Tests-Model xmlns:exs="https://extendedxmlserializer.github.io/v2"><PropertyWithInterface exs:type="Issue183Tests-Implementation" /></Issue183Tests-Model>
```

Unfortunately, you will not get around the `exs` definition as there needs to be some differentiation in namespaces from the element and the attribute.  If `exs` was not there, `type` would resolve to the namespace that `Issue183Tests-Model` is in.

**Comment by Mike-EEE** [comment]
I will be closing this issue for now.  Please let me know if you have any additional questions/discussion around this and I will be happy to re-open it for you.
