### ISSUE TITLE
UseOptimizedNamespaces never finishes

### ISSUE THREAD

**Issue by eluchsinger** [wojtpl2/ExtendedXmlSerializer#188]
When I try using the `UseOptimizedNamespaces()` extension method, the serialization of the objects never finishes.

This is how I do the serialization inside a custom `OutputFormatter`: 

```csharp
public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
{
    var configurationContainer = new ConfigurationContainer()
        .UseOptimizedNamespaces();
    var serializer = configurationContainer.Create();
    var result = serializer.Serialize(context.Object);
    return context.HttpContext.Response.WriteAsync(result);
}
```

Am I doing something wrong or is this a known problem? I could not find an issue that describes this problem.

**Comment by Mike-EEE** [comment]
Weird.  Is this with a particular object or all objects?  Also, are you able to serialize this object(s) in a unit test, by chance?

**Comment by eluchsinger** [comment]
I do not have a Unit Test. Maybe I can tell you more next week.

**Comment by eluchsinger** [comment]
I have not been able to reproduce the bug with a unit test using this repo. It must have to do something with the code around the serialization. I will open a new issue, if I can narrow down the bug.

**Comment by Mike-EEE** [comment]
ok cool... let us know if you find anything else and we'll look into it for you, @eluchsinger. 👍

**Comment by eluchsinger** [comment]
@Mike-EEE To be honest, I think it's a performance bug or something. My memory usage grows by 3 when I use that method and then the garbage collector starts running pretty often. Maybe it falls into an endless loop or something?
I don't have time to do any further tests here or narrow down where the problem lies, because I would have to reproduce the data structure. Just saying this so it's noted ;).
Cheers! Nice library btw.
