### ISSUE TITLE
Default Emit Behavior for v2

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#19]
Another issue to be aware of that should be resolved for v2:

Currently default values for enumerations (the first value) are emitted.

So in the example of `TestClassPrimitiveTypes`, it currently expects this in the results:

`<PropEnum>EnumValue1</PropEnum>`

When in fact that should not be emitted at all.

**Comment by wojtpl2** [comment]
In this case we should check how works standard Xml serializer. Do you know?

**Comment by Mike-EEE** [comment]
#LULZ!  This is what I hate about XmlSerializer!

http://stackoverflow.com/questions/15357589/how-to-tell-xmlserializer-to-serialize-properties-with-defautvalue-always

Gotta use DataContractSerializer instead.

This is why I am helping you out, because there seems to be dozens of these types of "answers" on SO.  I shouldn't have to go to another serializer to get the functionality I am looking for.  It should "just work." 😛 

FWIW I have this already solved in my v2.0 serializer.  I hit a snag but will try to get it done today.

**Comment by wojtpl2** [comment]
OK. I'm waiting for your changes... I've created branch v2.0.0.

**Comment by wojtpl2** [comment]
Do you have any problems with your changes?

**Comment by Mike-EEE** [comment]
Ah, yesterday was a bad day.  I have one test to finish up here (properties on lists), and then gotta clean up the code and send it your way!  Maybe about 3-4 more hours.  Hopefully. 👍

**Comment by Mike-EEE** [comment]
OK I finally got all the tests I care about (all of them :)) passing.  I am honestly embarrassed by how long this has taken and how much code there is. :/  If anything you can review it and tell me you hate it, so I can save another week or so of additional work in writing the deserializer. :)  I am cleaning up the code now and hope to have something here in an hour or two.  Wayyyyy too much work here on my part!

**Comment by wojtpl2** [comment]
I'm very curious about what you did ;)

**Comment by Mike-EEE** [comment]
WHEW!  There you go. :P  It's basically a rewrite.  Sort of embarrassing but sort of cool. :)  I actually have a huge migraine right now. :(  So I will be calling it a day and will get back to you tomorrow.  Hope you can make sense of all the changes!

**Comment by Mike-EEE** [comment]
I am thinking we need an `IExtendedXmlConfiguration.EmitDefaultValues(bool)` method for this issue/feature.  Thoughts?

The only thing I can think of is that XmlSerializer does NOT emit default values for everything but Enums, which is silly and of course complicates this.

Maybe `IExtendedXmlConfiguration.EmitDefaultValues(params Type[] types)` that you pass in the types you want to emit defaults?  Might be better.  Emitting default values should be the exception and not the norm.

**Comment by wojtpl2** [comment]
It is good idea! I'll add these methods.

**Comment by Mike-EEE** [comment]
I mentioned in #64 that I would open a new issue, but I think this issue fits the bill already.

We should decide on default emit behavior for v2:

1.  Do we want to use `XmlSerializer`'s behavior?  Essentially all null values except for `Enum`s are emitted.  This seems a little strange to me.
1. We could always emit values by default.  This is performance-friendly (as there are no checks) but doesn't make much sense otherwise.
1. We could emit only when the value is not null.  This is performance-friendly but will still emit if the value is a ValueType (e.g., `null != 0`)
1. We could emit when the value is not the value of a default instance of a class.  This is what #64 introduces ([example](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializerTest/ContentModel/Members/InstanceDefaultsMemberSpecificationsTests.cs#L50-L52)).  The problem with this route is that it does impact performance (~2us) as there is an equality check against a value with each and every call.  This might be worth doing in any case.

To me, there are really only two choices for default emit behavior: Only emit when the value is not null (#3 above) or emit when the value is not a default value for that member (#4 above).  I am open to other considerations, however. :)

**Comment by wojtpl2** [comment]
I have question to point 3. In this case we won't emit default value of enum's, will we?

We have to support point 2. It is default behaviors for standard `XmlSerializer`. You can imagine that you have class where you have property with default value, but not null. Then you set to this property null. In case 1 and 3 you don't serialize this property, because it has null value. When you deserialize this XML property will have default value (not null), but this property should have null value. 

Point 3,4 are good ideas, but they can be dangerous when default value will be changed. 

I think that the worst option is point 1. I'm not sure if we need such behaviour at all.

I think like you that we should choose point 3 or 4. Do you plan to support 2, 3 and 4 options? 

In the configuration it may look like this:
cfg => cfg.SetEmitBehaviour(DefaultValueEmitBehaviour.DoNotSerializeNullValue)

Point 2 DefaultValueEmitBehaviour.SerializeEvertything
Point 3 DefaultValueEmitBehaviour.DoNotSerializeNullValue
Point 4 DefaultValueEmitBehaviour.DoNotSerializeDefaultValue

In the future we can support set in configuration default value:
cfg => cfg.ConfigureType<Type>().Property(p=>p.ValueBool).Default(true).

Microsoft has other feature http://stackoverflow.com/a/9430339/4809321 
but it is strange to me. This feature isn't documented.

**Comment by Mike-EEE** [comment]
Ah!  yes, sorry that I didn't make that clear.  *all* of the above are supported, for sure.  It is what is the _default_ behavior is that question I am wanting to answer. :)

As for the configuration, I will have to put some more thought into this.  Maybe:

```
cfg.Emit(EmitBehaviors.Always)
cfg.Emit(EmitBehaviors.Classic) // `XmlSerializer`
cfg.Emit(EmitBehaviors.WhenNotDefault)
cfg.Emit(EmitBehaviors.WhenNotNull)
```

`EmitBehaviors` would be a static class of `ISpecification<object>` (or some equivalent) instances.  This way consumers can make their own as well.

As for that StackOverflow question, yes, that is terrible. :P  You never want to tightly couple solutions to  metadata/attributes and polluting your POCO with additional properties makes it doubly bad.

**Comment by wojtpl2** [comment]
Your configuration will be the best.

**Comment by Mike-EEE** [comment]
Haha thanks.  We still haven't decided on the default behavior, however. :)  Should it be `cfg.Emit(EmitBehaviors.WhenNotNull)` ?  I think this is the most expected behavior while also being performant.

**Comment by wojtpl2** [comment]
OK. It is good idea!

**Comment by Mike-EEE** [comment]
OK this is all in v2 now.  Please open a new issue and/or feel free to reopen this one if something is not working as expected.

**Comment by Mike-EEE** [comment]
Pre-release deployment for this feature can be found at these feeds:
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha
