### ISSUE TITLE
Namespace / XmlType

### ISSUE THREAD

**Issue by justeff** [wojtpl2/ExtendedXmlSerializer#191]
Found this XML Serializer by accident :)
I'm a bit playing with it and struggled with some different behaviours regarding to XmlSerilaizer.

```
    internal class Program
    {
        [XmlTypeAttribute(Namespace = "http://test.org/schema/test")]
        [XmlRootAttribute(Namespace = "http://test.org/schema/test", IsNullable = false)]
        public partial class Test
        {
            [XmlAttribute]
            public string Attribute { get; set; }
            [XmlElement]
            public string Element { get; set; }
        }

        public static void Main()
        {
            Test test = new Test() {Attribute = "aaa", Element = "bbb"};
            var serializer = new ConfigurationContainer().Create();
            var xml = serializer.Serialize(new XmlWriterSettings {Indent = true}, test);
		
            Console.WriteLine(xml);
        }
    }

```
1) If I don't use an explicit name for XmlType, I would expect the class name _Test_ and not _Program-Test_. Is this a desired behaviour?

2) How can I change the default namespace?. I would expect _xmlns="http://test.org/schema/test"_ but get _xmlns="clr-namespace:ConsoleApplication3;assembly=ConsoleApplication3"_

**Comment by Mike-EEE** [comment]
Hey @justeff welcome aboard. :)  We actually do enable both of your requests.  The tricky part about nested classes is that of course you need to have some way of resolving its name.  However, if you specify the `XmlTypeAttribute.TypeName` property we will honor that and the `Namespace` if you make use of the `InspectType` extension method.  

I just now [made an example here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/078753dae55e67c3ffefb36ec4cf2f3c2500e745/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue191Tests.cs) for you to check out. If you have any further questions please let me know. 👍

**Comment by justeff** [comment]
Awesome :) TypeName was also an easy & obvious solution for me. Just noticed the difference behaviour to the MS solution, but _InspectingType_ .... haven't read anything about it in the Docs haha. Thank you very much :)

**Comment by Mike-EEE** [comment]
Yeah, our documentation is a bit of [a sore topic right now](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/189).  I've done a sweep of it but it really deserves its own story.  I've dedicated myself to answering questions like this manually until then.  With any luck it will spur me to write a few more lines of words in there. 😉 

In any case, if you have any other questions/issues, please feel free to let us know.  Closing this one for now.
