### ISSUE TITLE
How to call the IExtendedXmlSerializer from IExtendedXmlCustomSerializer?

### ISSUE THREAD

**Issue by lordmampf** [wojtpl2/ExtendedXmlSerializer#193]
Hello ;)

Thanks for your great library. I just found it and started to implement an ExtendedXmlCustomSerializer.
I want to serialize a property with the default IExtendedXmlSerializer class.
Something like a recursive call.

I read Issue #154. And tried this code:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue154Tests.cs#L174-L186
But the `_serializers` contains only the custom serializers.

I'm looking for something like this:

```
public class RandomTypeSerializer : IExtendedXmlCustomSerializer<RandomType> {
    public void Serializer(XmlWriter writer, RandomType obj) {         
        xmlWriter.WriteAttributeString("Description", obj.Description);
         //   Serializer.Serialize("IRandomType2", obj.RandomType2);
    }
   [...]
}
```

Does the current version supports this? If yes, how to implement it?

My main goal is to serialize an open generic type. This is why my idea is to create an IExtendedXmlCustomSerializer which will store the Typename as string and recreate the generic class.
One property of this generic class is an interface which can have different types and circular references.

**Comment by Mike-EEE** [comment]
Hello. 😁

Sorry for the delay here.  I had some major environmental issues to deal with this past week.  

The problem you present is indeed a tricky one.  I am not very happy with how to deal with it in v2.  I am better with how it is progressing (or has progressed) in v3.

However, there are several ways to go about this and I have provided examples here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/14ed5908649abdf0ab09332324a9b67c7da40c5b/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue193Tests.cs#L18-L56

Please let me know if you have any further questions/problems/complaints around this. 😆

**Comment by lordmampf** [comment]
Hello ;)

Wow! Thank you very much.
There is no delay, when you answer so fast ;)

I was able to get the Serializer running ;) Thanks for your example.

The only thing I changed:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/14ed5908649abdf0ab09332324a9b67c7da40c5b/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue193Tests.cs#L77
to
`var result = typeof(RandomType).IsAssignableFrom(parameter) ? new Serializer(serializer).Adapt() : serializer; `

because if RandomType is an interface it did not work for me ;)

Thank you very much for your support!

**Comment by Mike-EEE** [comment]
OK great!  That's a good point.  We should be using a specification there.  I have gone ahead and updated the example to do this.  Let me know if you have any further questions/issues here and we'll revisit.  Happy to see this worked for you. 👍  Closing for now.

**Comment by lordmampf** [comment]
I just detected another small issue ;)

The `Adapt` extension and the `GenericSerializerAdapter` class are not public.
So I made some small modifications and reflection to get it run in another project ;)

Yesterday I played around with your unit tests only :P
