### ISSUE TITLE
Provide a binary library

### ISSUE THREAD

**Issue by 1342886192** [wojtpl2/ExtendedXmlSerializer#195]
the whole project complied by vs2017, anyone can provide a binary library supported .net 4.0 without have to complied the source code? the library is simple to use and support previouse version ide that is so good!

**Comment by Mike-EEE** [comment]
Hey @1342886192 thanks for writing in and the kind words. :)  

Unfortunately we are pegged to 4.5 as .NET Standard 2.0 supports that as a minimum framework version. :(

Do note, though, that Visual Studio Community 2017 is free.  :D

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=15

**Comment by 1342886192** [comment]
Hey @Mike-EEE thank you for your response, any you provide a binary library support for .net 4.5?

Visual Studio Community 2017 is too big to complied the library.

you can send me an email: 1342886192@qq.com.

thank you :)

**Comment by Mike-EEE** [comment]
Which development environment do you have. @1342886192?  Does it have nuget?  It's easier to use NuGet if you have it.

**Comment by 1342886192** [comment]
thank you!
good job!
have a nice day!

**Comment by Mike-EEE** [comment]
Hehe sure thing.  Those are the problems I like to have. :)  Please let me know if you have any further questions/issues and feel free to either comment here or open a new issue.  Closing this issue for now.
