### ISSUE TITLE
Private properties/classes and attributes from System.Attribute/ComponentModel

### ISSUE THREAD

**Issue by gimi87** [wojtpl2/ExtendedXmlSerializer#197]
Hello :)

I am trying to serialize/deserialize for example `System.Windows.Forms.Button` as below:
````csharp
Button btn = new Button();
var contents =
	new ConfigurationContainer()
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, btn);
````
This causes an `System.InvalidOperationException` with:
```
The serializer for type 'System.Drawing.Font' could not be found.
Please ensure that the type is a valid type can be activated.
The default behavior requires an empty public constructor on the (non-abstract) class to activate.
```
OK. Some classes have no parameterless constuctor. Let's build an empty serializers to prevent Cursor/Font to throw an exception:
````csharp
public class CursorSerializer : IExtendedXmlCustomSerializer<Cursor>
{
	public Cursor Deserialize(XElement xElement) => null;
	public void Serializer(XmlWriter xmlWriter, Cursor obj) { }
}
public class FontSerializer : IExtendedXmlCustomSerializer<Font>
{
	public Font Deserialize(XElement xElement) => null;
	public void Serializer(XmlWriter xmlWriter, Font obj) { }
}
````
and extend the call:
````csharp
Button btn = new Button();
var contents =
	new ConfigurationContainer()
		.Type<Cursor>().CustomSerializer(new CursorSerializer())
		.Type<Font>().CustomSerializer(new FontSerializer())
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, btn);
````
This causes an `System.InvalidOperationException` with:
````
The serializer for type 'System.Windows.Forms.Control+ControlNativeWindow' could not be found.
Please ensure that the type is a valid type can be activated.
The default behavior requires an empty public constructor on the (non-abstract) class to activate.
````
The struct/class `System.Windows.Forms.Control+ControlNativeWindow` is not visible and I don't know how to prevent the exception.
Let's extend the Button class with property with attribute:
````csharp
[AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = true)]
public sealed class ButtonExPropertyAttribute : Attribute { }

public class ButtonEx : Button
{
	[ButtonExPropertyAttribute]
	public int MyProperty { get; set; }
}
````
My questions are:
1) How to serialize only settable and public properties?
2) How to manipulate with property attributes (ignoring/selecting only)?

**Comment by Mike-EEE** [comment]
Wow... very ambitious, @gimi87. 😆

I took a look at this.  The irony is that objects such as `Cursor` and other WinForms elements make use of serialization constructors, but when you point the classic `XmlSerializer` at it, it throws up. 😮 

So in our case we need a clear way to easily avoid types that cannot be serialized outright.  You can use the custom serializers like above.  However, if I understand correctly you want to save/persist the state of common fields in an element such as size/position, etc.  I had to make a new extension, but you _should_ be able to get what you are looking for here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/926001c702abc257a5aa2d50f295f3e01f1fd33c/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue197Tests.cs

Do note that I could not use the actual `System.Windows.Forms` assembly as we're trying to keep references low but most importantly .NET Core can't load it (and I **hate** ifdefs!).

Anyways, take a look at that and let me know what you think and/or if you run into any issues. 👍

**Comment by gimi87** [comment]
Thank you. It lets me avoid the exceptions. But... I have another weird situation.
Assume that I have classes:
````csharp
[AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = true)]
public sealed class ButtonExPropertyAttribute : System.Attribute { }

public class ButtonExBase : System.Windows.Forms.Button
{
	[ButtonExProperty]
	public int FirstPropButtonExBase { get; set; }
	public int SecondPropButtonExBase { get; set; }
}

public class ButtonEx : ButtonExBase
{
	[ButtonExProperty]
	public int PropButtonEx { get; set; }
}
````
Look at the listing below:
````csharp
ButtonEx btn = new ButtonEx {
	PropButtonEx = 3,
	FirstPropButtonExBase = 1, SecondPropButtonExBase = 2,
	Text = "TBD"
};
var contents = new ConfigurationContainer().Extend(FallbackSerializationExtension.Default)
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, btn);
````
That creates long XML listing:
````xml
?xml version="1.0" encoding="utf-8"?>
<Form1-ButtonEx xmlns="clr-namespace:Panel;assembly=Panel">
  <FirstPropButtonExBase>1</FirstPropButtonExBase>
  <SecondPropButtonExBase>2</SecondPropButtonExBase>
  <PropButtonEx>3</PropButtonEx>
  <AutoSizeMode>GrowOnly</AutoSizeMode>
  <DialogResult>None</DialogResult>
  <AutoEllipsis>false</AutoEllipsis>
  <AutoSize>false</AutoSize>
  <BackColor />
  <FlatStyle>Standard</FlatStyle>
...
````
From https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.button?redirectedfrom=MSDN&view=netframework-4.7.2 the inheritance is:
Object -> MarshalByRefObject -> Component -> Control -> ButtonBase -> Button.
I can hide all controls up to ButtonBase and first one from Control.
Listings:
````csharp
ButtonEx btn = new ButtonEx { PropButtonEx = 3, FirstPropButtonExBase = 1, SecondPropButtonExBase = 2, Text = "TBD" };
var contents = new ConfigurationContainer().Extend(FallbackSerializationExtension.Default)
		.Type<ButtonEx>()
			.Member(m => m.PropButtonEx).Ignore()
			.Member(m => m.FirstPropButtonExBase).Ignore()
			.Member(m => m.SecondPropButtonExBase).Ignore()
			.Member(m => m.AutoSizeMode).Ignore()
			.Member(m => m.DialogResult).Ignore()
			.Member(m => m.AutoEllipsis).Ignore()
			.Member(m => m.AutoSize).Ignore()
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, btn);
````
````xml
<?xml version="1.0" encoding="utf-8"?>
<Form1-ButtonEx xmlns="clr-namespace:Panel;assembly=Panel">
  <AutoSize>false</AutoSize>
  <BackColor />
  <FlatStyle>Standard</FlatStyle>
````
Why the called `.Member(m => m.AutoSize).Ignore()` is in XML listing (is not ignored)? Is there any extension to ignore all inherited properties (for example from Control class) and then remove from Blacklisted list (opposite of Ignore())?

**Comment by Mike-EEE** [comment]
Alright @gimi87 I believe I got the issue addressed with `Ignore`.  You can find the latest version here on our preview feed:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by gimi87** [comment]
That `Emit` extension was close to the solution (I will use it in another part of application, thanks), but the latest commit solved my problem with `Ignore` method. I can now hide properties precisly and show them back when I want.

But... I ended with another situation with `System.Reflection.AmbiguousMatchException`. Look at the classes:
````csharp
public class ButtonExBase : System.Windows.Forms.Button
{
	public int MyProperty { get; set; }
}

public class ButtonEx : ButtonExBase
{
	public new double MyProperty { get; set; }
}
````
and the listing:
````csharp
ButtonEx btn = new ButtonEx { MyProperty = 2.2 };
var contents =
	new ConfigurationContainer().Extend(FallbackSerializationExtension.Default)
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, btn);
````
This causes an `System.Reflection.AmbiguousMatchException` because of the `new` keyword in the inherited class. Sometimes i want to force the type (because of some functionality in inherited class). I need to use the new keyword at this moment. Do you know the solution how to serialize as `double` in this nonsense case?

**Comment by gimi87** [comment]
Thank you for your patience. Yes... it can be a workaround, but not a good solution, because I have to remember to `Ignore` modified properties.
Look... I prepared a sketch where you can look at the next `System.ArgumentException` 😃
Classes/interfaces:
````csharp
//Interface implementations
public interface IProperty { int MyProperty { get; set; } int RefID { get; set; } }
public class PropertyBase : IProperty { public virtual int MyProperty { get; set; } = 1; public int RefID { get; set; } }
public class PropertyInherit : PropertyBase { public override int MyProperty { get; set; } = 2; }

//Class-handles to interface
public class IPropertyHandleBase
{
	public IProperty HandleToIProperty { get; set; }
}
public class PropertyBaseHandle : IPropertyHandleBase
{
	public new PropertyBase HandleToIProperty { get => base.HandleToIProperty as PropertyBase; set => base.HandleToIProperty = value; }
}
public class PropertyInheritHandle : PropertyBaseHandle
{
	public new PropertyInherit HandleToIProperty { get => base.HandleToIProperty as PropertyInherit; set => base.HandleToIProperty = value; }
}

//Object to serialize/deserialize
public class TestIProperty
{
	public List<IProperty> MyProperties { get; set; } = new List<IProperty>();
	public List<IPropertyHandleBase> MyHandles { get; set; } = new List<IPropertyHandleBase>();
}
````
and the call:
````csharp
PropertyBase prop1 = new PropertyBase { RefID = 1 };
PropertyInherit prop2 = new PropertyInherit { RefID = 2 };
PropertyBaseHandle hand1 = new PropertyBaseHandle { HandleToIProperty = prop1 };
PropertyInheritHandle hand2 = new PropertyInheritHandle { HandleToIProperty = prop2 };

TestIProperty obj = new TestIProperty();
obj.MyProperties.Add(prop1);
obj.MyProperties.Add(prop2);
obj.MyHandles.Add(hand1);
obj.MyHandles.Add(hand2);

var contents =
	new ConfigurationContainer().Extend(FallbackSerializationExtension.Default)
		.Type<IProperty>().EnableReferences(p => p.RefID)
		.Create()
	.Serialize(new XmlWriterSettings { Indent = true }, obj);
````

**Comment by Mike-EEE** [comment]
Oh man... I'M GETTING MY WORKOUT HERE COACH!!! 😂

Relatively easy to resolve the properties.  I *think* it works? 🤔 😁

Please try from the preview feed.

Also, if you find another issue (or I should say _when_ you do 😆) please create a new issue so we can track it there. 👍

**Comment by gimi87** [comment]
Thank you. Very, very much. The problem has been solved. You are the god 😃!

**Comment by Mike-EEE** [comment]
Woohoo!  I am kinda relieved to hear that?! LOL.  No, it's good.  It's a challenge but most importantly it improves quality.  Thank you for your efforts!  I will be closing this now and releasing `2.1.6`.  Please feel free to open another issue of course if you encounter another issue. 👍
