### ISSUE TITLE
EnableReferences() requires public empty ctor even with EnableParameterizedContent() extension

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#203]
Take the following class:

    public class Person
    {
        public Person(string name)
        {
            Name = name;
        }

        public string Name {get; set;}

        public Person Mother {get; set;}

        public Person Father {get; set;}
    }

When attempting:

    using (var xmlWriter = XmlWriter.Create(path, new XmlWriterSettings { Indent = true }))
    {
        var serializer = new ConfigurationContainer().EnableParameterizedContent().EnableReferences().Create();
        serializer.Serialize(xmlWriter, person);
    }

This will fail with `The serializer for type 'TaskSequencer.Actions.RunCommandAction' could not be found.  Please ensure that the type is a valid type can be activated.  The default behavior requires an empty public constructor on the (non-abstract) class to activate.`

This works when Person has an public empty ctor, but not when one isn't present (regardless of whether EnableParameterizedContent() is present or not).

**Comment by Mike-EEE** [comment]
Very close here.  We follow the protobuf rules as [outlined here](https://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html).  This requires that all arguments are read-only and match the same name as their properties.

With the following class:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/e3c45917b49cd595012c6da80dae62441e3e4cf0/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue203Tests.cs#L22-L31

The code emits and passes as expected.

It does look like you've seen #196 which will allow you to modify the specification used here to enable your scenario.  Please feel free to look further into that code there and let me know if you have any further questions.

**Comment by FaustoNascimento** [comment]
Dope! Yeah ... guess sometimes you just need to take a step back and look at it from a different angle. I was so sure that the problem was coming from `EnableReferences()` that I never even contemplated the fact that it was because the property referenced in the ctor had a `public setter` ... sigh... let me test this out when I get to the office tomorrow and I'll close this issue if it works.

**Comment by FaustoNascimento** [comment]
Ok, this can be closed as the issue was completely different than the one advertised and as you said it's intended.
