### ISSUE TITLE
Make FrameworkExtensions public

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#204]
Trying to create a `ISerializerExtension` as per #196 and in accordance to the [test for the same issue](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue196Tests.cs). 

The problem is  the test makes usage of `IServiceRepository.RegisterWithDependencies<TFrom, TTo>()` which lives in the `static class FrameworkExtensions` - and that is `internal`.

Could this class be made public? :)

**Comment by Mike-EEE** [comment]
Good point. :)  We basically have everything sealed and are unsealing things on a case-by-case basis.  I've gone ahead and done this and will push 2.1.8 soon.

**Comment by Mike-EEE** [comment]
Closing this now as this has been deployed.  Please let me know if you have any further questions/requests around this and I will take a look into it.
