### ISSUE TITLE
Discussion Around Parameterized Content

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#205]
Given the class...

    public class Person
    {
        private IList<Person> _friends = new List<Person>();

        public Person(string name)
        {
            Name = name;
        }

        public Person()
        {
        }

        public string Name { get; set; }

        public IList<Person> Friends
        {
            get => _friends;
            set => _friends = value ?? throw new ArgumentNullException();
        }
    }

And invoking it as such:

           var snoopy = new Person("Snoopy");
            var charlieBrown = new Person("Charles \"Charlie\" Brown");
            var sallyBrown = new Person("Sally Brown");
            var marcie = new Person("Marcie");

            snoopy.Friends.Add(charlieBrown);
            snoopy.Friends.Add(sallyBrown);
            snoopy.Friends.Add(marcie);
            snoopy.Friends.Add(charlieBrown); // added twice -- intentional

           var serializer = new ConfigurationContainer().EnableParameterizedContent().EnableReferences().Create();
            
            var serializedPerson = serializer.Serialize(snoopy);
            snoopy = serializer.Deserialize<Person>(serializedPerson);

The serialization will all work as expected, but an exception will be thrown on deserialization: 

    The value "ExtendedXmlSerializer.ExtensionModel.Types.ActivationContext" is not of type "ExsTests.Person" and cannot be used in this generic collection. Parameter name: value

If you comment out the last `Friends.Add` then the object will be properly deserialized *but* `snoopy` will be an empty object - no Friends, no Name. Please fix poor ol' Snoopy!

**Comment by FaustoNascimento** [comment]
Just did some further tests: if I remove the empty ctor and the `public setter` on `Name` then the deserialized `snoopy` has a name, but still no friends. Also tried making `Friends` an auto-property with no default value (not that I would expect that to have an impact on it) but snoopy is still friendless - `snoopy.Friends == null` after deserialization, no matter what.

**Comment by FaustoNascimento** [comment]
It appears to me that the deserializer is *only* ever calling the appropriate ctor and never attempting to set the values of the properties with a (public) setter.

If instead of the above class I use the following:

    public class Person
    {
        public Person(string name, IList<Person> friends)
        {
            Name = name;
            Friends = friends ?? new List<Person>();
        }

        public string Name { get; }

        public IList<Person> Friends { get; }
    }

and attempt to serialize/deserialize it in exactly the same way, then `snoopy` finally has `Friends` (unless `charlieBrown` is added twice, in which case serialization fails with the same exception as above.

**Comment by Mike-EEE** [comment]
Nice find @FaustoNascimento. For some context, the parameterized content was a passing thought/neat idea when I put it in for v2 initially.  It was never meant to be a "first class" feature of v2 but it ended up being that way. :)  We're also running into the issue of numerous extensions that are "just added" but really do not know about each other.  For the most part this has (amazingly) worked, but here is a good example where they step on each other's toes.

The fix was actually very straight forward.  So you should be able to try it from our preview feed now and see how it does.  Let me know if you have any further problems, and if not we will push 2.1.9. 👍

**Comment by Mike-EEE** [comment]
Ah btw @FaustoNascimento the preview feed is here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

:)

Let me know if you run into any further questions/problems/issues and I will help you out here. 👍

**Comment by FaustoNascimento** [comment]
@Mike-EEE ok, I've tested it and ... while it's looking better, `snoopy` still has no `Friends`.

Using the following class (which is as close to the actual class I've got as it gets):

    public class Person
    {
        public Person(string name)
        {
            Name = name;
        }

        public string Name { get; set;  }

        public IList<Person> Friends { get; set;  } = new List<Person>();
    }

And in the following way:

    var snoopy = new Person("Snoopy");
    var charlieBrown = new Person("Charles \"Charlie\" Brown");
    var sallyBrown = new Person("Sally Brown");
    var marcie = new Person("Marcie");

    snoopy.Friends.Add(charlieBrown);
    snoopy.Friends.Add(sallyBrown);
    snoopy.Friends.Add(marcie);
    snoopy.Friends.Add(charlieBrown); // added twice -- intentional

    var serializer = new ConfigurationContainer().EnableReferences().EnableParameterizedContent().Extend(WritableParameterizedContentExtension.Default).Create();
    var x = serializer.Serialize(snoopy);

    return serializer.Deserialize<Person>(x);

`WritableParameterizedContentExtension` is the extension from the #196 tests.

**Comment by FaustoNascimento** [comment]
FYI, even if I remove `Extend(WritableParameterizedContentExtension.Default)` and also remove the public setter from `Name`, snoopy is still friendless.

**Comment by Mike-EEE** [comment]
Ah.. are you able to make the code from the passing test work, @FaustoNascimento?  What is the difference where it stops working for you?

**Comment by FaustoNascimento** [comment]
The difference is that you have a `ctor` that accepts `List<People>`, I don't :)

**Comment by Mike-EEE** [comment]
Ah  I see it.  Make sure you have `friends` passed in as an argument:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/1dc8192ce257a199fc71e06243d96e74dff71d99/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue205Tests.cs#L63-L67

Also, going to post the rules here from the [aforementioned source](https://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html), for completeness 😁:

```
The rules are:

it must not already be marked as an explicit contract
only public fields / properties are considered
any public fields (spit) must be readonly
any public properties must have a get but not a set (on the public API, at least)
there must be exactly one interesting constructor, with parameters that are a case-insensitive match for each field/property in some order (i.e. there must be an obvious 1:1 mapping between members and constructor parameter names)
```

Please let me know if any of those do not work as expected and I will for sure look into it.  I realize you are also using an extension, which is what this is all about of course.  The ask here is to make sure the baseline works **first**, _then_ start adding on your magic. :D

**Comment by FaustoNascimento** [comment]
And while this could be fixed with further extensions, because like you said they don't know about each other it feels to me like it would make more sense to pass some (optional) parameters to `EnableParameterizedContent()` describing how it should behave.

**Comment by Mike-EEE** [comment]
> Think about it, if I have the class...

You lost me at the public setter. 😉

Both the referenced source and EXS (as well as protobuf, the source of the source, lol) all expect and use immutable objects and construction by default.

FWIW this can be solved by using the following class definition along with the writable properties extension:

```
		public class Person
		{
			public Person(string name) : this(name, null, new List<Person>()) {}

			public Person(string name, string nickname, IList<Person> friends)
			{
				Name = name;
				Nickname = nickname;
				Friends = friends;
			}

			public string Name { get; }

			public IList<Person> Friends { get; set;  }

			public string Nickname { get; set; }
		}
```

And yes, the great thing about having an extension-based framework is that you can make extensions to compensate for the things that don't work according to your expectations.  :)

**Comment by FaustoNascimento** [comment]
Sure, but I still need to create a ctor with all properties referenced in my class. And some of my classes have 20+ properties with public setters and I have over 30 classes affected.

It would be easier to just make an empty public ctor, although that also defeats the purpose ...

**Comment by Mike-EEE** [comment]
Hey don't look at me @FaustoNascimento I only followed and implemented the rules as I happened to like and agree with them. 😂  

Also FWIW, generating constructors is a snap with ReSharper.

Otherwise, this is obviously would a great scenario to leverage an extension to see if you can get it to do what you need.  If there are any classes/impediments that you encounter let me know so I can get them removed for you. 👍

**Comment by Mike-EEE** [comment]
Disregard the commit for #205 above.  I am not too good with Git.  Obviously. 😂

**Comment by FaustoNascimento** [comment]
So how would I serialize/deserialize a `FileInfo` or a `FileStream` objects for example? Neither has an empty public ctor and they both have properties with public setters :)

**Comment by Mike-EEE** [comment]
> I thought the extension WritableParameterizedContentExtension basically already did exactly that - allow public setters. Or is it conflicting with EnableParameterizedContent?

This is a workaround for the rules outlined above, but mostly a demonstration of how the extensions work.  The point/value showing how to work around the rules above if you need to do so.

> So how would I serialize/deserialize a FileInfo or a FileStream objects for example?

You can try using the `EnableAllConstructors` extension method which will use private constructors, if you wish. :)

**Comment by FaustoNascimento** [comment]
> This is a workaround for the rules outlined above, but mostly a demonstration of how the extensions work. The point/value showing how to work around the rules above if you need to do so.

I understand that, but the workaround does not work (as expected). I haven't quite understood how the extensions work to be honest, which is why I'm asking how to do it with an extension.

**Comment by FaustoNascimento** [comment]
This might be a different issue altogether, but it doesn't feel like creating own extensions is really that easy because pretty much all interfaces and classes used in the creation of extensions are `internal`.

So if I wanted to create my own version of `ParameterizedMembersExtension` by removing/modifying some of the `Register()` or `Decorate()` calls, I can't.

**Comment by FaustoNascimento** [comment]
Just a thought but ... how about creating 3 extensions for non-empty ctors?

Not going to try to name them, 'cause I suck at that but ...

- One extension that follows the rules of protobuf-net to the letter (the current one)
- One extension that is slightly looser and simply demands that properties set via the ctor have no public setter
- One extension that just doesn't care about public setters on any properties - even the ones set via the ctor.

The middle one would suffice for most classes and encourage immutability of properties set in the ctor (file FileInfo, FileStream - although the parameter names don't match property names, but that's a different issue), but for those cases where that is simply not enough (like mine) there's still the "completely loose" option.

**Comment by Mike-EEE** [comment]
> I understand that, but the workaround does not work (as expected).

It's not _the_ workaround, it's **a** workaround. :) And it does work for how it's intended.  We have now entered into another territory where it does seem more extensions are required.  As such...

> how about creating 3 extensions for non-empty ctors?

Indeed this is an open source project and those extensions are all possible.  Well, one (the first one) is more than that, it's already DONE. 😂  So it sounds like having two extensions made.

As for internal code, there is nothing keeping you from copy/pasting a full sweep code to get what you need for a starting point.  I agree it's not ideal but it seems that you are under the impression that it is the project that is blocking you here.  

Ooooh, but an EVEN BETTER IDEA. :) You are more than free to fork/clone this to your desktop and create your own version to your heart's content,  You can also subsequently submit a PR for your efforts and we can discuss them as appropriate.

You have to keep in mind that we have basically shelved this version as we work towards v3.  That was the intent, which doesn't always meet with the reality.

I am more than happy to have you go through and try to build your extension, unwrap the classes that you need and then send our way via a PR. 👍

**Comment by FaustoNascimento** [comment]
> You have to keep in mind that we have basically shelved this version as we work towards v3.

Apologies, wasn't aware of this, thought that while you were working towards v3, that v2 was still being actively maintained and improved (rather than just bug fixing).

> I agree it's not ideal but it seems that you are under the impression that it is the project that is blocking you here.

Well, not quite. Redesigning my classes is not really an option (having an empty private ctor is an option but it feels like dodging the problem rather than fixing it). But I don't see it as this project blocking me. I've always had alternatives but I thought that v2 was still being actively worked on and that as such I was contributing to this project by highlighting things that are important for developers like myself.

I don't mind creating my own extensions and submitting a PR when they're done - I'd actually prefer it since I'd end up with the knowledge about how to create my own extensions. But right now I don't feel like I know enough about all of the different classes involved to create my own. 

So long as you're happy to potentially devoting more time to teaching me what each class does than what it would take you to implement it I have no problems with creating an extension and submitting a PR.

**Comment by Mike-EEE** [comment]
Yep all of the above, LOL.  The intent was to continue to maintain but not introducing anything too disruptive.  Major features are in and complete.  Luckily everything that has been requested has not required significant work and has gone in pretty smoothly.

TBH I am a bit conflicted about encouraging custom extension development.  I would like to see this grow with a community around it, but v3 will for sure introduce breaking changes.  However, v2 exists and v3 does not. :)  So you gotta go with what works and is present currently.

From my understanding, this issue is resolved, correct?  The existing extensions work as designed but there is a need for additional extensions if I understand correctly.  Please create new (feature request) issue to capture this requirement and close this issue if that works for you.

**Comment by FaustoNascimento** [comment]
This issue is resolved and can be closed, yes. Although could you explain exactly what the extension WritableParameterizedContentExtension (as per #196) does?

It seems to me like it just allows public setters on properties set by the ctor, but not sure if that's the case?

**Comment by Mike-EEE** [comment]
Ah, so what that extension does in particular is demonstrate how to register the necessary components to override the default specification used by parameterized content, in this case allowing writable/settable properties (as this is not allowed in the default rules listed above).

That allows this (default requirements):

```
public class Person
{
    public Person(string name) => Name = name;
    public string Name { get; }
}
```

To be this:

```
public class Person
{
    public Person(string name) => Name = name;
    public string Name { get; set; }
}
```

**Comment by FaustoNascimento** [comment]
Ahh I see. It *allows* properties with setters them (as in, no exception thrown), but *doesn't* map them when deserializing. `Name` gets set through the ctor but if I had another property with a public setter and kept the single parameter ctor when deserialized that property's value would be lost (which is what we saw with the snoopy example above).

Ok, issue closed, opening a feature request for the extensions.
