### ISSUE TITLE
[Feature Request] Add (more) extensions for parameterized constructors

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#207]
As discussed in #205, would be nice if there were a couple more extensions for controlling how serialization/deserialization occurs when dealing with mutable objects that do not have a public/private empty ctor.

I suggest the following:

- One extension that follows the rules of protobuf-net to the letter (currently implemented one)
- One extension that is slightly looser and simply demands that properties set via the ctor have no public setter
- One extension that just doesn't care about public setters on any properties - even the ones set via the ctor.

**Comment by FaustoNascimento** [comment]
Umm... I can't help but move away from this thought that the currently implemented parameterized constructors extension's logic is wrong.

Firstly, because it feels (to me) like the difference between:

`new ConfigurationContainer().Create()`

and 

`new ConfigurationContainer().EnableParameterizedContent().Create()`

is that the second allows parameterized constructors. That's it. It's called `EnabledParameterizedContent()`, it's not called `EnabledParameterizedContentAndDisablePublicSetterProperties()`. 

The default state (with no extensions) is that public setters are allowed *but* a public empty ctor is required. By calling `EnabledParameterizedContent()` my expectation is that I keep all of the existing functionality (public setters, empty ctor) but add something on top of what of that (allowing parameterized constructors) - that's not the case with this extension. It's literally throwing the old rule book out the window and re-writing a completely new one from scratch. And maybe that's just a naming issue, but still needed to highlight it.

The second reason, and perhaps the the most important one, is that I don't think a library should *force* its consumers to work in a certain way unless there's a technical limitation behind it. Microsoft's XmlSerializer does not support classes without a public empty ctor - but that's a limitation of the serializer (sure, it's due to how it was written, but the point stands) rather than them enforcing a set of rules they came up with.

To say that parameterized constructors are supported but *only if* you follow these set of rules because I like immutable objects (rather than because of a technical reason) feels wrong and not the decision that a library should take - rather that's a decision for the consumer of the library designing the classes.

As such, I think that the rules for parameterized contructors should simply be:

 `there must be exactly one interesting constructor, with parameters that are a case-insensitive match for each field/property in some order (i.e. there must be an obvious 1:1 mapping between members and constructor parameter names)`

And this for the sole reason that you **need** a way to map ctor parameters to properties/fields. That's it, nothing else.

And thing is ... such an extension would work in *all* scenarios - it would work on immutable classes as well as mutable ones.

If you want to *encourage* immutability and give users a way of ensuring only immutable objects can be serialized, it feels like that should be an extra extension of its own (but then it would need to throw when an object is not immutable rather than fully serializing the object but only partially deserializing it back).

So maybe this should instead be about the creation of separate smaller extensions such as...

`EnforceImmutability()` or `EnforceImmutability(p => p.Name == "Name")`

At the same time, imho it would make sense to use attributes to override the 1:1 name mapping rule of property to a ctor parameter.

i.e., instead of having to write a custom serializer for this (taken directly from readme):

```
public class TestClass
{
    public TestClass(string paramStr, int paramInt)
    {
        PropStr = paramStr;
        PropInt = paramInt;
    }

    public string PropStr { get; private set; }
    public int PropInt { get; private set; }
}
```

instead we'd just do this:

```
public class TestClass
{
    public TestClass(string paramStr, int paramInt)
    {
        PropStr = paramStr;
        PropInt = paramInt;
    }

    [Serializer(ContructorParameterName = "paramStr")]
    public string PropStr { get; private set; }

    [Serializer(ContructorParameterName = "paramInt")]
    public int PropInt { get; private set; }
}
```

Thoughts?

**Comment by wojtpl2** [comment]
How about .Property(p => p.PropStr).SetConstructorParametrName("paramStr").

czw., 20 wrz 2018 o 11:10 FaustoNascimento <notifications@github.com>
napisał(a):

**Comment by Mike-EEE** [comment]
Yep... nodding along.  To re-iterate this was a "simple" (or cool) idea I had to implement and showcase the extension (along with the "Xamlness" functionality) and it's now taken a life of its own. 😆

The rules do exist to ensure immutability and also to simplify class design.  Classes have less characters and resulting "features" to worry about and to account for, which is one of the tenants of immutability of course.

FWIW the underlying principles here are immutability and also POCOs or POICOs -- _plain_ ol' Immutable CLR Objects.  _Plain_ being the goal in that no metadata are required to enable functionality.

While they can be used, the `ConfigurationContainer` is the go-to for such cases, but also allowing for metadata/attributes if they do exist.

So something like `new ConfigurationContainer().Type<MyClass>().Member(x=>x.Member).ConstructorName("name");`

In this case, yes we are indeed enforcing those rules as those are the rules that we have abiding by throughout v2 and also going forward for v3.  In my opinion, these enforce good design principles and as a result lower cost of development and maintanence.  However again having the ability to create your own extensions to circumvent these enforced rules are what this project is all about. :)

**Comment by FaustoNascimento** [comment]
> How about .Property(p => p.PropStr).SetConstructorParametrName("paramStr").

That feels like a good alternative, happy with that!

**Comment by FaustoNascimento** [comment]
> The rules do exist to ensure immutability and also to simplify class design.

But this is not something a library such as this should enforce. Someone might have genuine reasons for needing something outside of that rule set. You're basically saying "the library *can do this*, but because we think this is bad class design, we prevent you from doing it unless you create your own extensions."

> In this case, yes we are indeed enforcing those rules as those are the rules that we have abiding by throughout v2 and also going forward for v3.

Then just make a `EnableParameterizedContent()` that all it does is `return this.EnableParameterizedConstructors().EnforceImmutability()` -- immutability is not enforced at a library level and allows us to it on only some classes/properties, but it is not a breaking change which also allows it to be implemented in v2...

**Comment by Mike-EEE** [comment]
> But this is not something a library such as this should enforce.

Oh?  You have the magic EXS token of lore that dictates what EXS is _supposed_ to be?  Well then, let's make you the owner of this repo! 🤣  Last I checked, this is @wojtpl2's repo and it's his final say one what this library _should_ enforce.

(Also I did read your edit and I did mean the "rules" to mean the protobuf-origin rules that the parameterized content feature follows).

> You're basically saying "the library can do this, but because we think this is bad class design, we prevent you from doing it unless you create your own extensions."

As opposed to a typical project without an extension model which would generally state "the library can do this, but because we think this is bad class design, we prevent you from doing it, period.  Go ahead and submit a PR.  Good luck, and we'll wait."  Let's show a little appreciation for the context in which we are having this discussion, shall we?

> Then just make a EnableParameterizedContent() that all it does is return this.EnableParameterizedConstructors().EnforceImmutability() -- immutability

Yes, just go ahead and do that.  On your fork.  :)  You could even create an `ExtendedXmlSerializer.MutableOnly` nuget and we could see who wins the adoption race. 😂  

I am not sure if the `help wanted` tag is apparent enough, but I myself am not planning on spending time on this task as I personally feel it would be counterproductive -- not only in terms of my time specifically, but also from a philosophical perspective and the expense that it will incur into the library and for those who utilize it.   I feel the amount of time I have already put into the `WritableParameterizedContentExtension` is the extent of which I am wiling to apply my free time and goodwill into this endeavor.

But, of course, I am more than happy (but not really 😁) to facilitate dialogue and PR review for contributions that run counter to my ideals/principles, should one be presented.

**Comment by FaustoNascimento** [comment]
> Oh? You have the magic EXS token of lore that dictates what EXS is supposed to be?

You're twisting my words. I said *a library such as this*, as in a library that aims to cater for multiple different scenarios.

> As opposed to a typical project without an extension model

**without an extension model** -- exactly my point, so that would be a limitation at the project level, similar to what happens with XmlSerializer.

But you said already that classes required for extensions are internal and that you'd rather be the one to create/modify extensions. 

Besides, I loaded the project onto VS and spent the last two hours trying to create the extensions mentioned at the top and got nowhere. So close this issue if you want my only viable options at this stage are to either go with private empty ctors or find another serializer.

**Comment by Mike-EEE** [comment]
> You're twisting my words. I said a library such as this, as in a library that aims to cater for multiple different scenarios.

The point being that you are presuming a great deal here about what the expectations here are.  What makes you say that we are aiming to cater for multiple different scenarios?  The extensions are but one aspect of this project.  For me, being able to serialize interfaces was a good start. 😆

> But you said already that classes required for extensions are internal and that you'd rather be the one to create/modify extensions.

Some are and some aren't.  In any case you are free to unseal them in your local fork or you can request them to be unsealed and I can do it for you.  

For some perspective, I have had my hands into decompiled .NET code for nearly 10 years now.  If something doesn't work how I like, I will copy/paste code wholesale (sometimes a great deal of it) and adjust accordingly.  This was before the days of open source where the entire codebase can be simply cloned to my desktop in one command. :)

I will keep this issue open for the time being.  In your case, I think a private constructor is a nice compromise in light of the effort that has been expended thus far attempting to cater to your wishes.  You could also try braving the world of immutability. :)  I promise you won't regret it and your code will be better for it. 

As such, there _are_ other options to consider here.  There always are in our line of work!

**Comment by Mike-EEE** [comment]
Good news here, @aspektxxx has submitted a PR that enables settable properties via the `EnableParameterizedContentWithPropertyAssignments` call as demonstrated here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue207Tests.cs#L12-L27

This is available from the preview feed found here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Give it a shot and see how it treats you.  I think that takes care of most of the ask around this issue.  If not, please feel free to chime in and we can further consider additions and/or carry forward with it in mind for v3. 👍

**Comment by Mike-EEE** [comment]
This has been deployed to Nuget:
https://www.nuget.org/packages/ExtendedXmlSerializer/

If you run into any additional problems please feel free to open a new issue.

Closing for now.
