### ISSUE TITLE
Upgrade to .NET Core 2.1

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#210]
Wow... 2.0 is already EOL:
https://github.com/dotnet/announcements/issues/86

**Comment by Mike-EEE** [comment]
I am thinking this should bump us up to `2.2.0`.  What do you think, @wojtpl2 ?

**Comment by Mike-EEE** [comment]
I thought about this a bit more and it seems incongruent to have 2.2.0 for EXS and 2.1 for .NET Core.  So, `2.1.10` it is. 😁

However... I just noticed that nuget hasn't updated since 2.1.6!  Is there something wrong with the deployment or did I do something in error again? :(

**Comment by wojtpl2** [comment]
No. This time it is my fault. key from nuget was expired. Tomorrow I'll try
to fix it.

**Comment by wojtpl2** [comment]
I've updated Nuget keys. Can you try move tag v2.1.10
<https://github.com/wojtpl2/ExtendedXmlSerializer/releases/tag/v2.1.10>
?

czw., 4 paź 2018 o 22:02 wojtpl2 <wojtpl2@gmail.com> napisał(a):

> No. This time it is my fault. key from nuget was expired. Tomorrow I'll
> try to fix it.
>

**Comment by wojtpl2** [comment]
I think that library should be created in as low as posible version. Then many user can use it. 
Almost every library is created in the same way. Eg: https://www.nuget.org/packages/Newtonsoft.Json/
Newtonsoft.Json is available for .net Standard 1, 1.3 and 2. All feature with are unavailable in 1 are in `#ifdef`.

**Comment by Mike-EEE** [comment]
Whew!  Git can be a pain sometimes.  There is no "move" tag... you have to delete and then re-add.  But if it already exists on the remote it's a whole other command.  Anyways, it should be deploying now. 🤞

As for .NET Standard, that is intact and this doesn't affect it.  This is for .NET Core applications (`.netcoreapp2.0`), so `ExtendedXmlSeralizer.Tests` and `ExtendedXmlSerializer.Samples`. :)

**Comment by Mike-EEE** [comment]
Bummer... doesn't look like it succeeded. :(  I am afraid you will have to take care of this deployment, @wojtpl2.  Let me know if I can assist further towards this.

**Comment by Mike-EEE** [comment]
Addressed deployed in `v2.1.13`.  Closing for now.
