### ISSUE TITLE
Issue parsing collapsed XML tags

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#215]
Test class:
```
public class TestClass
{
	public string Foo { get; set; }
	public string Baz { get; set; }
}
```

Passing XML:
```
<?xml version="1.0" encoding="utf-16"?>
<TestClass xmlns="clr-namespace:Test;assembly=Test">
  <Foo>Foo</Foo>
  <Baz>Baz</Baz>
</TestClass>
```

Troublesome XML:
```
<?xml version="1.0" encoding="utf-16"?>
<TestClass xmlns="clr-namespace:Test;assembly=Test">
  <Foo/>
  <Baz>Baz</Baz>
</TestClass>
```

Deserializing the first XML works fine. When deserializing the second however, Foo has an unexpected value of "\n  " (it should be an empty string), and Baz is also null.

**Comment by Mike-EEE** [comment]
Ew yeah... tricky one.  I am not very happy with the `XmlReader` as it is fraught with conditions and this will add another one.  It *should* be fixed now on the latest preview.  I am not sure if utf-16 is supported, however.  It was not working on my machine so the XML that is currently passing is utf-8.  Please let me know if this is a problem and I can take a further look into it.

**Comment by bpaczkowski** [comment]
UTF-16 seems to be working for me. As to the issue, it also seems to be fixed, thanks.

**Comment by Mike-EEE** [comment]
Woohoo!  good to hear. 👍 I am not sure what's going on with my utf-16, but if it works for you, then I do not dare to be concerned. 😁

**Comment by Mike-EEE** [comment]
This has been deployed to the public nuget feed.  Please give it a try and let us know of any problems that you find.  Closing this issue for now.
