### ISSUE TITLE
Exception when Deserializing Empty List When Emit(Behavior) is Set

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#216]
Example class:

```
public class Foo
{
	public List<string> Baz { get; } = new List<string>();
}
```

Baz does not have a setter. When trying do deserialize a serialized XML an exception occurs.

Also, somewhat related, but would it be possible to add an option for the serializer to ignore all properties without a setter?

**Comment by Mike-EEE** [comment]
Ahhh this might be a configuration issue then as we do support read-only collection properties.  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/ba89f35c591846c5ad7037593ab91e52123c6a94/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue216Tests.cs#L11-L23

As for ignoring properties, what you describe is our default behavior. :)  Are you encountering a problem with this somewhere?

**Comment by bpaczkowski** [comment]
Here's a failing test:

```
[TestClass]
public class Test
{
	private static readonly IExtendedXmlSerializer _Serializer = new ConfigurationContainer()
		.Emit(EmitBehaviors.Always)
		.Create();

	private static string ToXmlString(object input)
	{
		return _Serializer.Serialize(input);
	}

	private static object FromXmlString(string xmlString)
	{
		using (Stream stream = new MemoryStream(Encoding.UTF8.GetBytes(xmlString)))
		using (XmlReader reader = XmlReader.Create(stream))
			return _Serializer.Deserialize(reader);
	}

	private class Foo
	{
		public List<string> Baz { get; } = new List<string>();
	}

	[TestMethod]
	public void Test1()
	{
		string serialized = ToXmlString(new Foo());

		FromXmlString(serialized);
	}

	[TestMethod]
	public void Test2()
	{
		string serialized = ToXmlString(new Foo());

		Assert.IsFalse(serialized.Contains("Baz xsi:nil=\"true\""));
	}
}
```

Both these tests pass when EmitBehavior config is commented out.

The fact that a list is used here is relevant. A simple string seems to be working fine.

**Comment by Mike-EEE** [comment]
Ahhhh... got it.  It's when it's an *empty* list.  Yes I see it now.  Looking into this.

**Comment by Mike-EEE** [comment]
ARLIGHT... that was a rough one.  But a fix has been applied and it is ready to check out in our preview feed if you are so inclined, @bpaczkowski.  🤓

**Comment by wojtpl2** [comment]
You can try to publish a new version on Nuget. It should work well now.

**Comment by Mike-EEE** [comment]
Woohoo! I will give it a go right now!

**Comment by Mike-EEE** [comment]
Bummer @wojtpl2 it still looks broken:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Still on `2.1.6`. :(

**Comment by Mike-EEE** [comment]
This has (finally 😆) been deployed to the public nuget feed.  Please let us know if you have any additional questions/problems around this and we'll take a look into it.  Closing for now.
