### ISSUE TITLE
Serialize condition.

### ISSUE THREAD

**Issue by cm4ker** [wojtpl2/ExtendedXmlSerializer#217]
Hi guys!

Has the ExtendedXmlSerializer this function?

For example. I have this structures:

```csharp
public class ParentClass
    {
        public ParentClass()
        {
            Childs = new List<ChildClass>();
            Childs.Add(new ChildClass());
            Childs.Add(new ChildClass() {NeedSerialize = true});
        }

        public List<ChildClass> Childs { get; set; }
    }

    public class ChildClass
    {
        public bool NeedSerialize { get; set; }
    }
```

and then I try to serialize the ```ParentClass``` I want the xml result like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ParentClass xmlns="clr-namespace:XmlExtendedSerializerTest;assembly=XmlExtendedSerializerTest">
<Childs Capacity="4">
    <ChildClass NeedSerialize="true" />
</Childs>
</ParentClass>
```
The element with ```NeedSerialize = false``` skiped during serialization.

If this function are present how I can goal this?

Thank you!

**Comment by Mike-EEE** [comment]
You betcha.  Check it out, @cm4ker:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/9c1343d28839c14eb982d4b4b8ed72689afab4dd/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue217Tests.cs#L12-L20

This results in the following output:

```
<?xml version="1.0" encoding="utf-8"?>
<Issue217Tests-ParentClass xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests">
	<Childs>
		<Capacity>4</Capacity>
		<Issue217Tests-ChildClass>
			<NeedSerialize>true</NeedSerialize>
		</Issue217Tests-ChildClass>
	</Childs>
</Issue217Tests-ParentClass>
```

Please let me know if you have any additional questions here and I will do my best to answer them for you. 👍

**Comment by cm4ker** [comment]
Wow... This is realy ExtendedXml :) Great work! Have you guys any complete docs and features? I will close this issue.

**Comment by Mike-EEE** [comment]
Thanks @cm4ker 	:)

You can see list of features here:
https://extendedxmlserializer.readthedocs.io/en/latest/

And we are working on additional documentation here in our issues:
https://github.com/wojtpl2/ExtendedXmlSerializer/issues?q=is%3Aissue+label%3ADocumentation+sort%3Aupdated-desc
