### ISSUE TITLE
how to add same xml code Automatically in xml tags in kotlin?

### ISSUE THREAD

**Issue by faizanarif121** [wojtpl2/ExtendedXmlSerializer#219]
I want to add following xml code in my xml file, TextView tags automatically, how can I do that?

**code that I want to add after opening tag is:**

`com.mycompany.projectname.`

**Tag in which I want to insert above code is:**

```
<TextView
    android:id="@+id/textView16"
    android:layout_width="wrap_content"
/>
```

**My expected output is as follow**

```
<com.mycompany.projectname.TextView
android:id="@+id/textView16"
android:layout_width="wrap_content"
 />
```

**Comment by Mike-EEE** [comment]
Hi @faizanarif121 thanks for writing in.  Are you saying that you already have an XML file and you want to add additional XML to it?  If this is the case, I would use XSLT.  ExtendedXmlSerializer is better suited for object graph serialization/deserialization.  Please let me know if you have further questions around this and/or if I have anything misunderstood here.

**Comment by faizanarif121** [comment]
Thankyou very much @Mike-EEE , Problem has been solved.
