### ISSUE TITLE
Fix NuGet Deployments

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#220]
Any luck with this @wojtpl2, by chance? Getting this its own issue now as it seems to be a stickler. :)  

NuGet is still stuck on `2.1.6`:
https://www.nuget.org/packages/ExtendedXmlSerializer/

**Comment by wojtpl2** [comment]
Ok I'm trying to do it now.

**Comment by wojtpl2** [comment]
I did it 😃 
https://www.nuget.org/packages/ExtendedXmlSerializer/2.1.13

**Comment by Mike-EEE** [comment]
Woohoo!  Now I can close out some issues. 😎
