### ISSUE TITLE
Enable SourceLink for easier debugging

### ISSUE THREAD

**Issue by MagicAndre1981** [wojtpl2/ExtendedXmlSerializer#225]
### Expected  behavior

Press F11 to step into code and debug the code

### Actual behavior

because no PDBs + source info are found, debugger steps over

### Solution: 

[enable SourceLink](https://github.com/dotnet/sourcelink#using-sourcelink) + [pack PDBs inside the NuGet package](https://github.com/aspnet/Universe/issues/131#issuecomment-363269268) to [fetch the source from github](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#source-link-file-specification) during debugging to be able to step into the code.

**Comment by Mike-EEE** [comment]
Boh!  Sorry about that, @wojtpl2 I think I stepped on your toes there since this is technically deployment-based stuff.  Yes, of course.  Please feel free to use whatever you like and to fix any changes I made. :)

**Comment by MagicAndre1981** [comment]
it works fine so far. I can easily step through the code of the lib during debugging 😍👍

**Comment by wojtpl2** [comment]
@Mike-EEE You did a great job and you can do with this repo whatever you want. I trust you ;)

I wrote that Nuget Symbol Server is a new technology but I don't know yet any props and cons yet.
https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by wojtpl2** [comment]
I think we can close this issue right now. 👍

**Comment by wojtpl2** [comment]
@MagicAndre1981 Thanks for help.
