### ISSUE TITLE
More detail in case of a FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by caetanopaulo** [wojtpl2/ExtendedXmlSerializer#228]
Hi!

First of all great job with the lib.
 
Got a question regarding the exception we get when we try to parse with wrong type of argument: 
We are seeing that the library will throw a 'FormatException: Input string was not in a correct format' with no information regarding which xml field is causing this problem. This is an issue with really long XMLs, let's say we are trying to parse an extensive XML with an argument with the wrong type, it would be useful to have more information about what XML element or entity object parameter is responsible for the exception. 

Is there any way to get this information out of the lib? Setting... etc?

Keep up the good work!

**Comment by Mike-EEE** [comment]
Hey thanks for the kind words and for wriitng in, @caetanopaulo.  I believe we have what you are looking for here:

https://github.com/wojtpl2/ExtendedXmlSerializer/issues/214

Sample code is provided there, but the magic is using `ConfigurationContainer().EnableMemberExceptionHandling()`.  Please let me know how that treats you and if you have any other questions/issues that arise from this. 👍

**Comment by caetanopaulo** [comment]
That worked!
Thanks for the quick reply.
:)
