### ISSUE TITLE
Question about not using ConfigurationContainer

### ISSUE THREAD

**Issue by SOHODeveloper** [wojtpl2/ExtendedXmlSerializer#236]
I have just started working on a project that has ExtendedXmlSerializer included. The file version of the .dll is 1.5.0.0 and it has a date of 08/17/2017 (could have been copied with date changing methods).

The serialization code is simply (no references to ConfigurationContainer anywhere in the project)
` 
           ExtendedXmlSerializer serializer = new ExtendedXmlSerializer();
            String message = serializer.Serialize(messageObject);
`
Are we receiving any benefit by using ExtendeXmlSerializer over built in XML Serialization classes.  From reading the doc, it appears that most everything like circular references must be accounted for in the configuration of the ConfigurationContainer.

**Comment by Mike-EEE** [comment]
Hey there, thanks for checking in here.  The version you have is indeed "1.x" (1.5 obviously), which was the version available before the current version, "2.x" (or 2.1 to be more precise).

The primary features of 1.x were carried over to 2.x, via the new extension model that we created.

If you are looking at the built-in, traditional .NET serialization, the primary scenario and use case that you would have to consider (I believe -- @wojtpl2 might want to also add thoughts here) is how and what you are serializing.

For instance, the classic/traditional serializer does not support instances of objects that are defined as interfaces on an object graph (for instance, a property is defined as an interface).  EXS handles this no problem, plus pretty much any other .NET POCO element you would like to serialize/deserialize.

If you want to port your existing 1.x code to 2.x, it should be relatively straight-forward, although to be honest I am a little rusty with it. 👼   I would for sure be able to assist and help you out though if you choose to go that route, just let me know any questions that you have. 👍

**Comment by SOHODeveloper** [comment]
What I am trying to understand, is did the ConfigurationContainer exist in 1.5 and if so, since we are not using it, what 'extras' do we get from ExtendedXmlSerializer.  If it did not exist, there must have been some similar 'thing' to enable/disable serialization features.  We are only doing serialization, no deserialization.  At this point, we do not have the time or inclination to do an upgrade to 2.x.  The current version is working, I am just trying understand why we are using it.
Thanks

**Comment by Mike-EEE** [comment]
Paging @wojtpl2  :)

**Comment by wojtpl2** [comment]
@SOHODeveloper `ConfigurationContainer` didn't exist in 1.5 version. But you don't have to configure anything to have extra features. E.g. ExtendedXmlSerializer can serialize Dictionary, properties which are an interface type. 
You should try to use standard XmlSerializer. If XmlSerializer can serialize and deserialize your model then you do not need ExtendedXmlSerizlizer.

**Comment by wojtpl2** [comment]
@SOHODeveloper Hi I'm going to close this issue right now. If you have more questions or if my answer is not enough for you, please let me know. Please feel free to re-open this issue or create a new one.
