### ISSUE TITLE
Replace ITypeConfiguration<T>.Member with ITypeConfiguration<T>.MemberBy (Extension Method)

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#238]
As per discussion with #234, we should remove the `Member` extension method as it returns an `ITypeConfiguration` rather than a `IMemberConfiguration`, making it rather useless and it's probably why it is not used anywhere in the code.

Nonetheless, it is a public API method and should be handled appropriately.  We will `[Obsolete]` `Member` and point users to `MemberBy` which returns `IMemberConfiguration`.

FWIW, I prefer `MemberBy` as it has less characters as `GetMember` and is more congruent with the rest of the API (that is, we do not use `GetXXX` anywhere else on the API surface in this area).

As always, I am open to further thoughts/suggestions around this.

**Comment by SuricateCan** [comment]
This looks good. You have my support. :)

**Comment by Mike-EEE** [comment]
Great!  Thank you for your input and approval.  I should be able to get to this by EOD today or early tomorrow.  I will update this thread upon deployment.

**Comment by Mike-EEE** [comment]
This has been deployed to `2.1.16`:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Thanks again for your interest and participation, @SuricateCan!

**Comment by SuricateCan** [comment]
NP
