### ISSUE TITLE
Default/Null properties values on deserialization

### ISSUE THREAD

**Issue by gabrielfetz** [wojtpl2/ExtendedXmlSerializer#239]
Hi!
First of all, thank you for this library! It helped me a lot to clean my POCO classes and solved my problem with namespaces!

I have this xml file as an example:
```xml

<Root Id="ID1234567891234567891234567891234567">
  <FirstClass>
    <Value1>1</Value1>
    <Value2>2</Value2>
    <Value3>v02_05_00</Value3>
    <SecondClass>
      <Value4>4</Value4>
      <Value5>19468557</Value5>
    </SecondClass>
  </FirstClass>
</Root>
```

And these POCO classes also:

```csharp
    public class Root
    {
        public string Id { get; set; }

        public FirstClass FirstClass { get; set; }        
    }
```

```csharp
    using System.Collections.Generic;

    public class FirstClass
    {
        public byte Value1 { get; set; }
        public byte Value2 { get; set; }
        public string Value3 { get; set; }

        [XmlElement("SecondClass")]
        public List<SecondClass> SecondClass { get; set; }
    }
```

```csharp
    public class SecondClass
    {
        public byte Value4 { get; set; }
        public string Value5 { get; set; }
    }
```
In this example, the problem happens when I deserialize a xml file and the final object contains a collection property, as seen in the class "FirstClass". The created object have both Value4 and Value5 properties default/null, as show in the following image:

![image](https://user-images.githubusercontent.com/30673814/53444296-86e91c80-39ec-11e9-92fa-39ee9be31277.png)

The problem does not occur when I use the dotnet native serialize library, however, i had to keep the "[XmlElement("SecondClass")]" property decoration on "FirstClass".

Here is my Main method:

```csharp
        static void Main(string[] args)
        {
            var xmlFile = Assembly.GetExecutingAssembly().GetManifestResourceStream("PoCXML.Test.xml");
            var xmlRdr = XmlReader.Create(xmlFile);

            //var xmlSerializer = new XmlSerializer(typeof(Root));
            //var createdObject = xmlSerializer.Deserialize(xmlRdr);
            var xtendedXmlSerializer = new ConfigurationContainer().EnableImplicitTyping(typeof(Root)).Create();
            var createdObject = xtendedXmlSerializer.Deserialize(xmlRdr);
        }
```
Any suggestions?
Thanks in advance!

**Comment by Mike-EEE** [comment]
Hey @gabrielfetz thanks for writing in.  You are indeed running into a known issue for our v2 serializer here and one that I have officially captured in #240.

Essentially we do differ from the classic serializer currently in this regard.  If you want to succsessfully deserialize the above, you will need to provide an explicit property there as shown here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/c75b9768cf9807363c721083bef4a81af9bd90a4/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue239Tests.cs#L14-L37

Please note that the test is configured to use nested classes so the root element is `Issue239Tests-Root`.

This is a bit of an ugly problem but I will think about it some more to see if there's something we can do about it.

I'd hate to resort to an ugly hack, but that might be what we need to do here. :(

**Comment by gabrielfetz** [comment]
Hi Mike!
I changed the structure of my xml file as you suggested and it worked like a charm!
For now, I'll try to adapt it at runtime and you can close this issue if you want.
Thanks for your help and best regards!

**Comment by Mike-EEE** [comment]
Cool!  Glad it can get you unblocked.  I believe there have been a few times where the incoming XML is outside of the control of the user so it left them having to use the classic serializer.  

It's a tough problem and I am still not sure of a good way of tackling it as we still need to be able to serialize an entire subgraph while making it work for the currently deserialized context.

In any case, we have #240 open to keep track going further.  Hopefully, others that run into this issue will be able to see that as well and know of the limitation, too.  

Thanks again for checking in and let us know if any further questions/issues you encounter. 👍
