### ISSUE TITLE
Aliase for type parameters

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#24]
I use my xml file as configuration file for the end user.
It would be great if I could specify aliases for types.
So that the user could do sth like
```
        <AlbedoColor type="Color">
          <R>156</R>
          <G>208</G>
          <B>84</B>
          <A>255</A>
        </AlbedoColor>
```
Instead of
```
        <AlbedoColor type="OpenTK.Graphics.Color4">
          <R>156</R>
          <G>208</G>
          <B>84</B>
          <A>255</A>
        </AlbedoColor>
```

**Comment by Mike-EEE** [comment]
In v2, we are working on more traditional namespaces where you can define the types as you would in a typical xml element.  Here's an example:
```
<SubjectWithPropertyFromExternalAssembly xmlns="clr-namespace:ExtendedXmlSerialization.Test;assembly=ExtendedXmlSerializerTest" xmlns:exs=""https://github.com/wojtpl2/ExtendedXmlSerializer/futures" xmlns:ns1="clr-namespace:System.Xml.Linq;assembly=System.Xml.XDocument" xmlns:ns2="clr-namespace:System.Collections;assembly=System.Private.CoreLib" xmlns:ns3="clr-namespace:System.Collections.Generic;assembly=System.Private.CoreLib" xmlns:sys="https://github.com/wojtpl2/ExtendedXmlSerializer/primitives">
  <List exs:type="ns3:ArrayOfString">
    <sys:string>Hello World!</sys:string>
  </List>
  <Comparer exs:type="ns1:XNodeDocumentOrderComparer" />
</SubjectWithPropertyFromExternalAssembly>
```

Also note how namespaces are all emitted at the root, preserving overall document size.  That was a b**** to figure out. :)

**Comment by wojtpl2** [comment]
In version 2 You'll be able to enable or disable namespaces. But your issue is different. You want use custom  name of classes. This is good idea. I've added this problem to our TODO list.

**Comment by Mike-EEE** [comment]
Ah OK, @michidk I might have misunderstood you.  Are you looking for shorter names or _any_ name/alias for your output?

**Comment by michidk** [comment]
Actually I was talking about just aliases, like "Color"  for "xxx.xxx.xxx.GLColor4".

But more traditional namespaces are also a thing which would be great.

**Comment by Mike-EEE** [comment]
Gotcha.  Yeah we would have to have some way of creating a map of some sort to enable that.  Sort of like a dictionary attached property at the root.  We're looking at adding attached properties for v2, so this would be a good example of one, if we can make it work. 😄

**Comment by michidk** [comment]
Yeah,

Right now nearly every node in my xml file has a type attribute.
It would be great if I just could set the type in the parent node of a list. So that all child nodes (or list elements) are automatically of that type (or even a type that inherits that specific type).

**Comment by Mike-EEE** [comment]
Hey @michidk I was hoping to get to implement a cool type alias extension for v2 for you, but it doesn't look like it will happen (or at least, I will not be the one that will implement it, unfortunately).  What I have done, however, is made it so that all namespaces are consolidated/optimized so that they are emitted at the root element.

So given a hypothetical root object with a list property of 3 `Color4` instances, it would like something like the following:

```
<?xml version="1.0" encoding="utf-8"?>
<RootObject xmlns="clr-namespace:YourAssembly.YourNamespace;assembly=YourAssembly" xmlns:ns1="clr-namespace:OpenTK.Graphics;assembly=OpenTK">
	<Colors>
		 <ns1:Color4>
          <R>156</R>
          <G>208</G>
          <B>84</B>
          <A>255</A>
        </ns1:Color4>
		 <ns1:Color4>
          <R>100</R>
          <G>150</G>
          <B>200</B>
          <A>255</A>
        </ns1:Color4>
		 <ns1:Color4>
          <R>200</R>
          <G>150</G>
          <B>100</B>
          <A>255</A>
        </ns1:Color4>
	</Colors>
</RootObject>
```

Is this acceptable for what you are asking for here?  Any feedback would be greatly appreciated.

**Comment by michidk** [comment]
Hey,
thats nice!
Sadly its still a bit confusing for another person trying to build its own configuration file for my program.

It would be great if I could hide these alias defines from the user (e.g. by defining them in code: new XmlDeserializer(...)).
Also it would be great if I could just set 'Color' as alias for 'ns1:Color4'.

**Comment by Mike-EEE** [comment]
OK @michidk you have touched on another issue altogether, and one I think @wojtpl2 was trying to convey to me but I didn't get.  Are you saying it is confusing because of the additional namespaces?

One thing we could do is remove those namespaces and make them implicit, so the document would look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RootObject>
	<Colors>
	        <Color4>
	          <R>156</R>
	          <G>208</G>
	          <B>84</B>
	          <A>255</A>
	        </Color4>
	        <Color4>
	          <R>100</R>
	          <G>150</G>
	          <B>200</B>
	          <A>255</A>
	        </Color4>
	        <Color4>
	          <R>200</R>
	          <G>150</G>
	          <B>100</B>
	          <A>255</A>
	        </Color4>
	</Colors>
</RootObject>
```

With your code, as you suggest, you would have to do something like:

```
var configuration = new ExtendedXmlConfiguration()
				.WithAssemblies(typeof(Color4).Assembly, typeof(RootObject).Assembly);
```

The problem here however is that we now move (or abstract) valuable data from the XML document into code.  But, I guess that is the power of configuration. :)  The other problem of course is that if your assembly has two `RootObject` classes (in different namespaces), we run into a type resolution problem, so we would have to further the configuration to help resolve the type we are looking to resolve.

We might also be able to add an aliasing component as well, so your document looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<RootObject>
	<exs:aliases xmlns:exs="https://github.com/wojtpl2/ExtendedXmlSerializer/v2" xmlns:ns1="clr-namespace:OpenTK.Graphics;assembly=OpenTK">
		<exs:alias From="ns1:Color4" To="Color" />
	</exs:aliases>
	<Colors>
	        <Color>
	          <R>156</R>
	          <G>208</G>
	          <B>84</B>
	          <A>255</A>
	        </Color>
	        <Color>
	          <R>100</R>
	          <G>150</G>
	          <B>200</B>
	          <A>255</A>
	        </Color>
	        <Color>
	          <R>200</R>
	          <G>150</G>
	          <B>100</B>
	          <A>255</A>
	        </Color>
	</Colors>
</RootObject>
```

The problem we are running into here of course is that we still want to ensure our documents are XML-compliant.  It only takes one namespace collision to invalidate this.  But, for simple (relatively speaking 😄) scenarios this might work.

In any case, I will see if I can fit something into my busy schedule here to make this happen.  No promises however.  This would be a great test for our extensibility.  I also think that you should be able to specify aliases in code (which is actually part of #6).

Let's see what we can make happen here. 👼

**Comment by wojtpl2** [comment]
We can add configuration as you wrote:
`cfg => cfg.WithAssemblies(typeof(Color4).Assembly, typeof(RootObject).Assembly);`

Or:
```
cfg =>{
cfg.ConfigType<Color4>().Alias("Color");
cfg.ConfigType<RootObject>().Alias("RootObject");
};

```
The second option should be easier for users - in my opinion of course. I think that because other functions are configured in this way. 
@Mike-EEE if you would like to I can collect for you list of assemblies. In function ConfigType I can get typeof(T) and add to list. But I don't know if it will be useful for you. Not all type needs config and not all type will be there.

**Comment by Mike-EEE** [comment]
Yeah I was thinking about how it's currently implemented right now.  basically a URL-based namespace (i.e `https://github.com/wojtpl2/ExtendedXmlSerializer/v2`) represents an entire assembly, sort of like how Xaml does it.  Of course as I mentioned this will lead to class collisions if there are two classes with the same name.  

I like the per-class approach, too.  Even better if you can do it in both code and XML (this should be the goal with all configurations, where possible).

We could even optimize the process here with type-specific configuration, whereby:

`cfg.ConfigType<Color4>().Alias("Color");`

... would actually ensure `Color4`'s assembly as an implicit namespace, in addition to setting the alias (so no need to call `WithAssemblies`).

**Comment by michidk** [comment]
`cfg.ConfigType<Color4>().Alias("Color")`
Would be perfect!

Another approach would be to add an attribute to the class like `[XmlAlias("Color")] public class...`.
Would be even more convenient.

**Comment by Mike-EEE** [comment]
Ah, that is actually already taken care of by the use of the `XmlElementAttribute`.  So hopefully at the end of the day you'll be able to (ideally) set your aliases from:

- Code (imperative)
- XML (declarative)
- Metadata (declarative)

I think I got those right. :)

**Comment by wojtpl2** [comment]
Version 1.5.0 supports XmlRootAttribute and XmlElementAttribute. In these attributes you can change name.

**XmlElement attribute**
```C#
	public class TestClassWithXmlElementAttribute
	{
		[XmlElement(ElementName = "Identifier")]
		public int Id { get; set; }
	}
```
Xml will be look like:
```xml
<TestClassWithXmlElementAttribute type=""ExtendedXmlSerialization.Test.TestObject.TestClassWithXmlElementAttribute"">
  <Identifier>123</Identifier>
</TestClassWithXmlElementAttribute>
```

**And XmlRoot attribute:**
```C#
	[XmlRoot(ElementName = "TestClass")]
	public class TestClassWithXmlRootAttribute
	{
		public int Id { get; set; }
	}
```
Xml will be look like:
```xml
<TestClass type=""ExtendedXmlSerialization.Test.TestObject.TestClassWithXmlRootAttribute"">
  <Id>123</Id>
</TestClass>
```


Currently in v2, these xmls will look like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<TestClassWithXmlElementAttribute xmlns="clr-namespace:ExtendedXmlSerialization.Test.TestObject;assembly=ExtendedXmlSerializerTest">
	<Identifier>123</Identifier>
</TestClassWithXmlElementAttribute>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestClass xmlns="clr-namespace:ExtendedXmlSerialization.Test.TestObject;assembly=ExtendedXmlSerializerTest">
	<Id>123</Id>
</TestClass>
```

XmlElementAttribute has counterpart in configuration:
```
cfg => cfg.ConfigureType<TestClassWithXmlElementAttribute>()
					   .Property(p => p.Id).Name("Identifier")
```
XmlRoot attribute doesn't have counterpart in configuration. @Mike-EEE Do you think (like me) that it is the same function. If yes we should add 
`cfg.ConfigType<Color4>().Name("Color");`
instead of 
`cfg.ConfigType<Color4>().Alias("Color");`

**Comment by Mike-EEE** [comment]
> XmlRoot attribute doesn't have counterpart in configuration. @Mike-EEE Do you think (like me) that it is the same function

Definitely.   We have alias providers for both members and types. Technically it's a type alias, but also an element name, so both work.  As long as it is consistent. :)

**Comment by wojtpl2** [comment]
I've added `cfg.ConfigType<Color4>().Name("Color").`

**Comment by Mike-EEE** [comment]
The features described here should now be available and implemented within the v2 branch.  Please feel free to open a new issue if there is something that is overlooked and/or causing a problem.

FWIW, I ended up dropping "alias" from the model and went consistently with "name".

**Comment by Mike-EEE** [comment]
Ah I just realized that we still do not have implicit namespaces as described above.  This has been captured here: https://github.com/wojtpl2/ExtendedXmlSerializer/issues/84

**Comment by Mike-EEE** [comment]
FWIW, the features here can be downloaded from the prerelease feed:
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer

**Comment by Mike-EEE** [comment]
Hey @michidk I finally got your alias and implicit goodness working.  You can check it out the details here:
https://github.com/wojtpl2/ExtendedXmlSerializer/issues/84

It would be great if you could try it out and provide any feedback whenever you get the chance. 😎

**Comment by michidk** [comment]
Hey,
I finally got time to continue working on my project. I can't wait to try out the new v200 features of this project. Is documentation for v2 available? Because new ExtendedXmlSerializer() does expect some arguments.

**Comment by Mike-EEE** [comment]
Yes we have documentation scheduled for the final milestone.  In the meantime the `ConfigurationContainer` should most definitely exist in the `ExtendedXmlSerializer.Configuration` namespace.  Are you using alpha4, @michidk?

**Comment by michidk** [comment]
Aparrently i was using Alpha1. Thanks!

**Comment by michidk** [comment]
I get the following error while installing:
`Executing nuget actions took 8.74 sec
Install-Package : Could not install package 'ExtendedXmlSerializer 2.0.0-alpha4'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package ExtendedXmlSerializer -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:10.2869783
PM> `

**Comment by wojtpl2** [comment]
@Mike-EEE why have we upgraded to 4.6? 

There is documentation to version 2.0.0:
https://github.com/wojtpl2/ExtendedXmlSerializer/tree/v2.0.0
http://extendedxmlserializer.readthedocs.io/en/v2.0.0/

There is our web page:
https://extendedxmlserializer.github.io

We make this page available after publishing v2.0.0

**Comment by Mike-EEE** [comment]
Ahhh booo.  I copied/pasted the VS2017 XML from the restart branch and forgot to update it. :(  I will get to this today.

**Comment by Mike-EEE** [comment]
Nope... sorry I was wrong... I *did* try to set it to 45, but the nuget packages no longer support them:

```
Package System.Collections.NonGeneric 4.3.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package System.Collections.NonGeneric 4.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Package System.Reflection.TypeExtensions 4.3.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package System.Reflection.TypeExtensions 4.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - net462 (.NETFramework,Version=v4.6.2)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.5 (.NETStandard,Version=v1.5)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Package System.Collections.NonGeneric 4.3.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package System.Collections.NonGeneric 4.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Package System.Reflection.TypeExtensions 4.3.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package System.Reflection.TypeExtensions 4.3.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - net462 (.NETFramework,Version=v4.6.2)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.5 (.NETStandard,Version=v1.5)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
```
This changed after VS2017.  Thoughts?

**Comment by wojtpl2** [comment]
It is case for #if #endif. 
For .net 4.5 we can reference assembly. For .net standard we can use nuget.

**Comment by Mike-EEE** [comment]
Ahhhh.  Yes that works.  OK I will see if I can get that going.  I am thinking if we can fix this one we should release an Alpha4.1 haha.  Not sure if that breaks the version rules though. 😛

**Comment by wojtpl2** [comment]
If you fix it, I will publish alpha5 :)

**Comment by Mike-EEE** [comment]
OK... that wasn't too bad.  I committed a fix.  Please verify that it works for you as well, and if so deploy Alpha 5 when you can.  I will update Alpha 5 milestone to be Alpha 6.

**Comment by michidk** [comment]
So, since this EXMLSerializer is now working for me, I tried this feature.
- cfg.ConfigureType<Color4>().Name("Color"); Is awesome. Since Color4 is from an external dependency I can't (and dont want to) modify the source code, so I can set a user friendly name like this. I also don't have to specify the namespace anymore (didn't test that, just assume it works that way). Great work! 
- For my own source code I can use the XMLRoot attribute to do the same. So ConfigureType basically does a similar thing than setting the root object, right? It just doesnt define it for the global namespace.

But when using lots of types from my own source code (some with XMLRoot), I still have to specify their namespaces everytime I use them right? But I can prevent this by doing this:
`
            cfg.ConfigureType<Scene>().Name("Scene");` 
for every type.
Would be great if I can define some default assemblies (Like I don't have to specify the assembly for Integer).

**Comment by Mike-EEE** [comment]
Correct, we do have two ways of specifying type names (aliases) now: via configuration and via old-skool attributes.

If you are not wanting to use namepaces for types, we do have the ability for implicit typing, which allows you to specify types that do not need namespaces (they are derived implicitly from an explicit list. 😆).  Unfortunately, I just realized that this and a few of our extensions were made internal during a task we had for a previous alpha, so it is not available to you just yet.  It will be available in the next alpha, if that is OK with you.  :)

**Comment by michidk** [comment]
Haha, great 😆  🎉

**Comment by michidk** [comment]
I'm now using the project reference instead of nuget. Is it already possible to define those namespaces in the newest commit on the alpha? If so, how do I define them?

**Comment by Mike-EEE** [comment]
You mean the implicit types?  Yes we have examples in the [`ImplicitTypingExtensionTests`](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/Xml/ImplicitTypingExtensionTests.cs) class for now.  Documentation is on the way.  I promise. 😄 👼

**Comment by Mike-EEE** [comment]
I believe every outstanding issue has been addressed in this thread.  If there is something that is missed, please open a new dedicated issue for it and we will look into it for you.
