### ISSUE TITLE
XmlIgnore for Nullable

### ISSUE THREAD

**Issue by drmcclelland** [wojtpl2/ExtendedXmlSerializer#245]
I have generated C# classes using the XmlSchemaClassGenerator, including its support for nullable properties using the approach described here:

https://github.com/mganss/XmlSchemaClassGenerator#nullables

Unfortunately, the combination of an "xxxSpecified" boolean property with XmlIgnore/XmlElement (which works with the XmlSerializer) does not seem to work with the ExtendedXmlSerializer.  Am I doing something incorrectly?

Specifically, when the Id property has not been initialized, I would expect it to not be serialized - but I am seeing it serialized as 

    <Id>0</Id>

Here's the code I have been testing with for both XmlSerializer and ExtendedXmlSerializer:

**Test class to be serialized:**

    [System.SerializableAttribute()]
    public class TestData
    {
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Id", DataType = "int")]
        public int IdValue { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdValueSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                if (this.IdValueSpecified)
                {
                    return this.IdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdValue = value.GetValueOrDefault();
                this.IdValueSpecified = value.HasValue;
            }
        }
    }
    var nullTest = new TestData() { Name= "Null ID" };
    var testID = new TestData() { Name= "Not Null ID", Id = 123 };

**Test serialization code (ExtendedXmlSerializer):**

    var serializer = new ConfigurationContainer().Create();
    Debug.WriteLine(serializer.Serialize(nullTest));
    Debug.WriteLine(serializer.Serialize(testID));

**Test output (ExtendedXmlSerializer):**

    <?xml version="1.0" encoding="utf-8"?><TestData xmlns="clr-namespace:PS.PRM.Producer;assembly=PS.PRM.Producer"><Name>Null ID</Name><Id>0</Id></TestData>
    <?xml version="1.0" encoding="utf-8"?><TestData xmlns="clr-namespace:PS.PRM.Producer;assembly=PS.PRM.Producer"><Name>Not Null ID</Name><Id>123</Id></TestData>

**Test serialization code (XmlSerializer):**

    var serializer = new XmlSerializer(typeof(TestData));

    using (var stringWriter = new StringWriter())
    {
        serializer.Serialize(stringWriter, nullTest);
        Debug.WriteLine(stringWriter.ToString());
    }

    using (var stringWriter = new StringWriter())
    {
        serializer.Serialize(stringWriter, testID);
        Debug.WriteLine(stringWriter.ToString());
    }

**Test output (XmlSerializer):**

    <?xml version="1.0" encoding="utf-16"?>
    <TestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <Name>Null ID</Name>
    </TestData>
    <?xml version="1.0" encoding="utf-16"?>
    <TestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <Name>Not Null ID</Name>
      <Id>123</Id>
    </TestData>

**Comment by Mike-EEE** [comment]
This is a really nice find, @drmcclelland, thank you for finding it.  It would appear that the reason that `IdValue` (aliased as `Id`) is not being emitted is due to a magic convention in the classic serializer.  If you create a corresponding property with the suffix `Specified` to it, the classic serializer will use that to determine whether to serialize the value or not.

More information can be found here:
https://stackoverflow.com/questions/6711906/net-why-must-i-use-specified-property-to-force-serialization-is-there-a-way

FWIW, I had no idea that this existed. 😆

**Comment by Mike-EEE** [comment]
While we do support some features of the classic serializer, we tried to steer clear of those such as these that promote hidden magic, especially when we offer a more discoverable alternative exists.  I have committed an example of how to do this with ExtendedXmlSerializer here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/5311b05041404ec7b59d34eeabc038a6cbcbb6a1/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue245Tests.cs#L14-L20

Please let me know if you have any further questions around this and I'll do my best to answer them for you.

**Comment by drmcclelland** [comment]
Yes, it is [Deep Magic](https://narnia.fandom.com/wiki/The_Deep_Magic)   :smile:

Thanks for such a quick response, as well as the example of how to workaround this!
