### ISSUE TITLE
types with static ctor cannot be deserialized

### ISSUE THREAD

**Issue by aspektxxx** [wojtpl2/ExtendedXmlSerializer#249]
Class with static constructor cannot be deserialized when EnableAllConstructors() is active. 
System.MemberAccessException: 'Type initializer was not callable.' is thrown.

 ```
public static class StaticSample
    {
        public static void SerializeAndDeserialize()
        {
            var srl = new ConfigurationContainer()
                                            .EnableAllConstructors()
                                            .EnableParameterizedContent()
                                            .EnableReferences()
                                            .Create();

            var dt = new DataHolder();

            var data = srl.Serialize(dt);
            var obj = srl.Deserialize<DataHolder>(data);
        }
    }

    public class DataHolder
    {
        public Size Size { get; set; } = new Size(100, 200);
    }
```

**Comment by Mike-EEE** [comment]
Whoa, guess that is kind of obvious. 😁  Thanks for reporting it, @aspektxxx ... I've committed a fix that you can try out from our preview feed here:

https://www.myget.org/F/wojtpl2/api/v3/index.json

Let us know how it treats you and we'll post it to NuGet... but probably in a few days based on how quickly you're finding these. 😆  

Thanks for helping to improve the quality of ExtendedXmlSerializer. 👍

**Comment by aspektxxx** [comment]
@Mike-EEE thank you for quick fix. Its working as expected 👍. You can wait with releasing new verison, I've probably found a new bug. However, I have some troubles extracting the sample to easily reproduce, so it will take some time.

PS: I tried to fix both of reported issues, but unfortunately got lost in the implementation :(. Anyway, thanks for your work, this serializer is really great!

**Comment by Mike-EEE** [comment]
Hehe no worries and thank you for your kind words, @aspektxxx ... if you can fix it, great.  If not, report away and maybe you can learn from my commit.  Assuming I can fix it, that is. 😁
