### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by michidk** [wojtpl2/ExtendedXmlSerializer#25]
Right now if I get an error it could take me hours to figure out its cause.
E.g. messages like "{"Value cannot be null.\r\nParameter name: method"}" or just a plain "System.NullReferenceException" are not very helpfull.

**Comment by Mike-EEE** [comment]
Agreed.  I am not sure there is a lot of exception handling currently.  We also might consider having our own exception type, as this is what JSON.NET does for theirs.  Well, theirs and pretty much every serializer out there. :)

**Comment by Mike-EEE** [comment]
I have to admit everything is pretty happy path for v2, but when are error does occur you should get the full stack trace.  What I would be interested in is seeing if you can reproduce an error for v2 and if it seems better for you or the same.  This is definitely an area where I personally could improve, as I do not (and am not a fan of) covering/cascading code with a bunch of try/catches (as I understand it this is bad practice anyways).

I sort of want to cheat and close this issue, but it is sort of important and I do not think this is the last that we will see of it.  I guess the right approach is to see if you encounter issues in v2 and if there errors are same/worse/better than what you got previously.

**Comment by Mike-EEE** [comment]
Going to close this issue now as there has not been a lot of discussion around this.  I think the error bubbling we have now is a good start for v2.  If you encounter a scenario where the messaging could be better (in v2), please open a new issue and we will take it from there.
