### ISSUE TITLE
Installing ExtendedXmlSerializer into Android part of Xamarin.Forms app adds unneeded nuget packages

### ISSUE THREAD

**Issue by MagicAndre1981** [wojtpl2/ExtendedXmlSerializer#251]
Installing ExtendedXmlSerializer into Android part of Xamarin.Forms app, adds unneeded nuget packages.

I use .net standard 2.0 dll as shared codebase for Xamarin apps (Android, UWP 16299). And System.Xml.XmlSerializer is already part of [.net standard 2.0 and Xamarin.Android](https://docs.microsoft.com/en-US/dotnet/api/system.xml.serialization.xmlserializer?view=netstandard-2.0#applies-to), so why is this [still referenced](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj#L68)?

**Comment by MagicAndre1981** [comment]
[System.ComponentModel](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj#L67) is also already part of [.net standard 2.0](https://apisof.net/catalog/System.ComponentModel)

**Comment by Mike-EEE** [comment]
Hey good points @MagicAndre1981 ... to be sure, we started v2 before .NET Standard 2.0 was a thing. :)  So this is leftover from 1.x and it hasn't been looked at until now.

Do note that we are also supporting .NET Framework 4.5+, so I am not sure of the deployment implications here.  However, I did omit those references if the current build is .NET Standard 2.0.

I am not too familiar with the deployment ramifications, so @wojtpl2 might have to assist here before deploying to NuGet.  However, you can check with our preview feed to see if that is working better for you now: https://www.myget.org/F/wojtpl2/api/v3/index.json

If not, @wojtpl2 will have to take over from here. 😁

**Comment by MagicAndre1981** [comment]
For for full .net framework, they are already buildin for years and need no nugets. They were released to help users to migrate from .net framework to .net core.

ok, the major issue is now System.Reflection.Emit.Lightweight which is supposed to have no dependencies for MonoAndroid, but Nuget thinks it is .net standard 1.0 and install all other things into packages.config that are later not used in csproj  🤔

The issue is that I can't go away from packages.config for Android, because with "PackageReference Include" sometimes the [reference assemblies are picked and not the real implementations from lib](https://github.com/xamarin/xamarin-android/issues/2076) folder and so app crashes at start.

But with the 2.1.20 test build I see an small improvement, the XML thing is gone

**Comment by Mike-EEE** [comment]
WOW... so you get the actual ref assemblies rather than the runtime assemblies?  That sounds like something that should never ever happen. :P  If I understand correctly you are using VS2017 as well so that puts another wrinkle in your scenario.

I did look into `System.Reflection.Emit.Lightweight` and thought I was able to work around it with `System.Memory` instead, but it appears that LightInject is dependent on it. :(

I am not sure how to further assist in this particular issue for you, so I am open to suggestions on how to proceed.

**Comment by MagicAndre1981** [comment]
Last year I was using VS2017 15.7 with PackageReference Include, but the ASP Net Core SignalR package only worked since 15.8 for Xamarin, so I installed the 15.8 preview in a new VM and app worked, later updated from 15.7.x to 15.8 final, but app crashed when compiled with final 15.8 at start due to PackageReference Include bug I linked. So I have to stay at packages.config.

I played now for several hours with it. I need to install the dependencies System.Collections.Immutable, System.Interactive, System.Reflection.Emit.Lightweight on my own into the Android part, now nuget doesn't install the additional packages when I try to add ExtendedXmlSerializer 2.1.20 to Android.

I have no idea why I get the additional packages are installed when I only try to install ExtendedXmlSerializer 🤔 🤷‍♂️

**Comment by Mike-EEE** [comment]
Ahhh sounds like you're running into legacy Nuget issues then in VS2017, if I understand correctly.  I have yet to build an Android app, despite trying 2-3 times.  Each time I attempt to install Visual Studio (for an entire day 😆) and never get past odd warnings and errors when I compile.

So, you're having better luck than I do. 😁

That said, am I understanding that you have fixed this issue when directly adding those dependencies?  I am not sure why that is and it sounds like a Nuget limitation/bug.

**Comment by MagicAndre1981** [comment]
> That said, am I understanding that you have fixed this issue when directly adding those dependencies? 

this is correct. Before install ExtendedXmlSerializer , install System.Collections.Immutable, System.Interactive and System.Reflection.Emit.Lightweight and the issue with the many useless added packages is gone.

Maybe add this information to the readme

**Comment by MagicAndre1981** [comment]
btw, can you release the previews on nuget directly with beta suffix to avoid compile issue? I always get package downgrade from .20 to .19 and can't compile anything. And when .20 goes live, I need to delete the already cached one, otherwise I would not get the final bits. using the beta fixes this conflict

**Comment by Mike-EEE** [comment]
> btw, can you release the previews on nuget directly with beta suffix to avoid compile issue

Ahhh @MagicAndre1981 that's a good question.  We are actually using this scheme currently as preview feed users were getting errors/wrong packages on the other direction: e.g. on .20 preview feed they would get errors/inaccurate versioning because they had already installed .20 on the public feed.

Deployment is actually not my domain as I do not own the repo, and the automation is outside of my control.  This is something for @wojtpl2 to consider and/or assist. 😁  Perhaps take advantage of the new GitHub feeds?

> Maybe add this information to the readme

TBH I am not sure how valuable that will be, as I am not sure what we are doing that makes this happen, and from my understanding, this appears to be a Nuget issue with VS2017 packages.config on Xamarin projects.  I would rather fix the issue on our end if possible but can also be talked into putting a quick link to this issue for further information if that's what it takes, as well.

**Comment by MagicAndre1981** [comment]
I also tried it in VS2019 Update 2 Preview 3 and same happens. So this is a NuGet issue with the old packages which were created before .net standard 2.0 was out.

I checked and saw that there are pre Release versions 4.6.0-preview6.19303.8 which includes monodroid and .net standard 2.0 definitions and doesn't install garbage.

The name indicates that Microsoft will release them as stable when .net core 3.0 gets stable. So release the new package with the fix you already made and after .net core 3.0 GA, update the nuget package dependencies to the updated versions of System.Collections.Immutable, System.Interactive and System.Reflection.Emit.Lightweight and my issue will be fixed.


> > btw, can you release the previews on nuget directly with beta suffix to avoid compile issue
> 
> Ahhh @MagicAndre1981 that's a good question. We are actually using this scheme currently as preview feed users were getting errors/wrong packages on the other direction: e.g. on .20 preview feed they would get errors/inaccurate versioning because they had already installed .20 on the public feed.

no, if you release a .20.beta1/2/3 , users can easily install .20 final without issues. Your .20 is detected as stable release, so if real stable is out on nuget.org, I would not get the final bits without deleting cached files from C:\Users\USERNAME\.nuget\packages\extendedxmlserializer\ folder . I already had this in past for different package.

after several tries (deleting obj/bin folders) I was able to compile the app again.

**Comment by Mike-EEE** [comment]
> So release the new package with the fix you already made and after .net core 3.0 GA, update the nuget package dependencies to the updated versions of System.Collections.Immutable, System.Interactive and System.Reflection.Emit.Lightweight and my issue will be fixed.

Ok cool!  Sounds like this problem will [eventually take care of itself](https://youtu.be/zqjQDP9KX6E). 😆

> no, if you release a .20.beta1/2/3 , users can easily install .20 final without issues

I wasn't clear enough in my description of my decision/process there, apologies.  I was attempting to fix a problem without the use of beta/preview monikers, as deployment is configured by repo owners and I am but a contributor for this repo.  So, making best with the resources/powers available to me, if that makes sense.  If we want to use a beta/preview moniker (which is indeed the preferred way to go IMO), @wojtpl2 will have to get involved to assist in doing so.

**Comment by MagicAndre1981** [comment]
ok. @wojtpl2 can you please release the .20 with the implemented dependency fix as stable to nuget?

**Comment by Mike-EEE** [comment]
Ah, apologies for the confusion, @MagicAndre1981 ...  @wojtpl2 would be needed for a preview/beta moniker.  I can take care of regular/public deployments.  I was going to do .20 over the weekend, but Real Life. 😆  I will take care of this now.

**Comment by Mike-EEE** [comment]
OK @MagicAndre1981 2.1.20 is now available for you:
https://www.nuget.org/packages/ExtendedXmlSerializer/

**Comment by MagicAndre1981** [comment]
thanks, now I can disable your preview feed in nuget.

I'll leave it open until .net 3.0 is RTM/RTW/GA to see how dependencies are organized in final bits.

**Comment by Mike-EEE** [comment]
Sounds good to me, @MagicAndre1981.  Pretty much what I was thinking. 😊

**Comment by MagicAndre1981** [comment]
ok, for normal .net framework 4.8 the unneeded `System.ComponentModel` and `System.Xml.XmlSerializer` are also added 

When you look at `packages\System.ComponentModel.4.3.0\lib\net45` you see it is [empty placeholder](https://github.com/aspnet/AspNetCore/issues/744#issuecomment-123411563) `_._` 

Your [fix causing it](https://github.com/wojtpl2/ExtendedXmlSerializer/commit/cfb6e02fc213208ce9b29bf5cb5468807863b085#diff-802233c775e8a749803978227a02cdb6R69). Also check for normal .net 4.6/4.7 or in my case 4.8

**Comment by MagicAndre1981** [comment]
I think you can simply remove both dependencies. They are part of .net standard 2.0 and full .net framework.

**Comment by Mike-EEE** [comment]
Weird, @MagicAndre1981!  I remember encountering build errors by not having those references present, but they appear to be working now.  Might have been due to wonky project system state issues, which have been pretty prevalent since its release.

I've made a commit with those removed.  Please continue letting me know of anything further that you find. 👍

**Comment by MagicAndre1981** [comment]
[.net core 3.0 is now out](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/). Update the dependencies to latest versions and provide a test build so see how it looks now.

**Comment by Mike-EEE** [comment]
Ok cool!  I have been swamped with Real Life™ lately... Will try to see if I can get something going tomorrow, and if not, on Wednesday for sure.

**Comment by Mike-EEE** [comment]
Alright @MagicAndre1981 check out our preview feed now:
https://www.myget.org/F/wojtpl2/api/v3/index.json

See if that helps this issue any.  Not sure if the build on the server needs to be updated to 3.0 or anything.  If it does, that complicates this as I do not have access to it.

The other gotcha here is that I am in the middle of a feature with #264 and cannot release to public nugets until I get that to a place that I am happy with ... yeah, I am breaking some serious CD/CI rules with that. :P  

In any case you should be able to get the build from the preview to see where this stands now.

**Comment by MagicAndre1981** [comment]
I don't see an update in myget feed. Have you forgotten to increase version number from .22 to .23?

**Comment by Mike-EEE** [comment]
hah... maybe. 😁😇  I have posted a new commit that does so.  You should see it available in a few minutes or so.

**Comment by MagicAndre1981** [comment]
works fine  🥳   💪

I no longer get the old .net core 1.x packages offered. Only the real required packages in packages.config:

```
<package id="ExtendedXmlSerializer" version="2.1.23" targetFramework="monoandroid81" />
<package id="System.Collections.Immutable" version="1.6.0" targetFramework="monoandroid81" />
<package id="System.Interactive" version="3.2.0" targetFramework="monoandroid81" />
<package id="System.Reflection.Emit.Lightweight" version="4.6.0" targetFramework="monoandroid81" />
```

But only update [System.Interactive to 4.0](https://www.nuget.org/packages/System.Interactive/4.0.0) which was released today and has .net standard 2.0 dependency metadata

**Comment by Mike-EEE** [comment]
Woohoo!  That was a better result than I was expecting. 😆  I've gone ahead and updated `System.Interactive` as well.

The kicker here now is that I still need to finish #264 before I can publish this to the public feed.  The kicker's kicker is that I am leaving on vacation next week for a couple weeks and not sure if I will be able to get it in a state where it can be "done" but we'll see...

**Comment by MagicAndre1981** [comment]
you can make a new brunch which only includes the nuget updates and ignores the other changes and release those bits until the other thing is ready.

**Comment by Mike-EEE** [comment]
Yeah I thought of that... problem is my Git isn't too good and we deploy from `master`.  So it would mean creating a new branch called `Issue-264` or some such and moving the commits made around that (that are already in `master`) over to it.  Sounds like a lot of work. 😉

**Comment by MagicAndre1981** [comment]
ok, I did this and only [reverted this 1 commit](https://github.com/MagicAndre1981/ExtendedXmlSerializer/commit/0d4e90b767738c693655196a500d2f916e5d6c23) from master and moved this commit [into its own brunch](https://github.com/MagicAndre1981/ExtendedXmlSerializer/tree/Issue264) and merged the nuget changes from master.

Took me about 10 minutes with TortoiseGit

**Comment by Mike-EEE** [comment]
Cool... thanks for the inspiration, @MagicAndre1981. 😁  I use GitExtensions myself, and I looked into the revert.  What I did was:

- Revert 0d4e90b767738c693655196a500d2f916e5d6c23 as commit df1eebebf9e27081efdd625037b19af2739724c9
- Tag as `2.1.23` and push (This should create a NuGet)
- Bump to `2.1.24` 
- Revert df1eebebf9e27081efdd625037b19af2739724c9 (essentially re-committing 0d4e90b767738c693655196a500d2f916e5d6c23)

I *think* everything should be in order now? 😆  You should see a NuGet package soon:
https://www.nuget.org/packages/ExtendedXmlSerializer/

**Comment by MagicAndre1981** [comment]
thanks, I'll check this on monday

**Comment by MagicAndre1981** [comment]
> I _think_ everything should be in order now?  You should see a NuGet package soon:
> https://www.nuget.org/packages/ExtendedXmlSerializer/

works fine. Now only the real required packages are added and no longer all the .net core 1.x packages. I'll close the issue now.

**Comment by Mike-EEE** [comment]
Woohoo!  Good to hear.  Thank you for your contribution to improve the quality and developer experience of this project, @MagicAndre1981!
