### ISSUE TITLE
Testing ExtendedXmlSerializer configurations

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#254]
I noticed you used a `ForTesting()` extension method. 

In `ExtendedXmlSerializer.Tests.csproj` it shows `<PackageId>ExtendedXmlSerializer.Tests</PackageId>` but I can't find it under this name in NuGet.

Can we use this or is there another way we can test ExtendedXmlSerializer configurations?

**Comment by Mike-EEE** [comment]
Correct, that is a utility extension method in our testing project to ensure objects are being serialized then deserialized as expected.

You would probably be best off copying [this file](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/Support/SerializationSupport.cs) and [this file](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/Support/Extensions.cs) and incorporating them into your project.

**Comment by Mike-EEE** [comment]
Closing this issue as it appears the question has been answered.  Please feel free to add a comment and/or re-open if you have any further questions/comments.
