### ISSUE TITLE
How can I configure the serializer for a collection property with backing field?

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#255]
When I have a class which contains a collection property with a backing field, how can I serialize that?

For example: when I have this class...

```cs
public class BackingFieldExample
{
    private readonly IList<string> _values = new List<string>();

    public IReadOnlyCollection<string> Values => this._values.ToList().AsReadOnly();

    public void AddValue(string value) => this._values.Add(value);
}
```

... and this test with a serializer ...

```cs
[Fact]
public void SerializeBackingField()
{
    var e = new BackingFieldExample();

    e.AddValue("first value");
    e.AddValue("second value");

    var serializer = new ConfigurationContainer()
        .ConfigureType<BackingFieldExample>()
        .Create();

    serializer.Cycle(e).Should().BeEquivalentTo(e);
}
```

... then the `Values` collection of the deserialized object is empty.

**Comment by Mike-EEE** [comment]
While we haven't really made it a focus to carry over the classic functionality of the `XmlSerializer`, this is one scenario where we did.  You can make use of the `XmlElementAttribute` as demonstrated here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/2a820ece4eccc4810240229315141d7607291106/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue255Tests.cs#L15-L40

**Comment by Mike-EEE** [comment]
As it appears that this question was answered, I am going to close it for now.  Please feel free to add another comment and/or re-open if you have any additional comments/question around this issue.
