### ISSUE TITLE
Updated from 1.5.0 to 2.1.21 Deserializer doesn't work

### ISSUE THREAD

**Issue by RodrigoRodriguesX10** [wojtpl2/ExtendedXmlSerializer#263]
I'm getting: An attempt was made to load a type with the fully qualified name of 'FooBar', but no type could be located with that name. When I try to deserialize an object.

I have a legacy project with .NET Framework 4.5 and I want to migrate to .NET Core 2.1. So, all funcionalities will be migrated.

Legacy project has ExtendedXmlSerializer v1.5.0, I want that new project has the latest version (v2.1.21). But Deserializer does not have the same behavior.

Legacy test Class:
```
    [TestClass]
    public class XmlTest
    {
        [TestMethod]
        public void ShouldDeserializeXMLtoObject()
        {
            var xmlString = "<?xml version=\"1.0\" encoding=\"utf-8\"?><FooBar><Foo>Test 1</Foo><Bar>Test 2</Bar></FooBar>";
            var foobar = new FooBar { Foo = "Test 1", Bar = "Test 2" };
            var serializer = new ExtendedXmlSerialization.ExtendedXmlSerializer();
            var result = serializer.Deserialize<FooBar>(xmlString);
            Assert.AreEqual(foobar.Foo, result.Foo, "Deserialization failed with prop Foo");
            Assert.AreEqual(foobar.Bar, result.Bar, "Deserialization failed with prop Bar");
        }
    }
    public class FooBar
    {
        public string Foo { get; set; }
        public string Bar { get; set; }
    }
```

Which works perfectly. But, on the new project:

```
    [TestFixture]
    public class XmlTest
    {
        [Test]
        public void ShouldDeserializeXMLtoObject()
        {
            var xmlstring = "<?xml version=\"1.0\" encoding=\"utf-8\"?><FooBar><Foo>Test 1</Foo><Bar>Test 2</Bar></FooBar>";
            var foobar = new FooBar { Foo = "Test 1", Bar = "Test 2" };
            var serializer = new ConfigurationContainer().Create();
            var result = serializer.Deserialize<FooBar>(xmlstring);
            Assert.AreEqual(foobar.Foo, result.Foo, "Deserialization failed with prop Foo");
            Assert.AreEqual(foobar.Bar, result.Bar, "Deserialization failed with prop Bar");
        }
    }
    public class FooBar
    {
        public string Foo { get; set; }
        public string Bar { get; set; }
    }
```

Which is throwing the exception: **An attempt was made to load a type with the fully qualified name of 'FooBar', but no type could be located with that name**

I already tried to change the serializer creator line to 
**var serializer = new ConfigurationContainer().ConfigureType<FooBar>().Create();**
but I'm getting the same exception. 
I searched for the problem on the repository issues page, but I couldn't find a clue.

What can I do to make this works again?

**Comment by Mike-EEE** [comment]
Upon further "reflection" (pun intended 😆), I believe the problem you are encountering is from [auto-generated classes as described here](https://stackoverflow.com/questions/16349560/reflection-and-autogenerated-types).

I have added a new check within our implicit type extension to filter these out, so you _should_ be able to use `EnableImplicitTypingFromAll` now without error (or at least _that_ error).

**Comment by Mike-EEE** [comment]
This has been deployed to the public nuget feed.  If you have any further questions/issues with the feature please let us know either here in the comments or in a new issue and we'll take a look at it for you. Closing this issue for now.
