### ISSUE TITLE
NuGet package with A strongly-named assembly (Signed packages)

### ISSUE THREAD

**Issue by snovak7** [wojtpl2/ExtendedXmlSerializer#3]
> Result Message:	
> Test method XXX.Tests.Config.ConfigTests.TestSolutionSerialization threw exception: 
> System.IO.FileLoadException: Could not load file or assembly 'ExtendedXmlSerializer, Version=1.2.0.0, > Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by wojtpl2** [comment]
I've published version 1.3.0, that is signed. Please check if this solves your problem.

**Comment by wojtpl2** [comment]
Issue is fixed.
