### ISSUE TITLE
Consideration: Moving v1 to Legacy Namespace

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#30]
I should have asked this a long time ago. :P

I have encountered a lot of friction in the v2 design with having to account for v1/legacy functionality.  In fact a lot of my time has been spent having to account for both it and v2 vision.  This has proved quite challenging and time-intensive.

So the thought occurs to me... how open would you be to simply moving all current components to a `Legacy` folder (much like what I [did in the performance testing project](https://github.com/Mike-EEE/ExtendedXmlSerializer/tree/feature/Deserializer/test/ExtendedXmlSerializer.Performance.Tests/Legacy)) and deprecate the public components?  Some thoughts around this:

1. This gives the project insurance in case they really want v1 functionality while still being able to try v2 (and not have to lock to a particular version).
1. Simplify project.  Right now there is a lot of code in the project (maybe too much!) and a lot of it is due to having to consider both v1 and v2 scenarios.
1. This is a breaking change, though. :(  Users will upgrade to v2, and their code will not compile if they have made use of `ISerializationToolsFactory` at all.  They will have to update their references from `ExtendedXmlSerialization.ExtendedXmlSerializer` to `ExtendedXmlSerialization.Legacy.ExtendedXmlSerializer` (or ``ExtendedXmlSerialization.Legacy.LegacyExtendedXmlSerializer` if we wish).

The last point is why I haven't brought it up until now.  As a general, wise rule, breaking changes should be avoided if at all possible, but I am thinking since this project only has 18 stars at the moment, maybe it's something to do before it gets 18,000? :)

Definitely open to thoughts on this!

**Comment by wojtpl2** [comment]
I've removed ISerializationToolsFactory. I think that v2 could have breaking changes. 
Migration from version 1 to 2 won't be difficult. You can look up how I changed ExtendedXmlSerializer.Samples project.

**Comment by Mike-EEE** [comment]
GOOD. I agree.  Not much to change, but you never know with projects and the requirement to move forward/preserve existing functionality.  I just wish I asked sooner! :)

**Comment by Mike-EEE** [comment]
Addressed with #38
