### ISSUE TITLE
Cleanup Configuration Namespace

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#32]
- Delete Configuration
- Rename `NewConfiguration` -> `Configuration`

**Comment by wojtpl2** [comment]
Thanks!

**Comment by wojtpl2** [comment]
I've done rename NewConfiguration -> Configuration.

**Comment by Mike-EEE** [comment]
Great, thank you!

**Comment by Mike-EEE** [comment]
Ah, don't forget Testing/NewConfiguration!

**Comment by wojtpl2** [comment]
Ok thank you. I've done it too.

**Comment by Mike-EEE** [comment]
Great thank you!  Looks good 👍
