### ISSUE TITLE
Consider Rename

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#34]
So, this is a personal pet peeve, and I would totally understand not doing this, but I hate the word `Config`  and like seeing it typed out as `Configuration` (like `App` instead of `Application` seems lazy).

I understand `ExtendedXmlSerializerConfiguration` seems a little lengthy though... so maybe `ExtendedXmlConfiguration` ?

No worries if you don't like it, but thought I would ask!

**Comment by Mike-EEE** [comment]
Also would mean `IExtendedXmlSerializerConfigType` -> `IExtendedXmlTypeConfiguration` perhaps, as well.

**Comment by wojtpl2** [comment]
It is good proposition. 

My english is not perfect. To be honest I'm still learning. I will be glad if you give me know when I make mistakes.

**Comment by Mike-EEE** [comment]
Hey I've been at it for 40 years and I am still learning.  It's a rough, strange language.  And your English is fine!  At least enough that I understand.  :)  Do you have ReSharper?  They have a FANTASTIC plugin called [ReSpeller](https://resharper-plugins.jetbrains.com/packages/EtherealCode.ReSpeller/) which underlines misspellings for you.  But, "config" is not considered one, so it wouldn't help in this case (again, pet peeve!).

**Comment by wojtpl2** [comment]
I'll do it. 
Yes I know resharper ;) But I've never used ReSpeller.

**Comment by Mike-EEE** [comment]
Cool.  Do you use ReSharper?  If so, you can use project-based code-formatting settings and we should totally use that.  That way when you get ready to checkin, you format it like the project's settings are configured and it is formatted as desired. This is what I do now before I checkin, but I am just guessing what the formatting settings are. :)

**Comment by wojtpl2** [comment]
I've done this task. You can check.
I use default settings in ReSharper and you ?

**Comment by Mike-EEE** [comment]
Great!  I am not sure what default settings are, I've used it for over a decade now. :)  If you like how the code is formatted we can use that.  I do like a few things, we can discuss.  I will open a new issue.
