### ISSUE TITLE
Improve Performance of version 2

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#35]
The new v2 infrastructure is in place but it is nearly twice as slow as v1.  The goal/expectation/requirement is to preserve the magic speed that made v1 so cool.  Should be around the same or maybe 10us differential.

**Comment by wojtpl2** [comment]
For several days people stopped to retrieve packages from Nuget. And maybe we have too muche issues. I've changed name of this issue.

**Comment by Mike-EEE** [comment]
Oh, then I had better solve it quickly then!  Haha.  No I understand.  It's applied with a v2 label but people see all the items then the details (if at all).

I did some profiling and it looks like a lot of the time is spent dealing with v1 compatibility.  So hopefully we can get better performance after #30 is complete.

**Comment by Mike-EEE** [comment]
OK I have looked into this.  I have managed to squeeze the performance down to ~95us serialization and ~150us deserialization on my machine.  Unfortunately it doesn't look like the serialization will get much better.  dotTrace doesn't reveal any hot paths, and it seems that all the time is spent now in different method calls and not in any particular method.

For each new "context" we now allocate a new context object.  This was not in the original version and adds some overhead.  I tried to design it in such a way where we do not allocate, but there is a lot of value in doing this, and makes things much more extendible and nice to work with.

I will say that my performance tweaking -- even though I have spent an inordinate amount of time in it -- is not very good.  It's enough to get by, but perhaps there is something I might be overlooking.

So it seems as if the ~20us hit is due to the current design for serialization.  Deserialization might get some more improvements as I have not studied it much.

Anyways, I wanted to get your thoughts on this.  What should be the goal for v2?  Should it be around v1 speed?  Is there a certain speed you have in mind to match?

**Comment by wojtpl2** [comment]
~95us not too bad.
I created this project for my other projects. I wanted to serialize some (big) data to xml files. Performance for these projects isn't the most important. Generally speed is important, especially if we think about integration with MVC/WebApi. Of course we can improve performance later or in version 3.0 ;) 

In the worst case we could redesign your code. Users don't use your code directly. They use only configuration and interface of serializer.

**Comment by Mike-EEE** [comment]
Ahhh that's a good point and something that I have been thinking about... I wanted to make this so that users could "design their own serializer" so that if they are caught in a situation like what I was in (DataContractSerializer vs. XmlSerializer), they could simply rebuild their own using what is there as a blueprint.

Of course, this opens doors to other problems, but it would make it truly an "ExtendedXmlSerializer" :)   Open to discussion on this, of course.  It would definitely be "extend at your own risk" sort of thing.

As for performance, I found an issue: memory collection.  Right now I have things designed using singletons and weak reference dictionaries.  If I switch to use strong reference dictionaries, I get 83us serializer and 135us deserializer, which to me is perfectly acceptable for where we are with this at the moment.

However, using this, with the serializer starts out at 83us and then creeps up to 87us when it is complete, so it seems as if there is a memory leak somewhere.  I will have to fish it out and then send a commit over for this issue.

**Comment by Mike-EEE** [comment]
Ohp. :)  I couldn't let this one go.  I just published this branch for you to take a look into:
https://github.com/Mike-EEE/ExtendedXmlSerializer/tree/feature/WIP/refactor

Good news bad news... bad news is that I went through another model refactor.  Good news: it's blazing fast now.  It's a bit of a mess and it's only the serializer, but check this out:

```
BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4820K CPU 3.70GHz, ProcessorCount=8
Frequency=3613278 Hz, Resolution=276.7570 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0

Gen 0=4.4759  Allocated=37.62 kB

                          Method |       Mean |    StdDev |
-------------------------------- |----------- |---------- |
 SerializationClassWithPrimitive | 50.7612 us | 0.1046 us |
```

😮 😮 😮 

That means it's not only faster than v1 (by 33%!) it's faster than the native .NET XmlSerializer by 17%! 😮 😮 😮 

Anyways, I still have to do the deserializer and thought I would share, just in case there is something ridiculous that I am overlooking.  It should take me a little time to do so.  One thing I have noticed is that we use `XmlWriter` for writing but `XElement` for reading.  This means that the document is read twice: once to load the document, and then once to iterate through its elements.  Ideally we would like to have it go through once.  That should help with its performance.  I will look into this to see if we can improve that.

Let me know your thoughts around this when you get the chance.  I will re-open this issue for now.

**Comment by wojtpl2** [comment]
It looks amazing! I'll look.

**Comment by Mike-EEE** [comment]
Ok I just got deserialization working, too.  It's very rough (and very messy!  I've got it all in one file currently hehe), but here it is:
https://github.com/Mike-EEE/ExtendedXmlSerializer/tree/WIP/refactor

```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 50.8097 us | 0.8161 us | 4.6712 |  37.58 kB |
 DeserializationClassWithPrimitive | 70.2643 us | 0.3758 us | 3.7598 |  32.09 kB |
```

Here's native `XmlSerializer` (for reference):

```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 61.4240 us | 0.1171 us | 8.2031 |  56.85 kB |
 DeserializationClassWithPrimitive | 62.4411 us | 0.2501 us | 1.7415 |  22.91 kB |
```

And v1 (for reference):

```
                            Method |        Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |------------ |---------- |------- |---------- |
   SerializationClassWithPrimitive |  73.6575 us | 0.1087 us | 7.1126 |  51.16 kB |
 DeserializationClassWithPrimitive | 101.1237 us | 0.2058 us | 5.3060 |  55.97 kB |
```

Some thoughts:
- Not sure if XmlReader is worth it.  It is kind of tricky to work with and seems very error prone.  Obviously faster, however.  I guess it is worth a try to see how it goes.  We will definitely need to beef up exception messages/handling (#25).  Which is not my specialty, haha.
- I haven't profiled the deserializer yet, so I don't know if there is any improvements I can make, but it would be nice to get it to native performance.  In any case, 10us difference and 30% improvement over v1 is a nice start!

**Comment by wojtpl2** [comment]
At this moment it is enough. 

I don't remember very well, but I think that I used XElement because I needed to modify xml document in migration. And custom deserialization is simpler too. I didn't have other idea. If you have any idea pleas let mi know.

**Comment by Mike-EEE** [comment]
Ah!  That is a good point.  I would have figured that out once I got around to migration/custom XML. :) 👼 Since these are behind interfaces, we can use an `XElement`-based reader if the `ExtendedXmlConfiguration` enables either of these features.  I will look into this. 😎  

In the meantime I will aim to cleanup what I have here and get this submitted as a PR you can actually review.  I haven't mentioned this yet, but this greatly simplifies the design and code used.  It basically combines both the `ElementModel` and `Conversion` namespaces.  It's also basically what I have been trying to develop in previous versions, but this time it _actually works_... haha.

**Comment by Mike-EEE** [comment]
Alright, looks like I got the deserializer to be just a _smidge_ faster than the native.  That's good enough for me for now.

```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 49.5792 us | 0.1340 us | 4.7363 |  37.58 kB |
 DeserializationClassWithPrimitive | 61.6788 us | 0.0977 us | 3.1901 |  31.68 kB |

```

**Comment by Mike-EEE** [comment]
Oh man... I just realized that the deserialization tests were not equal.  The native `XmlSerializer` was using a `TextReader` while the `ExtendedXmlSerializer` uses a stream.  Additionally, the stream was created by a byte array that was being created each and every time with v2.

So what I did is [updated the tests to both cache a byte array and then use a stream](https://github.com/Mike-EEE/ExtendedXmlSerializer/commit/c523af244225a6b299406da9accff8f5427f1ede#diff-e171ba6ada2d3906030ee1d41be30cc1).

Here are the new results:

V2:
```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 49.6041 us | 0.0857 us | 4.4759 |  37.58 kB |
 DeserializationClassWithPrimitive | 57.1433 us | 0.0760 us | 2.7832 |  27.66 kB |
 ```

Native `XmlSerializer`:
```
                            Method |       Mean |    StdDev |  Gen 0 | Allocated |
---------------------------------- |----------- |---------- |------- |---------- |
   SerializationClassWithPrimitive | 59.5148 us | 0.0574 us | 8.3333 |  56.85 kB |
 DeserializationClassWithPrimitive | 66.3188 us | 0.0777 us | 2.7832 |  27.32 kB |
```

So essentially it is now around 15% (maybe more) faster than the native serializer for **both** serialization and deserialization. 👍

**Comment by wojtpl2** [comment]
It is amazing result.
Today I would like to push my changes.

**Comment by Mike-EEE** [comment]
Ah ok!  I do have some changes of my own. Should I send a PR over of my current work to be sure?  I can also merge if needed.

**Comment by wojtpl2** [comment]
If you can send you changes.

**Comment by Mike-EEE** [comment]
Alright, there you go. Let me know if you have any questions/problems.

**Comment by Mike-EEE** [comment]
Wicked fast now.  We're between 15-20% faster than `XmlSerializer`.

**Comment by wojtpl2** [comment]
You can see currently performance results: 
https://www.codeproject.com/Articles/1121574/Extended-XML-Serializer-for-NET?msg=5365408#xx5365408xx

**Comment by Mike-EEE** [comment]
Hah!  Very cool.  Don't forget that currently comes with an asterix, as we are caching `XmlConvert` results which leads to higher memory usage while the serializer is in memory.  We need to ensure that we enable the user to flush out the contents on demand.  I'll create an issue for this.
