### ISSUE TITLE
Create .sln.DotSettings File (ReSharper)

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#36]
These are personal preferences (and open to discussion, of course):

- Use `var` instead of type
- Prefer implicit modifier keywords (e.g. I prefer `readonly int a` vs. `private readonly int`)
- Tabs
- Remove `this.`

Basically the less code the better. :)

**Comment by wojtpl2** [comment]
- Use var instead of type - for me it was hint, but ok.
- Prefer implicit modifier keywords (e.g. I prefer readonly int a vs. private readonly int) - I always use private but this point is good for me too. What settings in resharper it is?
- Tabs - ok
- Remove this - it must be.

I agree with you - the less code the better ;)

I add my requirements:
- private member should start with _
- Adjust modifiers declaration order - https://www.jetbrains.com/help/resharper/2016.3/ArrangeModifiersOrder.html. 
public new static KnownConverters Default { get; }
instead of
public static new KnownConverters Default { get; }

and it's all for me right now. Do you can create this file ?

**Comment by Mike-EEE** [comment]
Great... yes, I do not have a preference on sort order and have been formatting with default profile on that, I believe.  We can edit those as we go along as well.   I will get a file checked in. 👍

**Comment by Mike-EEE** [comment]
OK...I have to reformat the code for this.  This will change everything to tabs and reorganize modifiers.  Is that OK?

**Comment by wojtpl2** [comment]
Great... Yes. You can push it.

**Comment by wojtpl2** [comment]
Do you have resharper licence. 
https://www.jetbrains.com/buy/opensource/

**Comment by Mike-EEE** [comment]
Great done.  Please look over the code and see if there is anything that needs changed in the .sln.DotSettings file.  Please feel free to modify and check back in as well.

And yes, I am ReSharper Ultimate for 2 years now. :)  Big fan of JetBrains!

**Comment by Mike-EEE** [comment]
Oops... guess this isn't "closed" until it has been pushed. :)

**Comment by Mike-EEE** [comment]
Btw, here are the ReSharper plugins I use (in order of importance to me):

- [Heap Allocations Viewer](https://github.com/controlflow/resharper-heapview) (shows you each memory allocation you make, invaluable!)
- [TestCop ](https://testcop.codeplex.com/) (nice unit testing compliment)
- [ReSpeller Pro](http://etherealcode.com/respeller-pro)
- [ZenSharp](https://github.com/ulex/ZenSharp)
- [Enhanced Tooltip](https://github.com/MrJul/ReSharper.EnhancedTooltip/)
- [xUnit Live Templates](https://github.com/JetBrains/resharper-xunit-templates)
- [Mnemonic Live Templates](https://github.com/JetBrains/mnemonics) (Like ZenSharp, I think.  have it installed, don't use much)
- [Xao ](https://github.com/hmemcpy/ReSharper.Xao) (have it installed, don't use much).

**Comment by wojtpl2** [comment]
Thank for you! 
I knew about some of them. 
I can recommended to you [VSColorOutput](https://www.visualstudiogallery.msdn.microsoft.com/f4d9c2b5-d6d7-4543-a7a5-2d7ebabc2496)

**Comment by Mike-EEE** [comment]
Oh man... I didn't see your recommendation for VsColorOutput until now.  I will check it out.  It looks like a functionality of VSCommands (which I actually paid for but looks like it went under, doh).

I saw this recently and it looks amazing:
https://marketplace.visualstudio.com/items?itemName=CodeValueLtd.OzCode

They offer an open source license, but you need a website :)
http://o.oz-code.com/open-source
