### ISSUE TITLE
V2 Deployment: Ensure Signed Package

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#52]
While adding [Sprache](https://github.com/sprache/Sprache), we encountered a problem with signed assemblies, captured in https://github.com/sprache/Sprache/issues/87.  The thinking is that libraries by default should not be signed, but should instead also deploy a signed version using the convention `.Signed`.  So in the case of EXS, this would be `ExtendedXmlSerializer.Signed`

**Comment by wojtpl2** [comment]
This was my first issue #3. 
Do you have any information about best practices for signed?
I've checked that, Autofac, AutoMapper, Entityframework are signed by default.

**Comment by Mike-EEE** [comment]
Yeah, I am finding that this is a complicated issue, LOL.  Looks like the result of https://github.com/sprache/Sprache/issues/87 recommends using https://github.com/dsplaisted/strongnamer for development.  I am also OK with ensuring an `ExtendedXmlSerializer.Signed` package that gets deployed to nuget when the CD runs.  I am not sure if AppVeyor allows you to add contributors to your account, but that would be helpful. 👼  We should setup v2 to start deploying pre-release packages to nuget.

**Comment by Mike-EEE** [comment]
Also, this URL is helpful, too: https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md#faq

**Comment by wojtpl2** [comment]
I don't know if AppVeyor allows me to add contributors to my account. I've found but I haven't seen any options to do this. 
Maybe you create account and connect them with you github. Or you can try login by github account. 

You can also modify file appveyor.yml. I've created it based on http://andrewlock.net/publishing-your-first-nuget-package-with-appveyor-and-myget/

**Comment by Mike-EEE** [comment]
OK great I will look into this once we get deployments going.  Hopefully soon. :)

**Comment by Mike-EEE** [comment]
so looking into this, I believe the answer here is not to use signed assemblies at all.  For OSS projects, at least.  If it is really really needed, one can use the strong namer as described above.

I will be closing this issue as such.  Please let me know if this needs a second look by re-opening this issue.

**Comment by wojtpl2** [comment]
OK. Let's close this issue. If somebody will create new issue we will be thinking about it.
