### ISSUE TITLE
NullReferenceException of ExtendedXmlSerializer.Deserialize()

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#54]
I'm trying to Deserialize the following XML which was produced by ExtendedXmlSerializer:

```
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfIPreflightCheck>
	<DiskSpace type="ImageMenu.PreflightChecks.DiskSpace">
		<MinimumMb>20480</MinimumMb>
		<RecommendedMb>40960</RecommendedMb>
		<DiskNumber>0</DiskNumber>
		<Name>Disk 0 Size Check</Name>
	</DiskSpace>
</ArrayOfIPreflightCheck>
```

Yet I immediately get a NullReferenceException.

Here's my code:

```
    public class DiskSpace : IPreflightCheck
    {
                public uint MinimumMb { get; set; }
        public uint RecommendedMb { get; set; }
        public ushort DiskNumber { get; set; }

        public DiskSpace(ushort diskNumber, uint minimumMb, uint recommendedMb)
        {
            DiskNumber = diskNumber;
            MinimumMb = minimumMb;
            RecommendedMb = recommendedMb;

            Name = $"Disk {DiskNumber} Size Check";
        }

        public string Name { get; set; }

        [XmlIgnore]
        public PreflightCheckStatus Status { get; private set; }

        [XmlIgnore]
        public string Message { get; private set; } = "";

        public PreflightCheckStatus Validate()
        {
            ...
        }
    }

    public interface IPreflightCheck
    {
        string Name { get; }

        PreflightCheckStatus Status { get; }

        string Message { get; }

        PreflightCheckStatus Validate();
    }

    var diskSpace = new DiskSpace(0, 20 * 1024, 40 * 1024);
    var t = new ExtendedXmlSerializer();
    var xml = t.Serialize(diskSpace);
    var co = t.Deserialize<DiskSpace>(xml);

```

Any ideas what the problem might be? I'm using version 1.5

**Comment by FaustoNascimento** [comment]
Ok, just realized this is because there's no public empty constructor. If I create a private empty constructor it still fails, but with a public empty constructor it works. Has this been fixed in v2?

**Comment by FaustoNascimento** [comment]
ok, looks like this issue has already been opened twice, so this can be closed, but could one of the others be updated to reflect whether v2 will have this fixed? There were comments to say that it *should* be implemented in v2, but nothing was confirmed.

**Comment by wojtpl2** [comment]
It should be done in v2.

**Comment by Mike-EEE** [comment]
Ahhhh ... yes indeed #8 does capture this.  However. :)  It was recently brought to my attention that [Protobuf](https://developers.google.com/protocol-buffers/) allows for serialization for constructors just as you have them.  The requirement is that each parameter must match an equal property with name and type.

I definitely think it would be cool to support this as well.

**Comment by wojtpl2** [comment]
Of course if this issue will take many time in first step we can add only message "Type X doesn't have public constructor without parameters" or something like that.

**Comment by Mike-EEE** [comment]
I will be closing this issue since it is captured by #8 and opening another issue for the cool Protobuf constructor serialization.  Please let me know if I have something misunderstood and/or feel free to re-open this issue as well.
