### ISSUE TITLE
Make XML pretty

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#55]
By default XmlSerializer outputs indented XML, but ExtendedXmlSerializer does not.

Can you either provide a way to configure the output or match the default output of XmlSerializer?

Or both...

**Comment by wojtpl2** [comment]
I think that we can do this for v2. What do you think @Mike-EEE.

**Comment by Mike-EEE** [comment]
Oh yeah, of course!  Indentation is turned off right now by default because it is a performance hit. :)  Maybe a ConfigurationAPI root method `WithSettings(XmlReaderSettings, XmlWriterSettings)` ?

**Comment by FaustoNascimento** [comment]
So long as don't always have to specify both :)

One might want to only that particular instance of the serializer only to read or write, not both.

**Comment by wojtpl2** [comment]
I've added method WithSettings(XmlReaderSettings, XmlWriterSettings).
That's enough for now. Maybe later we will add overloads:
WithSettings(XmlReaderSettings),
WithSettings(XmlWriterSettings).

**Comment by Mike-EEE** [comment]
Cool... Yeah, I was thinking 2 separate methods but got lazy. :P  Either one works.  We'll hash it out when we get through the ConfigurationAPI.

**Comment by wojtpl2** [comment]
I've changed WithSettings(XmlReaderSettings, XmlWriterSettings)
to
WithSettings(XmlReaderSettings),
WithSettings(XmlWriterSettings).

**Comment by Mike-EEE** [comment]
Alright, this is finally in the v2 branch as part of https://github.com/wojtpl2/ExtendedXmlSerializer/pull/81.  Please let me know if you encounter any problems and/or have additional questions, and re-open this issue.
