### ISSUE TITLE
Fluent Assertions

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#58]
@Mike-EEE Do you know Fluent Assertions? http://www.fluentassertions.com/
I think that it is good framework. What do you think about it?

**Comment by Mike-EEE** [comment]
Oh yeah, I checked it out once.  Testing continues to be something of an area that I need to work on.  I usually write tests just to make sure that things work.  There's so much to learn about best practices and the like.

I am also a big fan of AutoFixture, as well: https://github.com/AutoFixture/AutoFixture

**Comment by Mike-EEE** [comment]
Did you want to include this in the solution?  I am all for it, as well as adding AutoFixture as well.  I am not sure if AutoFixture supports .NETCore, however.

**Comment by Mike-EEE** [comment]
OK I have added fluent `FluentAssertions` but unfortunately `AutoFixture` does not support .NETCore.  I will try to incorporate FA going forward.  Please feel free to use it so I can see how it's done. :)

**Comment by wojtpl2** [comment]
Ok. Great.

**Comment by Mike-EEE** [comment]
FWIW I just passed my first Fluent Assertion.

Nice part about this is that the language stays the same in case there is ever a new testing framework that goes under it.  Very nice. 👍

**Comment by Mike-EEE** [comment]
!!!

http://www.continuousimprover.com/2012/09/asserting-object-graph-equivalence.html

Where has this been all my life?! 😄

**Comment by wojtpl2** [comment]
Yes it is really useful.
