### ISSUE TITLE
V2: Enable Ability to Flush Cached Values

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#66]
via #35, we should implement a way to enable the user to flush out cached values stored in memory if they make use of `cfg.EnableValueOptimizations(bool)`.  Something to the effect of:

```
var aware = serializer as IValueOptimizationAware;
aware?.ClearAll();
```

**Comment by Mike-EEE** [comment]
This is now possible w/ #77.

**Comment by wojtpl2** [comment]
Thank!
