### ISSUE TITLE
New WebPage

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#67]
Move from #20

> It is great page https://www.staticgen.com/. On this page you can see comparison of static web generators. I think that http://gohugo.io/ or http://jekyllrb.com could be useful for us.
> Then we can host this page as github pages.

I've checked hugo. It is very simple. I am able to create web for API like this: http://themes.gohugo.io/hugo-theme-learn. I think it is enough for us. 
We can also create home page like this: http://themes.gohugo.io/theme/hugo-universal-theme/. 

Jekyll is harder to configure than Hugo. I don't have enough time to learn it now. 

We have to think about address of web page. If we use default address for this repository it will be look like: https://wojtpl2.github.io/ExtendedXmlSerializer/. I've configured it.

If we want address 
extendedxmlserializer.github.io
we must create new account on github, named ExtendedXmlSerializer and move this repository there.

We can also buy custom address and set it without moving repository. 
ExtendedXmlSerializer.com would be great. 
But we don't have any budget :wink:

**Comment by Mike-EEE** [comment]
Cool!  Thanks for looking into it.  I definitely think getting a domain right now would be risky, especially if we branch out to other formats and drop Xml from the name (I think XML is the tops... maybe we'll keep the name and support other formats, who knows).

extendedxmlserializer.github.io is my vote. 👍

**Comment by wojtpl2** [comment]
I've change decision. We'll use https://readthedocs.org/ It is great tool. It support for versioning so we can build docs from tags and branches of your code in your repository. It generate pdf too. 

http://extendedxmlserializer.readthedocs.io/en/latest/Index/
It is only imported readme.md, but looks almost great. We need to only write documentation in plain text (reStructuredText).

E.g.:
There is autofac's documentation http://autofac.readthedocs.io/en/latest/
It is generated from:
https://github.com/autofac/Documentation

**Comment by Mike-EEE** [comment]
Cool!  Yes, Benchmark.NET uses that too, if I am not mistaken.  Good company. :)

**Comment by wojtpl2** [comment]
I've moved documentation for version 1.5 to http://extendedxmlserializer.readthedocs.io 

Great features:
- edit documentation from github:
![image](https://cloud.githubusercontent.com/assets/17333903/23365666/2549efee-fd04-11e6-9ddb-61c37d83afca.png)
- versioning:
![image](https://cloud.githubusercontent.com/assets/17333903/23365728/65f8c6e6-fd04-11e6-8cf9-6a83bae7e7ef.png)

**Comment by wojtpl2** [comment]
I'd like to create page like this http://themes.gohugo.io/theme/hugo-universal-theme/ 
But if we need to have address like:
extendedxmlserializer.github.io
We must create new account on github and new mail.

Maybe we should change name now to ExtendedSerializer?

**Comment by Mike-EEE** [comment]
Yeah that looks great!  As for name... going to go there, are you?  :)  

ExtensibleSerializer?

Or how about... 

XSerializer or xSerializer

Shorter. :)

**Comment by wojtpl2** [comment]
This name is already used:
https://www.nuget.org/packages/XSerializer/

**Comment by wojtpl2** [comment]
If we change name we lose history on https://www.nuget.org/packages/ExtendedXmlSerializer/

**Comment by Mike-EEE** [comment]
LOL dohhhhh... should have looked that up first.  This is why I hate naming!  

Yeah I like the name ExtendedXmlSerializer.  I know the temptation is to drop the Xml, but it is what we are good at (NOW :) ), and anything else my be a little presumptuous.  I say let's go organic and stick with `ExtendedXmlSerializer` if we can help it.  Who knows, maybe we'll make XML cool again. :)

**Comment by Mike-EEE** [comment]
You know, just a (dangerous 😁) thought, but we could use a different name altogether.  The thing about "Xml Serialization" is that it is usually data-based.  Not many use it primarily for .NET POCO serialization.  Or if they do, they run into the problems that we fix.  There isn't a "XML POCO Serializer that 'Just Works'."  Which should be our motto/goal.

So maybe something with "POCO" in it?  POCOMOCO (like locomotion) comes to mind haha.  Or maybe Mo'POCO (More POCO).  Might be too silly, but maybe not. 👼 

I also have been thinking of the word "Blaze" recently for some reason.  Problem there is Blaze Serializer ([BS](http://www.urbandictionary.com/define.php?term=BS&defid=21513)) haha.

I'll keep thinking of it some more.

**Comment by wojtpl2** [comment]
I don't have enough time for this project in this week. Maybe next week will be better or next.

**Comment by Mike-EEE** [comment]
No worries.  I am cranking along here and hope to be feature complete with the Configuration API by next weekend.  We'll see how I do. :P

**Comment by wojtpl2** [comment]
I've seen your private api. It should be easy connect it to my fluent API.

**Comment by Mike-EEE** [comment]
Totally the idea. 😄

**Comment by wojtpl2** [comment]
I was thinking about name and we should keep ExtendedXmlSerializer name. We will be thinking about change when we will add other format. What to you think?

**Comment by Mike-EEE** [comment]
Definitely think that is the way to go!

**Comment by wojtpl2** [comment]
I've created ExtendedXmlSerializer@gmail.com and account on github ExtendedXmlSerializer. We need this account because we want ExtendedXmlSerializer.github.io address.

**Comment by Mike-EEE** [comment]
Great, sounds good!  One less thing to worry about. :)

**Comment by wojtpl2** [comment]
In next week maybe I'll have more time and I'll find time to create web.
How about you? How's everything coming along?

**Comment by Mike-EEE** [comment]
Coool... looking into the ConfigurationAPI now.  I am going to do the type configuration first and then the member configuration.  Hopefully should be done by this weekend. 👍   After that, it's tackling all these issues on here, and then helping out with documentation.  Then we can finally call this sucker done.  Hopefully. 😄

**Comment by wojtpl2** [comment]
What do you think about this logo. It is only idea.
![untitled 3](https://cloud.githubusercontent.com/assets/17333903/24354468/35aaf8ca-12f2-11e7-9507-3ce429296f79.png)
I am not graphic designer but I think this logo should fit with **Extended**XmlSerializer.

**Comment by wojtpl2** [comment]
or more square: 
![untitled 5](https://cloud.githubusercontent.com/assets/17333903/24355275/8ffa6bfa-12f5-11e7-915e-dc4cd03c4fad.png)

**Comment by Mike-EEE** [comment]
I like the 2nd one... can we flip it on its side? Or upside down?  It almost looks like a face that is crying currently. :)

**Comment by wojtpl2** [comment]
There is:
![untitled 7](https://cloud.githubusercontent.com/assets/17333903/24359155/c5b3e2f4-1303-11e7-82ff-95affe0f884d.png)

**Comment by Mike-EEE** [comment]
How about this? :)

![exs](https://cloud.githubusercontent.com/assets/2931376/24366180/5118dcbe-12e6-11e7-85e7-2e06be612669.png)

It sort of looks like an "E". 😄 And there is an "S" in there too (top).  No X though.  Maybe we _should_ call it Extended Serializer hahah.

**Comment by wojtpl2** [comment]
It is true. There is "E" and "S". I think that it is the best graphic I've ever made. I think it is enough for now. What do you think?

**Comment by Mike-EEE** [comment]
I think it's a great first run!  Good first step towards progress. 😄

**Comment by ExtendedXmlSerializer** [comment]
https://extendedxmlserializer.github.io/ExtendedXmlSerializer/

**Comment by ExtendedXmlSerializer** [comment]
It is first version.

**Comment by Mike-EEE** [comment]
AWESOME!  That looks great!

**And now you are SOOOOOOO going to hate me! LOL.**  I was working out in the gym and I *finally* got inspired about some names. 👼   Your logo inspired me. 😄 

Are you familiar with [Transformers](https://transformers.hasbro.com/en-us)?  I was thinking your cool purple shade looks like the purple [Decepticons](https://www.google.com/search?q=decepticon+purple) use for their color.

Then I started thinking... How about Extendicon?  Or even Extenditron? (I _really_ like that one)  Something robot-y that fits well with your logo.  Also, there's a really cool name generator here:
http://www.namemesh.com/domain-name-search/extend?show=1

Interesting to see that x.tn is available. 😮 

The other thought I have been kicking around is that I am thinking that adding on a JSON formatter would be really really powerful and might not take that long (maybe a week?).  Everything that I have worked on in the past few weeks has worked in smoothly.  I am thinking of riding that wave and looking into JSON formatting for the next week.  It doesn't have to be 100%, but simply demonstrates an extension that changes the format of the input/output altogether.

What do you think?  Do you hate me yet? 👼 👼 👼  Hahaha.

**Comment by Mike-EEE** [comment]
Also just thought of this one:

x10  ("ex-ten").  Kind of cool because it is [1-0](https://en.wikipedia.org/wiki/Binary_code). :)

**Comment by wojtpl2** [comment]
If we change package name we lose history on nuget. Currently we have 1683 downloads. This users newer show information about update. 
But I have idea. 
We can rename 
ExtendedXmlSerializer.Legacy -> ExtendedXmlSerializer
ExtendedXmlSerializer -> new name
In legacy ExtendedXmlSerializer we mark all class by Obsolide with message "Update to NEW_NAME: URL".

But in this way we have to own domain. NewName.com or something like that. 

I don't have idea what name is better. I'm Polish :poland: I like Extenditron but it is long. What do you think about Extentron? 
But this name don't say that it is for save file. What do you think about: ExSaver? ExtSaver?

**Comment by Mike-EEE** [comment]
No you are 💯% right.  Sometimes it takes things getting out of my head to see how I feel about it.  I took another look at the site, and it "feels" right.  I think we should go with this for now.  Anything else is adding unnecessary risk (like I have already said before! LOL).

**Comment by Mike-EEE** [comment]
I also get funny ideas when I work out, part of the creative process. 😝

**Comment by wojtpl2** [comment]
Now you are adding JSON or something else?

**Comment by Mike-EEE** [comment]
Ah yes... Markup extensions has taken a little longer.  It's good though because it exposed some bugs.  Fixing them now and should have something committed EOD or tomorrow at the latest.  Then I'll decide if I want to do JSON.  :)

**Comment by wojtpl2** [comment]
Ok your choice ;) 
We will release version only if we decide. 
I have some issue in WebPage on smartphone. I'll do it in next week.

**Comment by Mike-EEE** [comment]
Cool.  I will probably do it just because it is a challenge but also because of finding more bugs before someone else does. 👼 

I heard from someone @ MSFT that the next version of Windows 10 is out very soon, maybe a couple weeks.  And then there is this from ReSharper:
https://blog.jetbrains.com/dotnet/2017/03/30/resharper-ultimate-2017-1-eap-8/

(Next Monday)

So maybe when I am done w/ JSON support these will be done and hopefully a new update for VS2017. 👍

**Comment by Mike-EEE** [comment]
I went ahead and updated https://github.com/wojtpl2/ExtendedXmlSerializer/ -> https://extendedxmlserializer.github.io/ namespaces in code.

Please note that we have a [link in legacy code](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/src/ExtendedXmlSerializer.Legacy/Support.cs#L29) to [this this URI](https://github.com/wojtpl2/ExtendedXmlSerializer/wiki/Configuration-API) but it doesn't work currently in the new site.  

https://extendedxmlserializer.github.io/ExtendedXmlSerializer/wiki/Configuration-API <-- where is this in the new site?  Or is it not ready yet?

**Comment by wojtpl2** [comment]
Our side is https://extendedxmlserializer.github.io/ExtendedXmlSerializer/ . I don't know why not https://extendedxmlserializer.github.io . 

I'll create this link. Thank for reporting.

**Comment by wojtpl2** [comment]
I'll continue working next week.

**Comment by wojtpl2** [comment]
There is first version of documentation for 2.0.0. 
http://extendedxmlserializer.readthedocs.io/en/v2.0.0/

This documentation is generated from code. If we change something in xml or configuration or class, we could regenerate documentation. No more CTRL+C -> CTRL+V.

**Comment by Mike-EEE** [comment]
Hey that's great! 👍

**Comment by wojtpl2** [comment]
Documentation for 2.0.0 is rewritten. 

It is the last part of doc: 
http://extendedxmlserializer.readthedocs.io/en/v2.0.0/get-started/index.html#property-encryption
I've found one issue with configuration of encryption. I'll create issue tomorrow.

**Comment by wojtpl2** [comment]
Address http://extendedxmlserializer.github.io/ is working now!

**Comment by Mike-EEE** [comment]
Fantastic!

**Comment by wojtpl2** [comment]
There is api doc: https://extendedxmlserializer.github.io/doc-v2.0.0

**Comment by Mike-EEE** [comment]
I believe this issue is closed.  We have our web page open, available, and accessible and it looks very nice.  Great work @wojtpl2. :)
