### ISSUE TITLE
V2: Upgrade to .NET 4.6

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#68]
Oh man, I've been _trying_ to work on references but got caught up in another blasted performance rabbit hole.  The news is good, however.  [I found the problem](https://github.com/dotnet/BenchmarkDotNet/issues/363#issuecomment-282535089) and it is actually faster than before (~33us serialization and ~44us deserialization on my machine).

Well, almost.  [Please read this issue](https://github.com/dotnet/BenchmarkDotNet/issues/371#issuecomment-282542865).  There is a better solution to this, [but it requires .NET 4.6](http://stackoverflow.com/a/32007523/3602057).  Do you see any problem in upgrading to this?

**Comment by wojtpl2** [comment]
No. You can upgrade.

26.02.2017 10:12 "Mike-EEE" <notifications@github.com> napisał(a):

**Comment by Mike-EEE** [comment]
Cool.  I will do so.  FWIW that weirdness went away but it's probably best to utilize the latest and greatest, just in case. :)

**Comment by wojtpl2** [comment]
Or maybe you can try add frameworks 4.6 to https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/project.json#L28
and use preprocessor directives.
But only if it will be easy. It is not very important for me.

**Comment by Mike-EEE** [comment]
Ahhh yeah, I hate those directives. :P  I basically went through and changed everything to `#if CORE` to mark the difference.

Speaking of which, I have been getting caught up in .NET Core tooling nightmare.  Turns out all the performance "weirdness" was actually due to the `ExtendedXmlSerializer.Performance.Tests` not compiling correctly!  So even though it would say it compiled, it would be using a previous version. 😟   So I was basing all my results/understanding of a previous compile altogether. 

Also, I've noticed that "clean" does not even clean the directory!  Does it do the same for you?

In any case, it looks like doing a `rebuild` does the trick to solve the problem above.  Such a pain.  `project.json` was supposed to provide a "lit up" experience, and all it has done is lit my fuse. 😠 

I did get references working, but noticed that performance was down again, and have been chasing it since.  I hope to have a commit for you tomorrow EOD at the latest.  Despite all the tooling hassles it's starting to finally shape up.

**Comment by wojtpl2** [comment]
Being honest: I hate directives too. ;)

Maybe we should move to new csproj format? To VS 2017. But I wander if I will be able to use VS 2015 🤔

**Comment by Mike-EEE** [comment]
I read somewhere once that hashtags belong on Twitter, and I cannot agree more. :p 

As for VS2017, I doubt it is any better there.  If you follow along w/ the CPS project (the new project system) it doesn't look too good with the reports that are coming in.  And that's before you add ReSharper. :P  So it's going to be a while still.  Regardless, we should probably switch over when it is available next week (and are feature complete).

Unfortunately VS2015 does not support the new format. :(

**Comment by Mike-EEE** [comment]
Reverting back to 4.5.1 to be safe.  Please let me know if this will be an issue.
