### ISSUE TITLE
Serialization class that inherits from IList, ICollection with additional properties

### ISSUE THREAD

**Issue by TobiasSico** [wojtpl2/ExtendedXmlSerializer#7]
Hello again!

In the last few days I worked very intensive with XML serializing. For my Tests I used the default XmlSerializer and the ExtendedXmlSerialize to be able to compare the advantages and disadvantages of both. By my Tests I noticed two issues of the ExtendedXmlSerializer, which I want to tell you.

 1) when a class derives from Collections, the ExtendedXmlSerializer is not able to serialize it. Then a NullReferences Exception will be thrown.

Example class:
public class ListOfTest : List<Test>
{
  public string name { get; set; }
}

The default XmlSerializer can do this, but there are also some Problems with it:
-) List<T> only works when T is not an Interface
-) only the List get serialized and deserialized, all other Properties don't. (from example the property "name" would not get serialized) 

 2) if a Property has the Datatype "object" the ExtendedXmlSerializer serialize it, but is not able to deserialize it. After deserializing the XML all Properties which have the Datatype "object", would have the string "System.Object" as value.

Example:
public class Test
{
  public object testProperty { get; set; }
}

TestData:
 Test t = new Test() { testProperty = 1234; }
 Test t2 = new Test() { testProperty = "name"; }

Xml-Output would look like this:
```
<?xml version="1.0" encoding="utf-8"?>
  <Test>
     <testProperty>
        1234
     </testProperty>
  </Test>
  <Test>
     <testProperty>
        name
     </testProperty>
  </Test>

```
TestData after deserialize:
 t.testProperty == "System.Object"; 
 t2.testProperty == "System.Object"; 

I hope this information will help you by bugfixing and by upgrading the ExtendedXmlSerializer.

**Comment by wojtpl2** [comment]
Thank you for reporting these errors. It is very helpful.
I have to check it.

**Comment by wojtpl2** [comment]
1. This bug is difficult to fix. It well be fixed in version 2.0.0, but I don't know when that will be. If you wont you can create pull request. 
2. This bug is fixed in version 1.4.1.

**Comment by Mike-EEE** [comment]
Hello, thank you for making this project and for keeping it so current.  I was going to file a bug, but I will append this instead as it is similar and I want to see if I am running into the same problem.

I have the following class:

```
	public class Processor : IProcessor, ITask
	{
		public void Execute( IProcessingContext context )
		{
			foreach ( var task in Tasks )
			{
				task.Execute( context );
			}
		}

		public Collection<ITask> Tasks { get; } = new Collection<ITask>();
	}
```

It has a list of tasks (that implement `ITask`) in there, but when I serialize it, this is my result:

```
<?xml version="1.0" encoding="utf-8"?><Processor type="Namespace.Model.Processor" />
```

Is this the same problem?  Or is there a way to serialize the collection items as expected?  Thank you for any assistance you can provide. :)

**Comment by wojtpl2** [comment]
Properties need to have set accesory. In your case try:
public Collection<ITask> Tasks { get; set; } = new Collection<ITask>();
	}

**Comment by Mike-EEE** [comment]
Perfect!  Yes, that works.  Thank you!  that is what I expect when I try to use DataContract/XmlSerializer, but as you know, it takes a lot of configuration, especially when compared to JSON.NET.

That said, JSON.NET and Xaml support read-only properties, so no modification of the POCO model is required.  Is this something you have thought about supporting?  It would be super cool/awesome if you did. 😄

**Comment by wojtpl2** [comment]
Do you know if this issue is fixed in v2? If yes you can close it.

**Comment by Mike-EEE** [comment]
Yes, this *should* be fixed now.  I just need to wire it up. :)
