### ISSUE TITLE
Submodule Dependencies

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#71]
As per https://github.com/wojtpl2/ExtendedXmlSerializer/pull/69#issuecomment-283595466, we should get our dependencies into submodules, and reduce the amount of generated assemblies for EXS.

**Comment by wojtpl2** [comment]
For JetBrains.Annotations we can use:
http://stackoverflow.com/a/15680284/4809321

Resharper-> Options -> Code Annotations -> Button "Copy C# implementation to clipboard". 
Then paste into .cs file.

**Comment by Mike-EEE** [comment]
Cooool... I should have done that from the start.  Too busy getting it all working. 👼   Thanks for the info!

**Comment by Mike-EEE** [comment]
This has been addressed with #86.
