### ISSUE TITLE
ExtendedXmlSerializer.Legacy

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#76]
So I am looking at the Configuration API now.  I think you mentioned you did this, but the `Legacy` configuration was moved from legacy into v2 root.  

The point of `Legacy` was to have it there in case people wanted to migrate their XML from v1 to v2.

But now I am thinking, maybe we should have an `ExtendedXmlSerializer.Legacy` nuget for this.

So we can take the `Legacy` out, and put it in this new package, along with tests.  It would help make it less confusing?  What do you think?

**Comment by Mike-EEE** [comment]
Actually, tests would not go into the nuget package.  But we would make a `ExtendedXmlSerializer.Tests.Legacy` project that are the tests for `ExtendedXmlSerializer.Legacy`.

**Comment by wojtpl2** [comment]
It's not true. 
Old configuration is ExtendedXmlSerialization.Legacy.ExtendedXmlSerializerConfig
New configuration is in ExtendedXmlSerialization.Configuration namespace.
New configuration has tests too in ExtendedXmlSerialization.Test.Configuration.

New configuration isn't used in Legacy code.

It is great idea to separate new code from old. 
Names is good: ExtendedXmlSerializer.Legacy and EtendedXmlSerializer.Tests.Legacy.
After deploy v2 people will need to change nuget package or update theirs code to new version.

**Comment by wojtpl2** [comment]
New Configuration ExtendedXmlSerialization.Configuration I created only for version 2.

**Comment by Mike-EEE** [comment]
Ahhhhh then it seems I got my code switched around, haha.  Alright, cool, yeah I must have gotten some wires crossed as I thought I saw some Legacy  code referencing v2 contracts.  I will keep an eye out as I dive through this.

**Comment by Mike-EEE** [comment]
This is now done per #81.  Please note that I changed the default namespace for `ExtendedXmlSerializer` from `ExtendedXmlSerialization` to `ExtendedXmlSerializer`.  This works well because the `ExtendedXmlSerializer.Legacy` project is `ExtendedXmlSerialization`.

Also note that I have updated the test projects so that they are consistent in the format of `ExtendedXmlSerializer.Tests.*`

**Comment by wojtpl2** [comment]
Namespace ExtendedXmlSerializer isn't good idea. 
If you want create ExtendedXmlSerializer() without configuration. in your code you have to write:
new ExtendedXmlSerializer.ExtendedXmlSerializer() because name of class is the same as namespace. 

In XmlSerializer is the same situation, that is why the namespace is System.Xml.Serialization.

But if it isn't true this name is ok for me.

**Comment by Mike-EEE** [comment]
Ah but you cannot directly create an `ExtendedXmlSerializer` from code starting in v2, correct?  It is internal now, and the only way you can create it is through ConfigurationAPI.  Let me know if I have this wrong.

**Comment by Mike-EEE** [comment]
I see where the confusion is... `ExtendedXmlSerializer` is public still.  I was going to make it internal for #70, along with all the other classes for this task.

**Comment by wojtpl2** [comment]
Ok. great!
