### ISSUE TITLE
Allow deserialization of classes with private/internal constructor

### ISSUE THREAD

**Issue by kulbitskayak** [wojtpl2/ExtendedXmlSerializer#8]
I'm trying to deserialize the class with private constructor and receiving NullReferenceException somewhere in ReadXML method. With changing access modifier to public the issue has gone.

**Comment by wojtpl2** [comment]
thank you for reporting this bug.
I've never tried to serialize object with private constructor. I need to check how standard XMLSerializer works.

**Comment by Mike-EEE** [comment]
Alright, I have (_finally_ LOL) ensured that this works as expected.  A new prerelease version of EXS should be out end of week for you to try.  I will update this thread when posted.  Here is the passing test that demonstrates this functionality:

```
[Fact]
		public void PrivateConstructor()
		{
			var configuration = new ExtendedConfiguration().Extend(AllConstructorsExtension.Default);
			var support = new SerializationSupport(configuration);
			var instance = Subject.Create("Hello World from Private Constructor (hopefully)!");
			var actual = support.Cycle(instance);
			Assert.Equal(instance.PropertyName, actual.PropertyName);
		}

		class Subject
		{
			public static Subject Create(string message) => new Subject { PropertyName = message };

			Subject() {}

			public string PropertyName { get; [UsedImplicitly] set; }
		}
```

I will be closing this issue for now.  Please feel free to reopen or open a new issue altogether if something does not work to your expectations.

**Comment by Mike-EEE** [comment]
FWIW, pre-release deployment for this feature can be found at these feeds:
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha
