### ISSUE TITLE
Protobuf-style Constructor Support

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#82]
As discussed in https://github.com/wojtpl2/ExtendedXmlSerializer/issues/54#issuecomment-279987252

Protobuf has some cool functionality around this.  I have been thinking a little about how we could do it here for EXS, and it might be challenging, but it still might be worth checking out.

**Comment by wojtpl2** [comment]
I don't know what you want to do in this issue ;)

**Comment by Mike-EEE** [comment]
Hehe, I can't think of a good, concise name for it, so I don't blame you.

I guess we could call it Protobuf-style Constructor Support.

So given:

```
class Subject
{
	public Subject(string propertyOne, int propertyTwo)
	{
		PropertyOne = propertyOne;
		PropertyTwo = propertyTwo;
	}

	public string PropertyOne { get; }
	public int PropertyTwo { get; }
}
```

EXS could read and write an instance from:

```
<Subject PropertyOne="Hello World!" PropertyTwo="6776" />
```

**Comment by Mike-EEE** [comment]
This is now possible with the latest commit.  A very basic version, that is.

Also, I just realized that the initial link that I provided for this feature isn't the link that I was thinking about, so no wonder there is confusion.  Here is a link that describes it in further detail:
http://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html
