### ISSUE TITLE
Markup Extensions :) :) :)

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#83]
I have been thinking lately that I would be remiss to spend so much time and energy on this project and not enable markup extensions, my favorite feature from Xaml.  This would in effect make EXS as a Xaml parser in addition to being a XML POCO parser.

This should be an extension, obviously.  FWIW while I am not the happiest with the ConfigurationAPI (I'd rate it like 6/10), I am very happy with the ExtensionModelAPI (an 8 or 9 out of 10).  Lots of cool stuff there and I think it's a great new way to look at serialization. 👍

**Comment by wojtpl2** [comment]
I like your changes in Configuration, but I don't know what you want to do in this issue .

**Comment by Mike-EEE** [comment]
So Markup Extensions are an awesome feature of Xaml that allow you to provide runtime values for a property while the object is being serialized.  They also allow you to tie into the object that is being serialized so that you can do cool things with it as time goes on (like binding).

Super simple example here:

```
public class MyMarkupExtension : IMarkupExtension
{
	public object ProvideValue(IServices services) => "Hello World"; // <-- could be from a web service or anywhere.
}
```

```
class Instance
{
	public string PropertyValue { get; }
}

<Instance PropertyValue="{x:MyMarkup}" />
```

```
var serializer = new ExtendedConfiguration().Create();
var actual = serializer.Deserialize<Instance>();
Assert.Equal( actual.PropertyValue, "Hello World!");
```

Another scenario could be how we use references.  Instead of using custom attributes (exs:reference/identity), we could use markup extensions instead. That's how Xaml does it. :)

**Comment by Mike-EEE** [comment]
OK this took a little longer than expected, but we now have a very simple implementation of markup extensions with core support for default framework markup extensions such as [Null](https://msdn.microsoft.com/en-us/library/ms743649%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396), [Type](https://msdn.microsoft.com/en-us/library/ms753322%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396), and [Static](https://msdn.microsoft.com/en-us/library/ms742135%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).  Basically got done in one week [what the entire UWP group has taken nearly seven years to do](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/7232264-add-markup-extensions-to-and-improve-winrt-xaml). ;)

Example of the static extension can be seen [here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/Markup/MarkupExtensionTests.cs#L85-L92).

Please note that in addition to specifying strings for values within a markup extension, I took it one step further so that you can use actual .NET/C# expressions within it.  So let's say you have an extension like this:

```
sealed class NumberExtension : IMarkupExtension
{
	readonly int _number;

	public NumberExtension(int number)
	{
		_number = number;
	}

	public object ProvideValue(IServiceProvider serviceProvider) => _number;
}

sealed class Subject
{
	public int Number { get; set; }
}
```

You are able to use it in your markup as such:

```
<?xml version="1.0" encoding="utf-8"?>
<Subject xmlns="clr-namespace:YourNamespace;assembly=YourAssembly" PropertyName="{Number 3 * 4}" />
```

```
var subject = new ExtendedConfiguration().EnableMarkupExtensions().Create().Deserialize<Subject>(xml);
subject.Number.Should().Be(12);
```

Cool huh!  Unfortunately (or fortunately, depending on your perspective :) ), in order to do this, we had to take on a dependency.  Currently, it is using the very powerful and handy [Eval-Expression.NET](https://github.com/zzzprojects/Eval-Expression.NET/issues/4).  It is free for the first 50 characters.  I am in communication with @JonathanMagnan in regards to this to see if we can somehow get a pro version if we give it special mention/thanks in our README.  Jonathan has said that they should have something together by Monday to discuss.

Also a consideration here Jonathan (and feel free to reply here): currently we are using all of our dependencies inline.  So we currently have two dependencies in [Sprache](https://github.com/sprache/Sprache) and [LightInject](https://github.com/seesharper/LightInject).  Both of them have been [placed in our Core folder](https://github.com/wojtpl2/ExtendedXmlSerializer/tree/v2.0.0/src/ExtendedXmlSerializer/Core) with licenses provided for both.

Will this be OK for your project as well?

I will be closing this issue to mark as done for now to get it off our list towards the milestone.  Please feel free to continue to comment.

**Comment by wojtpl2** [comment]
Build failed ;)

There is log: https://ci.appveyor.com/project/wojtpl2/extendedxmlserializer/build/72

**Comment by Mike-EEE** [comment]
Hah!  It sure did.  Is there a notification for this, perhaps?  Seems like an important one to know. :)

The break is actually due to Eval-Expression.NET.  It looks for a new package at the start of every month.  I believe this is what Jonathan and team are looking for in our case here.  

I just committed a fix.  HERE GOES NOTHING!! 😆

**Comment by Mike-EEE** [comment]
OK this looks like this is working as expected now.  Let me know if it is otherwise.
