### ISSUE TITLE
Implicit Namespaces

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#84]
As per #24, we want to make it so that we can describe a core set of namespaces/assemblies that are searched for type resolution.  This should decrease emitted XML considerably, but also can lead to problems if there is more than one type with the same name in an assembly.  This will be a very simple implementation with a "use at your own risk" expectation.

**Comment by Mike-EEE** [comment]
This actually turned out pretty good.  I got basic support in there now.  You can see how it's done [here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/ImplicitTypingExtensionTests.cs).

Here it is without:

```
<?xml version="1.0" encoding="utf-8"?>
<ImplicitTypingExtensionTests-Subject xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel;assembly=ExtendedXmlSerializer.Tests">
	<Items>
		<Capacity>4</Capacity>
		<string xmlns="https://github.com/wojtpl2/ExtendedXmlSerializer/system">Hello</string>
		<string xmlns="https://github.com/wojtpl2/ExtendedXmlSerializer/system">World!</string>
	</Items>
</ImplicitTypingExtensionTests-Subject>
```

Here it is enabled:

```
<?xml version="1.0" encoding="utf-8"?>
<ImplicitTypingExtensionTests-Subject>
	<Items>
		<Capacity>4</Capacity>
		<string>Hello</string>
		<string>World!</string>
	</Items>
</ImplicitTypingExtensionTests-Subject>
```

Cool huh!

**Comment by wojtpl2** [comment]
it's amazing! I'm really impressed!
Thank for your effort.
