### ISSUE TITLE
Doc public API

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#85]
We have to add xml comment to public API.
For all classes, functions and properites. 

After that we will generate api doc. This comments are shown in intellisense in VisualStudio.

**Comment by Mike-EEE** [comment]
FWIW I have a document generator that we can start out with, [GhostDoc](http://submain.com/blog/ReleasedGhostDocV50.aspx).  Unfortunately when I purchased it with "Lifetime Upgrades" it was only for v4.  It is v5 now. I've reached out to them to see if they would help support our project and we can add them to the credits (like OzCode and ReSharper).  I will update here when I hear of more.

**Comment by wojtpl2** [comment]
I've used https://github.com/EWSoftware/SHFB/releases/tag/v2017.1.28.0

**Comment by wojtpl2** [comment]
I've pushed new project ExtendedXmlSerializer.Documentation. Documentation will be generated after build this project and will be located in docGenerator\ExtendedXmlSerializer.Documentation\Help
The Help folder is marked as ignored. It will be hosted on pages. 

But now we have comments in API.

**Comment by wojtpl2** [comment]
Of course you have to install https://github.com/EWSoftware/SHFB/releases/tag/v2017.1.28.0
This tools support VS 2017 too.

**Comment by Mike-EEE** [comment]
Ah!  OK cool.  GhostDoc has some cool features like being able to collapse all documentation, which I how I would prefer to view code.  English just gets in the way. ;)  So I'll use it for that. 👍

**Comment by wojtpl2** [comment]
But something works wrong now with it. I'm checking it now.

**Comment by Mike-EEE** [comment]
OK cool.  I got it installed but haven't got latest code yet.

**Comment by wojtpl2** [comment]
Now you can try it.

**Comment by wojtpl2** [comment]
Sorry. I haven't push my changes. Now my changes are in git.

**Comment by Mike-EEE** [comment]
Btw, I just saw this PostSharp webinar that you might be interested in.  I will be checking it out for sure:
https://www.postsharp.net/webinar-fluent-interfaces

If you aren't familiar with [PostSharp](https://www.postsharp.net), I highly recommend it.  I use it for my Framework and it is very powerful stuff.

**Comment by wojtpl2** [comment]
I used to PostSharp. But I think it isn't free.

**Comment by Mike-EEE** [comment]
Guess again. 😎 

https://www.postsharp.net/purchase/request-free

Add that to the list of possible contacts once we deploy v2.  The problem is that I haven't hit a scenario yet where PostSharp would be a good answer for it. But regardless, it's a really nice tool to have in the toolbelt if you can have it.

**Comment by wojtpl2** [comment]
There is doc api: https://extendedxmlserializer.github.io/doc-v2.0.0/
