### ISSUE TITLE
Prerelease of ExtendedXmlSerializer

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#88]
I have been mentioning this, but I wanted to ping and get this on the radar.  How difficult would it be with the current setup to deploy a prerelease version of v2?  I have been planning on looking into this when I get the chance, but the thought strikes me that if it is an easy thing to do based on current setup and configuration, why not do that instead? :)

**Comment by wojtpl2** [comment]
I've published packages on myget:

https://www.myget.org/feed/Packages/wojtpl2
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer
https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer.Legacy

Let me know if you want this packages on normal nuget.

**Comment by Mike-EEE** [comment]
Great, thank you!  Are you able to post to nuget prerelease as well?  If it's too much work don't worry about it.  I will get to it when I do deployments, hopefully by end of this week.

**Comment by wojtpl2** [comment]
it is easy.

Publish to myget:
`git push <- to master or v2.0.0 branche`

Publish to nuget:
```
> git tag v2.0.0-alpha
> git push origin --tags
```

**Comment by wojtpl2** [comment]
I've configured it today.

**Comment by wojtpl2** [comment]
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha

**Comment by wojtpl2** [comment]
![image](https://cloud.githubusercontent.com/assets/17333903/24139829/f46f63d8-0e1d-11e7-91de-b9c59c7c2635.png)

**Comment by Mike-EEE** [comment]
Wow that is amazing! LOL! Very cool!

**Comment by wojtpl2** [comment]
And Legacy version: 
https://www.nuget.org/packages/ExtendedXmlSerializer.Legacy/2.0.0-alpha

**Comment by Mike-EEE** [comment]
!  Seriously that's **really** impressive!  Really amazing with what you can do in that regard now.  Deployments used to be such a grueling effort.

**Comment by Mike-EEE** [comment]
The best part about this is that it takes care of one more item from the issue list. 😄
