### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#90]
Well, double whammy.  While implementing the feature for #56, I found out two issues.

1. We have a performance creep between 4f015846a5fb899eb5865e432b095722b273d0c1 and the current commit (b61e39944009dc07fa9124e7de7ad2df6179ae92).  Here is the performance from the first:

```
                            Method |       Mean |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 34.9980 us | 0.0149 us |
 DeserializationClassWithPrimitive | 44.8417 us | 0.0299 us |
```

And here it is currently:

```
                            Method |       Mean |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 37.0960 us | 0.0456 us |
 DeserializationClassWithPrimitive | 48.5083 us | 0.0949 us |
```

I took some time to see where it could be taking place, but could not see anything obvious.  I did find one area that I fixed, but it is still too slow.  To be honest, I am a little burnt out on fixing the performance, so I am definitely open to any assistance here.  It has easily consumed 40% of my time on this project, if not more.

2. Secondly -- and probably worse -- it appears that the way in which we were testing the original `XmlSerializer` was not accurate.  I have updated the tests so [that they are doing the same thing](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests.Performance/Benchmarks.cs#L112-L151) as how we are testing v2 (using XmlWriter/Reader directly), and here are the new results:

```
                            Method |       Mean |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 40.8919 us | 0.2061 us |
 DeserializationClassWithPrimitive | 57.7255 us | 0.0529 us |
```

This is from ~62/60 on my machine.  So, a considerable jump.

Just so you know, I start a new work project on April 3rd, so I will not be able to help out here much after that.  I hope to have all the outstanding issues complete by then.  Although I am not so sure about this one.  If you want to help out and look at this issue, please feel free to do so.

**Comment by Mike-EEE** [comment]
I did find an issue where the benchmarks were not properly using the new `ClassicExtension`.  This was addressed, and while the reading improved, the writing actually got worse:

```
                            Method |       Mean |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 38.5309 us | 0.0275 us |
 DeserializationClassWithPrimitive | 45.4199 us | 0.0441 us |
```

The writing used to be @ 32, so that is a huge jump.

**Comment by Mike-EEE** [comment]
OK I found the culprit and have pushed it in.  Here is the current results on my machine, which is at the absolute limit of what I would accept for v2 (aiming for 35 write and 45 read):

```
                            Method |       Mean |    StdDev |
---------------------------------- |----------- |---------- |
   SerializationClassWithPrimitive | 35.8604 us | 0.0360 us |
 DeserializationClassWithPrimitive | 45.8316 us | 0.0298 us |
```

If I get some extra time I will see if I can narrow that down even further.

**Comment by wojtpl2** [comment]
This result is really great!
