### ISSUE TITLE
Code Analysis

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#91]
Part of our deployment readiness should be to ensure code adheres to a basic set of code analysis rules.  I have a good set that I have landed on with my framework if that is a good starting point:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.ruleset

BTW, I broke up the remaining tasks into milestones and got rid of the v2 label.  It's pretty cool.  You can view and add issues directly to the milestone here:
https://github.com/wojtpl2/ExtendedXmlSerializer/milestone/1

**Comment by wojtpl2** [comment]
It is good list. 

How many issues CA1000 (Do not declare static members on generic types) we have?

**Comment by wojtpl2** [comment]
Milestones is good idea!

**Comment by Mike-EEE** [comment]
Hey thanks.  As for CA (code analysis), I haven't ran it yet. :)  But the thought strikes me... does CA even work w/ .NET Core? :/

**Comment by Mike-EEE** [comment]
Blarg... of course .NET Core does not support Code Analysis w/o a bunch of work. 😠 
http://stackoverflow.com/questions/32148225/use-code-analysis-with-visual-studio-dnx-project-xproj

Looks like this will be something to do after VS2017 upgrade.  Speaking of which that needs to be captured.

**Comment by Mike-EEE** [comment]
Alright, looks like VS2017 new projects doesn't support CA, but we're using ReSharper which covers a good range.  I went through and fixed all the outstanding issues so this will do for now.
