### ISSUE TITLE
Upgrade to VS2017

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#92]
This should be the very very _very_ last thing that we do. 

Have you installed VS2017 yet?  I have not, and I have not seen very many positive things said about it.  Since its launch it has increased by 2,000 problems:
https://developercommunity.visualstudio.com/spaces/8/index.html
:/

I know that ReSharper 2017.1 is due to release next week or the week after.  They are already working on a VS2017 Update.  Ideally we could upgrade when both of those are released.

FWIW, I am thinking "v2.0" milestone as "feature complete" and then "v2.1" will be all the fixings like documentation and website.  I will update them accordingly.

**Comment by wojtpl2** [comment]
I don't have VS2017. I agree with you that it should be last thing in v2. 

I think that we can't release v2.0 without documentation. The min reqiurements for me is new readme with describe all old functionality. New extensions we can describe later. 
If we will have new readme then I will update article on CodeProject.

**Comment by wojtpl2** [comment]
In this week I won't have enough time for documentation. I'll try publish simple web page  by the end of week.

I was thinking about extensions. Do you know how extensions work together? Are all extensions compatible with other ?

**Comment by Mike-EEE** [comment]
Oh yeah I am fully expecting to help out with documentation, don't you worry! :)  I actually want to write a blog post [on my blog](http://blog.developers.win) about this project so I won't be able to do that until it's documented.

I am going to wrap up markup extensions sometime today or tomorrow and we'll call v2.0 done and start working on v2.1 ... actually we should call v2.1 v2.0.1 haha... it's really just documentation and code quality issues.  I will update the milestone to reflect this.

And yes... extensions are compatible with each other.  The only ones that work together (or really, require a dependency to another) is the `DeferredReferenceExtension` (it requires the `ReaderContextExtension`).  Everything else _should_ "just work", but without tests that is impossible to verify.

**Comment by Mike-EEE** [comment]
Update here... have been working on my new virtualized (Hyper-V) environment.  I have another day or so of setup and then I will be back up to speed to start coding again. 

Also, I did try to upgrade to 2017 and encountered problems as expected.  I have created a branch with the problems @ https://github.com/Mike-EEE/ExtendedXmlSerializer/tree/VS2017 for @unniravindranathan to check out.  I just happened to have a phone call with him a couple weeks ago and he asked to send along any issues I encountered, so here we go. 😄 (Thanks again, Unni!)

**Comment by wojtpl2** [comment]
I am impressed by your commitment to the project. Thanks a lot.

**Comment by Mike-EEE** [comment]
Hey thanks... I am rounding out my environment today or tomorrow.  Then unfortunately I have to take care of my storage now that the weather is a little better here, as well as some items here with the new environment.  So I am thinking maybe next Wednesday or so at the latest I should _finally_ be back to coding and won't stop until this is done. :P

**Comment by Mike-EEE** [comment]
Woooooooohooo... FINALLY got this sucker up and running again!  Thanks again so much for your patience.  I should be running full steam ahead from now on... once I get the tooling figured out. 👼   (Seriously, in addition to VS2017 I am also using [GitExt](https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions) for my Git solution -- SO MANY NEW THINGS!!!)

I've created a [restart](https://github.com/wojtpl2/ExtendedXmlSerializer/tree/restart) branch that will serve as the intern branch until I get all tests passing again.  I just upgraded to VS2017, got projects building, and pushed it.

It appears we now have two document projects:
- `ExtendedXmlSerializer.DocGenerator`
- `ExtendedXmlSerializer.Documentation`

Two things I see:

- [ ] `ExtendedXmlSerializer.Documentation` does not load.
- [ ] Would it be possible to rename `ExtendedXmlSerializer.DocGenerator` to `ExtendedXmlSerializer.Documentation.Generator` ?

**Comment by Mike-EEE** [comment]
(I've also removed the `breaking change` label as this label should be used for scenarios that are for consumers of our compiled code, not source code.)

**Comment by Mike-EEE** [comment]
Two more thoughts here:

- In case it wasn't clear, `restart` is incredibly broken right now.  Please do not run tests expecting them to work.  It is basically in the middle of a refactor, unfortunately.  My goal is to get this back up and running ASAP.
- Check out [this](https://github.com/leddt/visualstudio-colors-solarized/blob/master/vs2017/solarized-dark.vssettings) plus Dark Theme when you get the chance.  It's how I am developing in VS2017! 👍

**Comment by Mike-EEE** [comment]
Oh yeah, VS2017 is still a mess, unfortunately.  My IDE has locked up 3 times now simply editing a csproj.  Really incredible this still happens, especially with all of the testing and fixes that has gone around this.  Consider this thread a running log now of all things terrible I find with VS2017. 😛 

To start with, it seems that while compiling a `TargetFramework` of .NET Core 1.1 (`netcoreapp1.1`) with a .NET Standard 1.6 library works, and compiling a `TargetFramework` of .NET Framework 4.6 (`net46`) with a .NET Standard 1.6 library works, compiling with a dual `TargetFrameworks` of `netcoreapp1.1;net46` does not, and results in errors.  Again, seems like such a simple, common scenario that should "just work" at this point, but alas, it does not.

No turning back now. The obstacle ahead is the way.  I will submit issues and update/reference them here accordingly.

**Comment by wojtpl2** [comment]
You can change ExtendedXmlSerializer.DocGenerator to ExtendedXmlSerializer.Documentation.Generator. This application generate documentation. Before run this application you have to run Example application. 

ExtendedXmlSerializer.Documentation needs to https://github.com/EWSoftware/SHFB/releases. It is VS plugin. I've written about it.

Compilation with dual `TargetFrameworks `of `netcoreapp1.1;net46` has been working in VS 2015. You have right it is common scenario. unbelievable ;)

**Comment by Mike-EEE** [comment]
OK cool.  I thought I had installed SHFB but will double-check.  

I just got an answer to the multi-target compilation.  Turns out it's the _exact_ framework that is found in list of [supported frameworks](https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support).

So, if we support .NET Standard 1.2 we can support both 4.5.1 and .NET Core 1.1.  This greatly simplifies our library (no more #defines!), and takes care of #107 to boot. 👍

**Comment by wojtpl2** [comment]
We have `#if` in some place eg: https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests/ExtensionModel/Xml/ExtendedXmlSerializerTests.cs#L205-L213
or
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/a12ee8bc2bbb6c5f6f68658400bca91765859719/src/ExtendedXmlSerializer/Cache/TypeDefinitionCache.cs#L54-L82

And we still need it 
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/a12ee8bc2bbb6c5f6f68658400bca91765859719/src/ExtendedXmlSerializer/Cache/TypeDefinitionCache.cs#L54-L82

**Comment by Mike-EEE** [comment]
Correct. Now that the cement is settled, it might be time to introduce a more structured way to provide platform-specific resources.  I will create a new issue.

**Comment by Mike-EEE** [comment]
This is now complete in the latest v2 branch.
