### ISSUE TITLE
Attached Properties Extension

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#94]
The hits continue along here.  On the heels of markup extension support, I am going to attempt to add [attached properties](https://msdn.microsoft.com/en-us/library/ms749011%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) support, but make them a bit more powerful/flexible than System.Xaml and Xamarin.Forms xaml reader and make it so that it works on POCOs.  System.Xaml and Xamarin.Forms have their own "bindable objects" that are coupled to this feature.  The idea here is that you should be able to attach a property to any POCO and have it serialize/deserialize.

This is my weekend project.  Let's see how I do. :)

**Comment by Mike-EEE** [comment]
An update on this.  I actually got writing in relatively easily.  The reading is another matter altogether.  I sort of got caught up with refactoring this and #95, so I am in a bit of a mess right now. ;)  I hope to have something to commit in the next day or so.

Also @wojtpl2, please email me when you can: michael at dragonspark dot us.

**Comment by Mike-EEE** [comment]
An update here.  I got a little sidetracked with Real Life this week.  Getting back into this now.  I hope to have this done by the weekend and then #95 done by next week.

Not sure if you heard, but [ReSharper 2017.1](https://blog.jetbrains.com/dotnet/2017/04/03/meet-resharper-ultimate-2017-1/) launched, as well as [an update for VS2017](https://blogs.msdn.microsoft.com/visualstudio/2017/04/05/visual-studio-2017-update/). From the looks of the comments, VS still sounds like a disaster, however. 😆

**Comment by wojtpl2** [comment]
Thank for your effort!

**Comment by Mike-EEE** [comment]
Sure thing. :)  Almost there.  Got everything but JSON.  The files/classes are named a little odd right now (ie `IContentAdapter`).  That will be the first thing I fix before I really start getting into it.  The other good news is that our performance is back. 😄   I am getting 34.9 serialization and 44.6 deserialization. 👍 

This issue is also complete, as well.
