### ISSUE TITLE
NuGet Error

### ISSUE THREAD

**Issue by Mike-EEE** [wojtpl2/ExtendedXmlSerializer#96]
FWIW, I tried installing alpha3 on a .NET 4.5.1 project and got the following:

![](https://content.screencast.com/users/Mike-EEEE/folders/Jing/media/85f7c060-5e77-4d49-95c0-859b4c772f01/2017-04-15_0452.png)

This project is/was using the old Nuget (v2 -- packages.config), so I am not sure if that is supported or not.

**Comment by wojtpl2** [comment]
I'll check this.

**Comment by wojtpl2** [comment]
This issue should be fixed.
