### ISSUE TITLE
Version 2.0 do not support System.Windows.Point

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#97]
Version 1.5 support System.Windows.Point, version 2.0 don't.

**Comment by wojtpl2** [comment]
There is exception:
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The serializer for type 'System.Windows.Point' could not be found.  Please ensure that the type is a valid type can be activated.
  Source=ExtendedXmlSerializer
  StackTrace:
       w ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\RuntimeSerializer.cs:wiersz 53
       w ExtendedXmlSerializer.ContentModel.DecoratedWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:wiersz 37
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Body(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 41
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 35
       w ExtendedXmlSerializer.ContentModel.ConditionalWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\ConditionalWriter.cs:wiersz 44
       w ExtendedXmlSerializer.ContentModel.AlteringWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\AlteringWriter.cs:wiersz 40
       w ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:wiersz 46
       w ExtendedXmlSerializer.ContentModel.Members.MemberListWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberListWriter.cs:wiersz 43
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:wiersz 71
       w ExtendedXmlSerializer.ContentModel.DeferredSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DeferredSerializer.cs:wiersz 40
       w ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\RuntimeSerializer.cs:wiersz 53
       w ExtendedXmlSerializer.ContentModel.DecoratedWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:wiersz 37
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Body(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 41
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 35
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\CircularReferenceEnabledSerialization.cs:wiersz 61
       w ExtendedXmlSerializer.ExtensionModel.References.DeferredReferenceSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\DeferredReferenceSerializer.cs:wiersz 60
       w ExtendedXmlSerializer.ContentModel.Collections.EnumerableWriter.Write(IFormatWriter writer, IEnumerable instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Collections\EnumerableWriter.cs:wiersz 46
       w ExtendedXmlSerializer.ContentModel.WriterBase`1.ExtendedXmlSerializer.ContentModel.IWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\WriterBase.cs:wiersz 30
       w ExtendedXmlSerializer.ContentModel.Collections.MemberedCollectionWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Collections\MemberedCollectionWriter.cs:wiersz 40
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:wiersz 71
       w ExtendedXmlSerializer.ExtensionModel.References.DeferredReferenceContent.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\DeferredReferenceContent.cs:wiersz 65
       w ExtendedXmlSerializer.ContentModel.DecoratedWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:wiersz 37
       w ExtendedXmlSerializer.ContentModel.Members.VariableTypedMemberWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\VariableTypedMemberWriter.cs:wiersz 61
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ContentModel.DecoratedWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:wiersz 37
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Body(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 41
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 35
       w ExtendedXmlSerializer.ContentModel.ConditionalWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\ConditionalWriter.cs:wiersz 44
       w ExtendedXmlSerializer.ContentModel.AlteringWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\AlteringWriter.cs:wiersz 40
       w ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:wiersz 46
       w ExtendedXmlSerializer.ContentModel.Members.MemberListWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberListWriter.cs:wiersz 43
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:wiersz 71
       w ExtendedXmlSerializer.ContentModel.DecoratedWriter.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:wiersz 37
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Body(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 41
       w ExtendedXmlSerializer.ContentModel.Content.EnclosureBase.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\EnclosureBase.cs:wiersz 35
       w ExtendedXmlSerializer.ContentModel.Serializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:wiersz 39
       w ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\CircularReferenceEnabledSerialization.cs:wiersz 61
       w ExtendedXmlSerializer.ExtensionModel.References.DeferredReferenceSerializer.Write(IFormatWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\DeferredReferenceSerializer.cs:wiersz 60
       w ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:wiersz 55
       w ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\InstanceFormatter.cs:wiersz 50
       w ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, IXmlWriterFactory factory, Func`1 stream, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:wiersz 132
       w ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, Object instance) w C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:wiersz 118
       w ConfigurationTool.Common.Project.ProjectManager.SaveProject(SerializableProject serializableProject, String pathToProjectFile) w C:\Work\vat_ct_svn\trunk\ConfigurationTool\ConfigurationTool.Model\Project\ProjectManager.cs:wiersz 20
       w ConfigurationTool.Windows.MainWindow.SaveProject() w C:\Work\vat_ct_svn\trunk\ConfigurationTool\ConfigurationTool\Windows\MainWindow.xaml.cs:wiersz 174
       w ConfigurationTool.Windows.MainWindow.SaveAsProject() w C:\Work\vat_ct_svn\trunk\ConfigurationTool\ConfigurationTool\Windows\MainWindow.xaml.cs:wiersz 199
       w ConfigurationTool.Controls.MenuBar.SaveAsProject_OnClick(Object sender, RoutedEventArgs e) w C:\Work\vat_ct_svn\trunk\ConfigurationTool\ConfigurationTool\Controls\MenuBar.xaml.cs:wiersz 206
       w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       w System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       w System.Windows.Threading.DispatcherOperation.InvokeImpl()
       w MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       w MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       w System.Windows.Threading.DispatcherOperation.Invoke()
       w System.Windows.Threading.Dispatcher.ProcessQueue()
       w System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       w System.Windows.Application.RunDispatcher(Object ignore)
       w System.Windows.Application.RunInternal(Window window)
       w ConfigurationTool.App.Main()
       w System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       w System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       w Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       w System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by wojtpl2** [comment]
I've checked it in previous build of version 2 (before alpha) and it was working.

**Comment by wojtpl2** [comment]
I've added tests for Point. You have to build and run test by .\build.ps1 from console. Visual Studio runs test only for .net core.

**Comment by wojtpl2** [comment]
There is tests log:
https://ci.appveyor.com/project/wojtpl2/extendedxmlserializer/build/84/tests

**Comment by Mike-EEE** [comment]
Yes, if it worked in v1 it most definitely should work in v2. :)  The output might be different, but it should definitely work.  I will look into this.

I just spent the past two days tracking down another Benchmark.NET issue. Turns out all the problems I have been encountering is due to x64!  I will have to look into it, but with a simple test, x86 was faster:
https://github.com/Mike-EEE/Stash/tree/master/BenchmarkDotNet.Gc

Maybe we switch to x86 for now?  I have spent sooooo much time on performance. :(  It's actually easy to switch Benchmark.NET to x86: http://benchmarkdotnet.org/Configs/Jobs.htm

I am thinking of opening up an issue on their repo just to be sure.

**Comment by Mike-EEE** [comment]
Also, be sure to add as many breaking tests as you can. :)  I WILL FIX THEM!!!

**Comment by wojtpl2** [comment]
I have question about TestObject. I see that there is many unused objects. Can I add test for them? Where should I add this tests?

**Comment by Mike-EEE** [comment]
I think they are there from legacy.  The test project could probably use some work. :)   Feel free to add/use/move to make it better. 👍

**Comment by wojtpl2** [comment]
We can switch benchmark tests to x86.

**Comment by wojtpl2** [comment]
There is example in v1.5: [Point.zip](https://github.com/wojtpl2/ExtendedXmlSerializer/files/950708/Point.zip)

**Comment by wojtpl2** [comment]
It isn't working in ExtnededXmlSerializer.Legacy.

**Comment by Mike-EEE** [comment]
So this _doesn't_ work in 1.5?  If there was a test for this in 1.5, then it should be working because all of those tests are passing in ExtnededXmlSerializer.Tests.Legacy.

**Comment by wojtpl2** [comment]
It was working in v1.5. 
We don't have test for it but it is simple struct with two properties. It was working and It have to work.

**Comment by wojtpl2** [comment]
Check project from above attachment: Point.zip.

**Comment by Mike-EEE** [comment]
Ahhhhhhh well that is a problem then. ;)  I have been coding around passing tests.  Or what I do is look through the Legacy tests and then try them in 2.0.  Please make sure we get those tests in!  We should have one for 1.5 (Legacy) and 2.0.

Also, as for x86 benchmarking, that ended up not being the problem, so we'll stick w/ x64 after all.

**Comment by wojtpl2** [comment]
Ok. If you wish, I'll add test for Legacy code.

**Comment by wojtpl2** [comment]
Added

**Comment by wojtpl2** [comment]
It was working in v2 before Alpha1 when I fount #87.

**Comment by Mike-EEE** [comment]
OK this has been fixed.  Please try it out and let me know if there is anything further that is needed around this one.  Sorry for the delay!
