### ISSUE TITLE
Class with property interface of List

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#98]
If you have class:

```C#
class ClassWithPropertyInterfaceOfList
        {
            public IList<string> List { get; set; }
            public IDictionary<string, string> Dictionary { get; set; }

            public ISet<string> Set { get; set; }
        }
```

and create object:
```c#
            var expected = new ClassWithPropertyInterfaceOfList
            {
                List = new List<string> { "Item1" },
                Set = new HashSet<string> { "Item1" },
                Dictionary = new Dictionary<string, string> { { "Key", "Value" } }
            };
```

I've got exception:

ExtendedXmlSerializer.ExtensionModel.References.CircularReferencesDetectedException was unhandled by user code
  HResult=-2146233088
  Message=The provided instance of type 'ExtendedXmlSerializer.Tests.ExtensionModel.Xml.ExtendedXmlSerializerTests+ClassWithPropertyInterfaceOfList' contains circular references within its graph. Serializing this instance would result in a recursive, endless loop. To properly serialize this instance, please create a serializer that has referential support enabled by extending it with the ReferencesExtension.
  Source=ExtendedXmlSerializer
  StackTrace:
       at ExtendedXmlSerializer.ExtensionModel.References.ReferenceAwareSerializers.Serializer.Write(IFormatWriter writer, Object instance) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceAwareSerializers.cs:line 77
       at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:line 55
       at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\InstanceFormatter.cs:line 50
       at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, IXmlWriterFactory factory, Func`1 stream, Object instance) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 132
       at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, Object instance) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 118
       at ExtendedXmlSerializer.Tests.Support.SerializationSupport.Assert[T](T instance, String expected) in C:\Work\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\Support\SerializationSupport.cs:line 46
       at ExtendedXmlSerializer.Tests.ExtensionModel.Xml.ExtendedXmlSerializerTests.PropertyInterfaceOfList() in C:\Work\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\ExtensionModel\Xml\ExtendedXmlSerializerTests.cs:line 205
  InnerException: 

I'll add test to repo.

**Comment by wojtpl2** [comment]
It was working in v1.5.

**Comment by Mike-EEE** [comment]
Maybe we should work on the exception message (it's a little old)?

> Serializing this instance would result in a recursive, endless loop. To properly serialize this instance, please create a serializer that has referential support enabled by extending it with the ReferencesExtension.

Should be:

> Serializing this instance would result in a recursive, endless loop. To properly serialize this instance, please create a serializer that has references enabled by calling the EnableReferences extension method.


Try that out and let me know how it goes.  It should work. 👼

**Comment by wojtpl2** [comment]
I don't understand. What should I do? 
I don't see any reference in this example.

**Comment by wojtpl2** [comment]
For me it should work without configuration.

**Comment by Mike-EEE** [comment]
Doh!  You are correct.  I thought this was a reference class by the title.  That's what I get for reading this while working out. :)  I will look into this.  (I'll also fix that message, too).

**Comment by wojtpl2** [comment]
Ok thanks!
I've already added a failed test.

**Comment by wojtpl2** [comment]
There is test in Legacy code: ExtendedXmlSerializer.Tests.Legacy.TestObject.TestClassPropertyInterfaceOfList

**Comment by wojtpl2** [comment]
There is legacy test: https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests.Legacy/SerializationPropertyInterfaceOfListTest.cs#L30-L45

**Comment by Mike-EEE** [comment]
Ahhh... guess what?  This is working exactly as designed.  It's a little tricky, but that `"Item1"` is a reference in the object graph.  If you change the 2nd one to `"Item2"` it will serialize as expected without an error.  Here is what it looks like when you enable references:

```
<?xml version="1.0" encoding="utf-8"?>
<ExtendedXmlSerializerTests-ClassWithPropertyInterfaceOfList xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ExtensionModel.Xml;assembly=ExtendedXmlSerializer.Tests">
	<List xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="sys:List[sys:string]">
		<Capacity>4</Capacity>
		<sys:string exs:identity="1">Item1</sys:string>
	</List>
	<Dictionary xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="sys:Dictionary[sys:string,sys:string]">
		<sys:Item>
			<Key>Key</Key>
			<Value>Value</Value>
		</sys:Item>
	</Dictionary>
	<Set xmlns:ns1="clr-namespace:System.Collections.Generic;assembly=System.Core" xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="ns1:HashSet[sys:string]">
		<sys:string exs:reference="1" />
	</Set>
</ExtendedXmlSerializerTests-ClassWithPropertyInterfaceOfList>
```

You can see it is using `exs:reference` to point to the previous string (a reference).  This seems a little overkill with a simple string, but imagine if there is a long string/message/text.  If it occurs one than once in the object graph, they will all point to the same one automatically (with references enabled, of course).

It's a little different from v1, but more powerful.  However, I am open to suggestions on any better way to handle this for the user.  We could probably print out the references. In the case of strings, this will print out the strings themselves, leading to less confusion.

**Comment by wojtpl2** [comment]
For me it is wrong designed. Valuable types (and string too) shouldn't be used as referenced object.
Eg, If you have list of `Person`:
```C#
public class Person{
   public string Name { get; set; }
   public int salary { get; set; }
}

List<Person> list = new List<Person>()
```
And you have on the list many items ( >= 1000) and many the same names (eg. Mike). With this design won't be able to read xml because in many places you will have references to other items.

And if I had:
```C#
            var expected = new ClassWithPropertyInterfaceOfList
            {
                List = new List<string> { "Item1" },
                Set = new HashSet<string> { "Item1" },
                Dictionary = new Dictionary<string, string> { { "Key", "Value" } }
            };
```
The first Item1 is another object from the second Item1. If you deserialize your xml you will have one string. If you change first Item1 you change second object too, don't you?

**Comment by Mike-EEE** [comment]
OK good points.  Maybe we can have a type collection property on `ReferencesExtension` for `IgnoredTypes`, and by default `string` is in there?

**Comment by wojtpl2** [comment]
It is good solution for now.  
Do you know what will happen with class Point. It be working if I would have many the same Points?

**Comment by Mike-EEE** [comment]
Point is a value type so it would not be considered for references.  String is really the only fuzzy/questionable type because it does seem like a primitive type (and is actually a "primitive" type, heh), but it is a reference/class type.  Confusing I know. :)

**Comment by Mike-EEE** [comment]
Alright, this is now done.  Please see `PropertyInterfaceOfList`, `PropertyInterfaceOfListEnabledReferences`, and `PropertyInterfaceOfListReferencesCleared` in `ReferencesExtensionTests` for examples.

**Comment by wojtpl2** [comment]
Great! Thanks!
I will check it tomorrow.

**Comment by wojtpl2** [comment]
I cun't run this tests. I have trouble because I have VS 2017 update 3 preview 6 and .net core 2.0. In this version I can't run unit tests. I got some error message. It is issue in VS. 
I need to have this version VS for another project.

**Comment by Mike-EEE** [comment]
Ahhh no worries.  I was using R# EAP and it wasn't able to debug tests until EAP9.  Funny how it is 3 months after launch and nothing really works still haha.  Let me know when you are able to test and check it out. 👍

**Comment by Mike-EEE** [comment]
I believe this is working as expected now.  Please feel free to comment/re-open this issue if not. :)

**Comment by MagicAndre1981** [comment]
I also get this ExtendedXmlSerializer.ExtensionModel.References.CircularReferencesDetectedException even when I create it this way: `var serializer = new ConfigurationContainer().EnableReferences().Create();`

This is happens with EF6 data model where class foo has `public virtual bar Bar { get; set; }` and class bar has `public virtual ICollection<foo> Foo { get; set; }`. 

With Json needed to ignore the entries, this is why I play with ExtendedXmlSerializer, but it also fails.

**Comment by Mike-EEE** [comment]
Can you provide a reproducible test, @MagicAndre1981?  I tried using your schema above and it seems to pass:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/363b584f1a4a62ef764bf70a782bab95ab23fe51/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue98Tests.cs#L11-L40

**Comment by MagicAndre1981** [comment]
not really. I'm already playing with a console demo, but here it works with the Employee database of Firebird. btw EF6 uses new `HashSet<Foo>()`, so I have no idea if this makes a difference.

**Comment by Mike-EEE** [comment]
Ah OK.  Sounds like the failure is occurring on EF6's end, if I understand correctly. A quick test of `Hashset` on our end seems to work as expected.  If you do find a reproducible failure, please let us know and we'll take a look at it. 👍

**Comment by MagicAndre1981** [comment]
I still don't understand this message. From Callstack I can see that I the CircularReferenceEnabledSerialization is used.

I want to serialize a `list<foo>` to save it with [Application.Current.Properties](https://docs.microsoft.com/en-US/xamarin/xamarin-forms/app-fundamentals/application-class#properties-dictionary)  which has several of those virtual entries which are used by EF for Foreign Key access to linked table. And this linked table has reference back with a `virtual ICollection` property.

**Comment by Mike-EEE** [comment]
Looks to be working here:
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/34ca6295e3a182670e9269ae002bdf8cf30c0efb/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue98Tests.cs#L32-L51

Sorry @MagicAndre1981, English just gets in the way. 😂  You are going to need to create a simple hello world example (Console application) and post it in your GitHub somewhere.  

I can then take a look at it to see if I can assist further. 👍

**Comment by MagicAndre1981** [comment]
ok, the code stops because I [configured VS to stop at this exception](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2017#tell-the-debugger-to-break-when-an-exception-is-thrown). I see the code works and generates XML and deserialized objects include the references again. 

I see you catch the exception and ignore it by still writing the content in `ReferenceAwareSerializers.cs`

```
catch (CircularReferencesDetectedException e)
{
     e.Writer.Write(writer, instance);
}
```

I configured VS to stop because I saw this CircularReferencesDetectedException before app closes and debugging stops 🤔 🤷‍♂️

**Comment by Mike-EEE** [comment]
Ah!  So it seems like a development environment-specific issue then, @MagicAndre1981?  And one that occurs on exit?

FWIW, indeed we check for that exception on a container configured with `EnableReferences` and continue writing instead.  That is, we handle the exception in this case whereas the default behavior is to throw.

**Comment by MagicAndre1981** [comment]
> FWIW, indeed we check for that exception on a container configured with `EnableReferences` and continue writing instead. That is, we handle the exception in this case whereas the default behavior is to throw.

this confused me. So the app was not crashing because of this, but something else, but last exception was the `CircularReferencesDetectedException` and I configured VS to stop at `CircularReferencesDetectedException` and wondered why it gets thrown when I already called `EnableReferences()`

**Comment by Mike-EEE** [comment]
> and wondered why it gets thrown when I already called EnableReferences()

That's a good point, @MagicAndre1981.  Try/Catch incurs a performance hit as well, so it might be better to maybe put that in a handler of some sort and use that instead.  The default handler throws the exception and a container configured with `EnableReferences` will handle it instead.

Something to carry forward with v3. :)

**Comment by MagicAndre1981** [comment]
> Something to carry forward with v3. :)

should I open a new issue on this or will you do this?

**Comment by Mike-EEE** [comment]
v3 it's an unofficial project at the moment, and I probably shouldn't have mentioned it.  Trying to pump myself into it. 😆

For some context, the _plan_ is to create [a new serializer as a separate project that supports numerous formats](https://github.com/SuperDotNet/Super.NET/issues/15) and then have ExtendedXmlSerializer be the XML version (along with classical support).

I emphasize _plan_ as every developer has a plan until their code punches them in their face. 🤣  That's how it is for me, anyway.

In any case, I have captured our discussion here:
https://github.com/SuperDotNet/Super.NET/issues/27

**Comment by MagicAndre1981** [comment]
ok, I notice that the performance is bad. Serialization of a List<foo> with the references to other classes and around 1 items takes several seconds (4-5).

Are there any plans for logging (ETW EventSource based) that would help pinpoint slow parts?

**Comment by Mike-EEE** [comment]
Ah, is this in debug mode, by chance @MagicAndre1981?  If an exception occurs in debug mode, there is a performance hit for sure (especially if you are emitting them in debug/console window), but in release mode it should operate more along expectations.

**Comment by MagicAndre1981** [comment]
happens in both (debug and release, where release is only a bit faster)

**Comment by Mike-EEE** [comment]
Bummer.  If you can provide a simple repro/object graph in a new issue I will take a look at it to see if there is an obvious issue at play.

**Comment by MagicAndre1981** [comment]
Here is what happens when I serialize the list:

![image](https://user-images.githubusercontent.com/8274816/62049418-793ff900-b20f-11e9-9584-d286f3714155.png)

Do you see anything to improve it?

**Comment by Mike-EEE** [comment]
Looks like something isn't getting cached correctly.  If you are able to create a simple hello world repro in a new issue, I can take a look into it. 👍

**Comment by MagicAndre1981** [comment]
ok, I have now a small demo with Employee database of Firebird where a list of 42 items take 1.3s to serialize. Is this slow enough? What are expected times such serializing should take?

**Comment by Mike-EEE** [comment]
Ah, I am a bit confused on what you mean by Firebird/database, @MagicAndre1981.  Ideally, a simple Hello World demo is using ExtendedXmlSerializer exclusively without any other components such as a database or other APIs.  Then we know for certain it is our library without others being the culprit, if that makes sense.

My concern here is that your object graph is exposing a bug on our end that has yet to be discovered, which is why I am curious on how you're configuring/using our API for further discovery.

**Comment by MagicAndre1981** [comment]
the data come from databases all time, to avoid network calls I currently use JSON to serialize them, but without references, when I use the cached data again, I need to do more network calls to fetch the reference data.

The graphic only show calls which occur during serializing in your lib, no other code.

If you don't want a demo with database calls I'm out here and can't help.

**Comment by Mike-EEE** [comment]
Ah, OK @MagicAndre1981.  What I would need to assist you is a simple Hello World .NET Core Console application hosted on your GitHub somewhere that demonstrates the issue.  Once you make that available I can further investigate to see if there is something obvious in your object graph that is causing the performance issue (or if there is one).

By the looks of the dotTrace graphic above, it would seem that the lambda expressions we are compiling are not being cached, but it is difficult to know for certain without being able to see the code/graph you are using to produce such results.

> If you don't want a demo with database calls

To be certain, I _do_ want a demo _without_ database calls. 😁
